### PR TITLE
[fix] #4211: Fix call blocking methods within async context

### LINKED ISSUE #4211: Async blocking bug

### PR DESCRIPTION
**Pull request by Erigara**
## Description

Followup fix for the same problem in benchmarks.

### Linked issue

Closes #4211 

### Benefits

Benchmarks works.

### CODE REVIEW

**Review by VAmuzing — APPROVED** [review]

File: core/benches/blocks/apply_blocks_oneshot.rs [hunk 1]
```diff
@@ -9,10 +9,16 @@ mod apply_blocks;
...
-    iroha_logger::test_logger();
+fn main() {
+    let rt = tokio::runtime::Builder::new_multi_thread()
+        .enable_all()
+        .build()
+        .expect("Failed building the Runtime");
+    {
+        let _guard = rt.enter();
+        iroha_logger::test_logger();
+    }
```
Comment (Arjentix) [inline core/benches/blocks/apply_blocks_oneshot.rs:20]: Logger needs runtime context...?

**Review by Arjentix — APPROVED** [review]

File: core/benches/blocks/apply_blocks_oneshot.rs (hunk 1 above)
Comment (Erigara) [reply core/benches/blocks/apply_blocks_oneshot.rs:20]: yes, initialization of logger, `LoggerHandle::new` calls `tokio::spawn`
