### PR TITLE
fix: address `check-cfg` warnings + chores

### LINKED ISSUE #4993: Unexpected feature flags
Since updating to Rust 1.80.0, which checks cfgs at compile-time, I've been noticing warnings about unexpected feature flags all over the project:

- unexpected `cfg` condition value: `ffi_import` (feature flag is commented out, might be related to https://github.com/hyperledger/iroha/issues/3102)
- unexpected `cfg` condition name: `crate_type` (seems unsupported: https://github.com/rust-lang/rust/issues/20267)
- unexpected `cfg` condition value: `metric-instrumentation` (feature flag missing)

### PR DESCRIPTION
**Pull request by 0x009922**
## Context

Close #4993 (see context there)

I found yet another time that metrics & telemetry is broken in Iroha. This PR doesn't fix it, but disables more parts of it to remove noisy warnings. Main issue is #5134 

### Migration Guide (optional)

---

### Checklist

- [x] I've read [`CONTRIBUTING.md`](../CONTRIBUTING.md).
- [ ] (optional) I've written unit tests for the code changes.
- [ ] All review comments have been resolved.
- [ ] All CI checks pass.

### CODE REVIEW

File: crates/iroha_derive/tests/ui.rs [hunk 1]
```diff
@@ -1,4 +1,3 @@
-#![cfg(not(coverage))]
```
Comment (0x009922) [inline crates/iroha_derive/tests/ui.rs:1]: Accidental noise from local work - no need to remove this.

But it is harmful and was useless anyway.

**Review by DCNick3 — APPROVED** [review]

File: crates/iroha_telemetry_derive/src/lib.rs [hunk 2]
```diff
@@ -256,34 +264,34 @@ fn impl_metrics(emitter: &mut Emitter, _specs: &MetricSpecs, func: &syn::ItemFn)
...
     let inc_metric = |spec: &MetricSpec, kind: &str| {
         quote!(
-            #metric_arg_ident
-                .metrics
-                .isi
-                .with_label_values( &[#spec, #kind ]).inc();
+            // #metric_arg_ident
+            //     .metrics
+            //     .isi
+            //     .with_label_values( &[#spec, #kind ]).inc();
```
Comment (mversic) [inline crates/iroha_telemetry_derive/src/lib.rs:285]: was this intended?

Comment (mversic) [reply crates/iroha_telemetry_derive/src/lib.rs:285]: if so, make it a ticket

File: Cargo.toml [hunk 3]
```diff
@@ -149,6 +149,12 @@ rust.single_use_lifetimes = "warn"
 rust.unused_lifetimes = "warn"
 # TODO: reenable
 # rust.unsafe_op_in_unsafe_fn = "deny"
+rust.unexpected_cfgs = { level = "warn", check-cfg = [
+    # FIXME: https://github.com/hyperledger/iroha/issues/3102
+    'cfg(feature, values("ffi_import"))',
+    # FIXME: was never supported
+    'cfg(coverage)'
```
Comment (mversic) [inline Cargo.toml:156]: how about you make a ticket?

File: crates/iroha_telemetry_derive/src/lib.rs (hunk 2 above)
Comment (0x009922) [reply crates/iroha_telemetry_derive/src/lib.rs:285]: There is no `.metrics` field anymore. This macro is just broken, but is still used in many places. I decided to remove codegen from it rather than removing it from everywhere.

File: crates/iroha_telemetry_derive/src/lib.rs [hunk 4]
```diff
@@ -237,9 +245,9 @@ fn impl_metrics(emitter: &mut Emitter, _specs: &MetricSpecs, func: &syn::ItemFn)
     };
 
     #[cfg(feature = "metric-instrumentation")]
-    let res = {
-        let (totals, successes, times) = write_metrics(_metric_arg_ident, _specs);
-        quote!(
+    {
+        let (totals, successes, times) = write_metrics(metric_arg_ident, specs);
+        return quote!(
```
Comment (mversic) [inline crates/iroha_telemetry_derive/src/lib.rs:250]:
```suggestion
       quote!(
```

I don't think you need a return

File: crates/iroha_telemetry_derive/src/lib.rs (hunk 2 above)
Comment (DCNick3) [reply crates/iroha_telemetry_derive/src/lib.rs:285]: There is already a ticket about this, https://github.com/hyperledger/iroha/issues/3910

File: Cargo.toml (hunk 3 above)
Comment (0x009922) [reply Cargo.toml:156]: https://github.com/hyperledger/iroha/issues/5139

Comment (0x009922) [reply Cargo.toml]: Actually it is not a bug (https://github.com/hyperledger/iroha/issues/5139#issuecomment-2401284049). I will leave a better comment here.

**Review by mversic — APPROVED** [review]

**Comment by dmitrivenger** [comment]
@mversic can we move this task to done?
