### PR TITLE
[fix] #2232: Make Iroha print meaningful message when genesis has too many isi

### LINKED ISSUE #2232: When genesis transaction has too many `isi`, Iroha prints meaningless message
## Description

I've generated sample genesis files with different sizes. It turned out that starting from ~1425..1437 count of ISI Iroha doesn't accept genesis.

### Expected

Expected genesis to be submitted or rejected with a message like "Your genesis transaction has too many instructions"

### Actual

> 2022-05-19T08:18:35.088297Z ERROR iroha_core::sumeragi::fault: Failed to submit genesis transactions error=Genesis transactions set is empty.

### Additional details

Sample genesis with 1437 isi: https://pastebin.com/d0GbajXZ

### PR DESCRIPTION
**Pull request by Arjentix**
Signed-off-by: Daniil Polyakov <arjentix@gmail.com>

### Description of the Change

* Added error message when can't process genesis transaction
* Logger initialization now starts eralier to be able to capture genesis creating logs

### Issue

* Closes #2232 
* Opens #2238 

### Benefits

Now users will get more meaningful message when they have too many instructions inside transactions

### Possible Drawbacks

None

### Usage Examples or Tests

You can take a big genesis from issue description and run Iroha with it to check this out.

I don't think I can write a test for it. This is UI-specific problem

### CODE REVIEW

File: cli/src/lib.rs [hunk 1]
```diff
@@ -96,11 +96,15 @@ where
     /// To make `Iroha` peer work all actors should be started first.
     /// After that moment it you can start it with listening to torii events.
     ///
+    /// # Side effect
```
Comment (appetrosyan) [inline cli/src/lib.rs:99]: Good practice.

File: cli/src/lib.rs [hunk 2]
```diff
@@ -137,22 +146,18 @@ where
...
         query_validator: IsQueryAllowedBoxed<K::World>,
         broker: Broker,
+        telemetry: Option<iroha_logger::Telemetries>,
     ) -> Result<Self> {
         if !config.disable_panic_terminal_colors {
-            if let Err(e) = color_eyre::install() {
-                iroha_logger::error!("Tried to install eyre_hook twice: {:?}", e);
-            }
+            // Ignoring error if `iroha_logger` has already installed colors
+            let _color_res = color_eyre::install();
```
Comment (appetrosyan) [inline cli/src/lib.rs:159]: I think we should still log it. Maybe `debug`.

File: client/tests/integration/restart_peer.rs [hunk 3]
```diff
@@ -24,7 +24,13 @@ fn restarted_peer_should_have_the_same_asset_amount() -> Result<()> {
 
     // Given
     let rt = Runtime::test();
-    rt.block_on(peer.start_with_config_permissions_dir(configuration.clone(), AllowAll, &temp_dir));
+    rt.block_on(peer.start_with_config_permissions_dir(
+        configuration.clone(),
+        GenesisNetwork::test(true),
+        AllowAll,
```
Comment (appetrosyan) [inline client/tests/integration/restart_peer.rs:30]: https://github.com/hyperledger/iroha/issues/2199

Refers to this. The permissions need to be specified inside the genesis block, not hard-coded in the init process.

File: core/src/genesis.rs [hunk 4]
```diff
@@ -196,7 +196,14 @@ impl GenesisNetworkTrait for GenesisNetwork {
 
                     raw_transaction.sign_and_accept(genesis_key_pair, tx_limits)
                 })
-                .filter_map(Result::ok)
+                .enumerate()
+                .filter_map(|(i, res)| {
+                    res.map_err(|error| {
+                        let error_msg = format!("{error:#}");
+                        iroha_logger::error!(error = %error_msg, "Genesis transaction #{i} didn't succeed")
```
Comment (appetrosyan) [inline core/src/genesis.rs:203]:
```suggestion
                        iroha_logger::error!(error = %error_msg, "Genesis transaction #{i} failed")
```

File: core/src/sumeragi/fault.rs [hunk 5]
```diff
@@ -466,7 +466,9 @@ impl<G: GenesisNetworkTrait, K: KuraTrait, W: WorldTrait, F: FaultInjection>
         ctx: &mut Context<Self>,
     ) -> Result<()> {
         if transactions.is_empty() {
-            Err(eyre!("Genesis transactions set is empty."))
+            Err(eyre!(
+                "Genesis transactions set is empty or all of the transactions are incorrect"
```
Comment (appetrosyan) [inline core/src/sumeragi/fault.rs:470]:
```suggestion
                "Genesis transactions set contains no valid transactions"
```

File: data_model/src/transaction.rs [hunk 6]
```diff
@@ -67,14 +67,18 @@ pub trait Txn {
                 let instruction_count: usize = instructions.iter().map(Instruction::len).sum();
 
                 if instruction_count as u64 > limits.max_instruction_number {
-                    return Err(TransactionLimitError(String::from(
-                        "Too many instructions in payload",
+                    return Err(TransactionLimitError(format!(
+                        "Too many instructions in payload, max number is {}",
```
Comment (appetrosyan) [inline data_model/src/transaction.rs:71]:
```suggestion
                        "Too many instructions in payload, max number is {}. Got {}",
```

File: data_model/src/transaction.rs [hunk 7]
```diff
@@ -67,14 +67,18 @@ pub trait Txn {
...
+                        limits.max_instruction_number
                     )));
                 }
             }
             Executable::Wasm(WasmSmartContract { raw_data }) => {
                 if raw_data.len() as u64 > limits.max_wasm_size_bytes {
-                    return Err(TransactionLimitError(String::from("wasm binary too large")));
+                    return Err(TransactionLimitError(format!(
+                        "Wasm binary too large, max size is {}",
```
Comment (appetrosyan) [inline data_model/src/transaction.rs:79]:
```suggestion
                        "Wasm binary too large, max size is {}. Got {}",
```

**Comment by appetrosyan** [comment]
Need to update the tests too
https://github.com/hyperledger/iroha/runs/6514631883?check_suite_focus=true#step:5:186

File: cli/src/lib.rs (hunk 2 above)
Comment (Arjentix) [reply cli/src/lib.rs:159]: When I was running Iroha I saw this error in the log. And after some new commits and rebasing the error dissapeared... So I think, I'll bring back `error` log here

File: data_model/src/transaction.rs (hunk 6 above)
Comment (Arjentix) [reply data_model/src/transaction.rs:71]: I perfer not to use dots in error messages so that error message chain looks better. I'll use comma here

File: cli/src/torii/tests.rs [hunk 8]
```diff
@@ -213,7 +213,7 @@ struct QueryResponseTest {
 
 #[allow(variant_size_differences)]
 enum QueryResponseBody {
-    Ok(VersionedQueryResult),
+    Ok(Box<VersionedQueryResult>),
```
Comment (Arjentix) [inline cli/src/torii/tests.rs:216]: After rebase clippy was warning me about very different variant sizes, so I have to Box it

Comment (appetrosyan) [reply cli/src/torii/tests.rs:216]: consider removing allow.

**Review by s8sato — APPROVED** [review]

**Review by appetrosyan — APPROVED** [review]
