### PR TITLE
[fix] #1404: Verify fixed.

### LINKED ISSUE #1404: Assets cannot be registered and minted in one transaction
Current:
  First need to send transaction with instruction to mint asset, await until it will be committed and only then send transaction to mint the asset

Expected: 
  Instruction to register asset and instruction to mint asset can be committed in one transaction

### PR DESCRIPTION
**Pull request by appetrosyan**
Signed-off-by: Aleksandr <a-p-petrosyan@yandex.ru>

### Description of the Change

Added test to verify that it's possible to both register and mint an asset in one `tx`. 

### Issue

Closes #1404

### Benefits

More tests. 

### Possible Drawbacks

More tests.

### CODE REVIEW

File: core/test_network/src/lib.rs [hunk 1]
```diff
@@ -108,17 +108,17 @@ impl std::cmp::Eq for Peer {}
...
+			r#"ed01207233bfc89dcbd68c19fde6ce6158225298ec1131b6a130d1aeb454c1ab5183c0"#,
+		)
+		.unwrap(),
+		private_key: PrivateKey {
+			digest_function: "ed25519".to_string(),
+			payload: hex_literal::hex!("9AC47ABF 59B356E0 BD7DCBBB B4DEC080 E302156A 48CA907E 47CB6AEA 1D32719E 7233BFC8 9DCBD68C 19FDE6CE 61582252 98EC1131 B6A130D1 AEB454C1 AB5183C0"
+			)
+			.into(),
+		},
+	}
```
Comment (mversic) [inline core/test_network/src/lib.rs:121]: tabs

**Review by mversic — DISMISSED** [review]

**Review by eadventurous — APPROVED** [review]

**Review by mversic — APPROVED** [review]

**Review by mversic — APPROVED** [review]
