### PR TITLE
[fix] #3596: `iroha_client_cli` show blocks/events

### LINKED ISSUE #3596: [BUG]
### OS and Environment

MacOS ventura 13.3, DockerHub

### GIT commit hash

c82f2c09

### Minimum working example / Steps to reproduce

the problem started to be observed from commit a8d62b51d79cb6e9f273b746bcc3530983730ae7

deploy iroha2-dev
deploy client_cli
./iroha_client_cli blocks 1

### Actual result

./iroha_client_cli blocks 1 -> does not display the current state of the blocks, the output in the terminal is empty

### Expected result

./iroha_client_cli blocks 1 -> displays the current state of the blocks

### Logs in JSON format

nothing todo

### Who can help to reproduce?

@timofeevmd

### Notes

_No response_

### PR DESCRIPTION
**Pull request by Erigara**
## Description

Pass closure inside subcomands to do printing. 

### Linked issue

Closes #3596 

### Benefits

Works correctly.

### Checklist

- [x] I've read `CONTRIBUTING.md`
- [x] I've used the standard signed-off commit format (or will squash just before merging)
- [x] All applicable CI checks pass (or I promised to make them pass later)
- [ ] (optional) I've written unit tests for the code changes
- [ ] I replied to all comments after code review, marking all implemented changes with thumbs up

### CODE REVIEW

**Review by Arjentix — APPROVED** [review]
Not sure I'd did it in the same way, but it's fine for me

File: client_cli/src/main.rs [hunk 1]
```diff
@@ -239,23 +250,31 @@ mod events {
...
+            self,
+            cfg: &ClientConfiguration,
+            callback: F,
+        ) -> Result<()> {
             let filter = match self {
                 Args::Pipeline => FilterBox::Pipeline(PipelineEventFilter::new()),
                 Args::Data => FilterBox::Data(DataEventFilter::AcceptAll),
             };
-            listen(filter, cfg)
+            listen(filter, cfg, callback)
```
[the remark this answers is not in the document]
Comment (Erigara) [reply client_cli/src/main.rs:262]: Yes, when you need to serialize and print value you call `callback` and pass your value inside.

File: client_cli/src/main.rs [hunk 2]
```diff
@@ -117,21 +117,29 @@ pub trait RunArgs {
...
         match $self {
-            $($variants(variant) => RunArgs::run(variant, $cfg),)*
+            $($variants(variant) => RunArgs::run(variant, $cfg, $callback),)*
         }
     };
 }
 
 impl RunArgs for Subcommand {
-    fn run(self, cfg: &ClientConfiguration) -> Result<Box<dyn Serialize>> {
+    fn run<F: FnMut(&dyn Serialize) -> Result<()>>(
```
Comment (0x009922) [inline client_cli/src/main.rs:136]: `FnMut(&dyn Serialize) -> Result<()>` is repeated over and over and over again. Could you use an alias for that?

File: client_cli/src/main.rs [hunk 3]
```diff
@@ -117,21 +117,29 @@ pub trait RunArgs {
     ///
     /// # Errors
     /// if inner command errors
-    fn run(self, cfg: &ClientConfiguration) -> Result<Box<dyn Serialize>>;
+    fn run<F: FnMut(&dyn Serialize) -> Result<()>>(
+        self,
+        cfg: &ClientConfiguration,
+        callback: F,
+    ) -> Result<()>;
```
Comment (0x009922) [inline client_cli/src/main.rs:124]: I don't like that each `RunArgs` implementor has to accept a magic `callback` and pass it explicitly to the final destination. Also, each time you have to specify the type of callback, which is verbose.

I think it would be better to introduce a trait like `RunContext`:

```rust
trait RunContext {
  fn configuration(&self) -> &ClientConfiguration;

  fn print_data(&self, value: impl Serialize) -> Result<()>;
}
```

That is something you can pass everywhere instead of `cfg` + `callback`. This approach is even less cost in terms of runtime (you don't need to pass 2 args, and you can simply `impl RunContext` with callback instead of passing a closure).

File: client_cli/src/main.rs (hunk 2 above)
Comment (0x009922) [reply client_cli/src/main.rs:136]: I also don't understand why it should be `FnMut` and not `Fn`?

**Review by 0x009922 — CHANGES_REQUESTED** [review]

File: client_cli/src/main.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (mversic) [reply client_cli/src/main.rs:262]: instead of passing in callback, could you make it a method on `RunArgs` trait?

**Review by mversic — DISMISSED** [review]

File: client_cli/src/main.rs (hunk 3 above)
Comment (0x009922) [reply client_cli/src/main.rs:124]: Runtime cost is definitely not an issue, of course. But I wonder if code organisation will be better with an umbrella trait.

Comment (Erigara) [reply client_cli/src/main.rs:124]: I will try to implement your approach. I think it will be look nicer that current one.

File: client_cli/src/main.rs [hunk 4]
```diff
@@ -111,27 +111,55 @@ pub enum Subcommand {
...
+    write: W,
+    config: ClientConfiguration,
+}
+
+impl<W: std::io::Write> RunContext for PrintJsonContext<W> {
+    fn configuration(&self) -> &ClientConfiguration {
+        &self.config
+    }
+
+    fn print_data(&mut self, data: &dyn Serialize) -> Result<()> {
```
Comment (0x009922) [inline client_cli/src/main.rs:136]: Why it should be `dyn Serialize` and not `impl Serialize`?

File: client_cli/src/main.rs [hunk 5]
```diff
@@ -111,27 +111,55 @@ pub enum Subcommand {
...
+}
+
 /// Runs subcommand
 pub trait RunArgs {
     /// Runs command
     ///
     /// # Errors
     /// if inner command errors
-    fn run(self, cfg: &ClientConfiguration) -> Result<Box<dyn Serialize>>;
+    fn run(self, context: &mut dyn RunContext) -> Result<()>;
```
Comment (0x009922) [inline client_cli/src/main.rs:148]: Same as with `dyn Serialize`: why not use just generics?

```suggestion
    fn run<C: RunContext>(self, context: &mut C) -> Result<()>;
```

File: client_cli/src/main.rs [hunk 6]
```diff
@@ -186,10 +217,10 @@ fn main() -> Result<()> {
 #[allow(clippy::shadow_unrelated)]
 pub fn submit(
```
Comment (0x009922) [inline client_cli/src/main.rs:218]: Btw, it seems that `context` is used only within `submit` and `listen` functions. So, maybe you can define a "miniclient" struct that has `submit` and `listen` functions, and does the printing internally?

```rust
trait MiniClient {
  fn listen(&mut self, height: NonZeroU64) -> Result<()>;

  fn submit(&mut self, isi: impl Into<Executable>, metadata: UnlimitedMetadata) -> Result<()>;
}
```

`RunArgs` might work with `MiniClient` trait. The struct that implements `MiniClient` might contain both configuration and debugging logic, which `RunArgs` does not care about.

**Review by 0x009922 — APPROVED** [review]
LGTM, although I got a new code organisation idea.

File: client_cli/src/main.rs (hunk 4 above)
Comment (Erigara) [reply client_cli/src/main.rs:136]: It can be `impl Serialize` but in this case code size would be bigger because compiled code would have monomorphized version of function.

If in the future we would introduce another `context` like `PrintRONContext`. 
Size of code will be proportional to `n_contexts * m_serialized_objects`.

Atm difference is not that big through `9.2Mb` for generics vs `9.1Mb` for dyn object (`9.2Mb` vs `9.8Mb` if we would add `RON` serialization support).

File: client_cli/src/main.rs (hunk 5 above)
Comment (Erigara) [reply client_cli/src/main.rs:148]: Answered in the comment above.

File: client_cli/src/main.rs (hunk 6 above)
Comment (Erigara) [reply client_cli/src/main.rs:218]: I should notice that `context` is also used in queries + `listen` for blocks/events functions are not the same.

Comment (Erigara) [reply client_cli/src/main.rs:218]: Created #3611.

File: client_cli/src/main.rs (hunk 4 above)
Comment (0x009922) [reply client_cli/src/main.rs:136]: I think that for the client the compiled binary size is more important than a tiny performance benefit we would get with `impl`. So yeah, I am fine with `dyn`.

File: client_cli/src/main.rs [hunk 7]
```diff
@@ -111,27 +111,55 @@ pub enum Subcommand {
     Json(json::Args),
 }
 
+/// Context inside which command is executed
+pub trait RunContext {
+    /// Get access to configuration
+    fn configuration(&self) -> &ClientConfiguration;
+    /// Serialize and print data
```
Comment (Arjentix) [inline client_cli/src/main.rs:118]:
```suggestion
    fn configuration(&self) -> &ClientConfiguration;
    
    /// Serialize and print data
```

**Review by Arjentix — APPROVED** [review]

File: client_cli/src/main.rs (hunk 7 above)
Comment (Erigara) [reply client_cli/src/main.rs:118]: Discussed in DM, let's do it as part of other task
