### PR TITLE
[fix] #3843: Fix genesis validation

### LINKED ISSUE #3843: [BUG] Allow genesis to execute any operation
After the merge of #3781 it has become impossible for genesis to execute instructions due to the lack of permissions

### PR DESCRIPTION
**Pull request by mversic**
### Linked issue

Closes #3843

### Checklist

- [ ] I've read `CONTRIBUTING.md`
- [ ] I've used the standard signed-off commit format (or will squash just before merging)
- [ ] All applicable CI checks pass (or I promised to make them pass later)
- [ ] (optional) I've written unit tests for the code changes
- [ ] I replied to all comments after code review, marking all implemented changes with thumbs up

### CODE REVIEW

**Review by appetrosyan — APPROVED** [review]

File: wasm/validator/src/permission.rs [hunk 1]
```diff
@@ -82,8 +82,8 @@ pub mod asset {
     }
 
     impl PassCondition for Owner<'_> {
-        fn validate(&self, authority: &AccountId, _block_height: u64) -> Result {
-            if self.asset_id.account_id() != authority {
+        fn validate(&self, authority: &AccountId, block_height: u64) -> Result {
+            if block_height == 0 && self.asset_id.account_id() != authority {
```
Comment (QuentinI) [inline wasm/validator/src/permission.rs:86]: I feel like you meant `!= 0` here

**Review by QuentinI — CHANGES_REQUESTED** [review]

File: wasm/validator/src/permission.rs [hunk 2]
```diff
@@ -82,14 +82,17 @@ pub mod asset {
     }
 
     impl PassCondition for Owner<'_> {
-        fn validate(&self, authority: &AccountId, _block_height: u64) -> Result {
-            if self.asset_id.account_id() != authority {
-                return Err(ValidationFail::NotPermitted(
-                    "Can't access asset owned by another account".to_owned(),
-                ));
+        fn validate(&self, authority: &AccountId, block_height: u64) -> Result {
+            if block_height == 0 {
```
Comment (pesterev) [inline wasm/validator/src/permission.rs:86]: The fact that ```block_height == 0``` skips all other checks is a bit confusing but as I understand it was done on purpose.

**Review by pesterev — APPROVED** [review]

File: wasm/validator/src/permission.rs (hunk 2 above)
Comment (mversic) [reply wasm/validator/src/permission.rs:86]: I will turn this comment into an issue so we can discuss better ways of doing this. The thing is that genesis account has to have the privilege to execute any ISI. Since we've introduced validation of genesis transactions in #3781 this was no longer the case and would not allow genesis to be applied

**Review by QuentinI — APPROVED** [review]
