### PR TITLE
[fix] #3905: Fix apply_blocks and validate_blocks benchmark

### LINKED ISSUE #3905: [BUG]: `apply_blocks` and `validate_blocks` fails
Currently `apply_blocks` and `validate_blocks` fails silently.

### PR DESCRIPTION
**Pull request by Erigara**
## Description

Benchmarks now measure what they suppose to measure.
Fix memory issue inside wasm validator.

### Linked issue

Closes #3905, #3906 

### Benefits

Fixed benchmarks.

### CODE REVIEW

File: wasm/src/lib.rs [hunk 1]
```diff
@@ -24,13 +24,14 @@ use data_model::{
...
 pub use iroha_wasm_derive::main;
+use lol_alloc::{FreeListAllocator, LockedAllocator};
 use parity_scale_codec::{DecodeAll, Encode};
 
 pub mod debug;
 pub mod log;
 
 #[global_allocator]
-static ALLOC: wee_alloc::WeeAlloc = wee_alloc::WeeAlloc::INIT;
+static ALLOC: LockedAllocator<FreeListAllocator> = LockedAllocator::new(FreeListAllocator::new());
```
Comment (DCNick3) [inline wasm/src/lib.rs:34]: Looking at the docs, `LockedAllocator` is only required if multi-threading is used in wasm. With [AssumeSingleThreaded](https://docs.rs/lol_alloc/0.4.0/lol_alloc/struct.AssumeSingleThreaded.html), a few bytes may be shaved off.

File: core/src/validator.rs [hunk 2]
```diff
@@ -27,10 +27,12 @@ impl From<wasm::error::Error> for ValidationFail {
...
                 match call_error {
                     ExecutionLimitsExceeded(_) => Self::TooComplex,
-                    HostExecution(error) | Other(error) => Self::InternalError(error.to_string()),
+                    HostExecution(error) | Other(error) => {
+                        Self::InternalError(format!("{error:#}"))
+                    }
                 }
             }
-            _ => Self::InternalError(err.to_string()),
+            _ => Self::InternalError(format!("{err:#}")),
```
Comment (DCNick3) [inline core/src/validator.rs:35]: How does this change the error message? Would it have proper newlines, or smth?

File: core/benches/blocks/common.rs [hunk 3]
```diff
@@ -136,10 +172,12 @@ fn restore_every_nth(
     Ok(instructions)
 }
 
-fn build_wsv(account_id: &AccountId, key_pair: &KeyPair) -> WorldStateView {
+pub fn build_wsv(account_id: &AccountId, key_pair: &KeyPair) -> WorldStateView {
     let kura = iroha_core::kura::Kura::blank_kura_for_testing();
     let mut wsv = WorldStateView::new(World::with([], BTreeSet::new()), kura);
     wsv.config.transaction_limits = TransactionLimits::new(u64::MAX, u64::MAX);
+    wsv.config.wasm_runtime_config.fuel_limit = u64::MAX;
+    wsv.config.wasm_runtime_config.max_memory = u32::MAX;
```
Comment (DCNick3) [inline core/benches/blocks/common.rs:180]: Is this necessary even after fixing the memory leak? Or is there just no sense to limit these in a benchmark situation? :thinking:

**Review by DCNick3 — COMMENTED** [review]
It's a bit hard to see what actually changed with all the renamings and stuff..

I understand what's the problem with the `wee_alloc` memory leak, but what the problem with `apply_blocks` and `validate_blocks`?

What was the problem with

File: core/src/validator.rs (hunk 2 above)
Comment (Erigara) [reply core/src/validator.rs:35]: It will print causes of error ([link](https://docs.wasmtime.dev/api/wasmtime/struct.Error.html#display-representations))

File: core/benches/blocks/common.rs (hunk 3 above)
Comment (Erigara) [reply core/benches/blocks/common.rs:180]: > Or is there just no sense to limit these in a benchmark situation? 🤔

Exactly, in the benchmark we are submitting large block that won't normally pass limitations in the validator.

**Comment by Erigara** [comment]
> but what the problem with apply_blocks and validate_blocks?

@DCNick3 so problem was that:
1) Not enough fuel
2) Transactions don't have enough rights to be executed with default_validator

File: core/src/validator.rs (hunk 2 above)
Comment (DCNick3) [reply core/src/validator.rs:35]: Ah, that's just an anyhow error. Makes sense.

**Review by DCNick3 — APPROVED** [review]

**Review by SamHSmith — APPROVED** [review]
