### PR TITLE
[fix] #3330: Manually implement `serde::de::Deserialize` for partially tagged enums

### LINKED ISSUE #3330: [BUG] Cannot deserialize U128
As per title. Issue spans from LTS to current ([726f5eabf65a79ea618b4fce62a09cee7a5b13d1](https://github.com/hyperledger/iroha/commit/726f5eabf65a79ea618b4fce62a09cee7a5b13d1)).
Easiest way to reproduce: start iroha with modified `genesis.json`.

<details><summary> <code>genesis.json</code> for LTS</summary>
<p>

```javascript
{
  "transactions": [
    {
      "isi": [
        {
          "Register": {
            "Identifiable": {
              "NewDomain": {
                "id": "wonderland",
                "logo": null,
                "metadata": {
                  "key": {
                    "U128": 1
                  }
                }
              }
            }
          }
        },
        {
          "Register": {
            "Identifiable": {
              "NewAccount": {
                "id": "alice@wonderland",
                "signatories": [
                  "ed01207233bfc89dcbd68c19fde6ce6158225298ec1131b6a130d1aeb454c1ab5183c0"
                ],
                "metadata": {
                  "key": {
                    "U128": 1
                  }
                }
              }
            }
          }
        },
        {
          "Register": {
            "Identifiable": {
              "NewAccount": {
                "id": "bob@wonderland",
                "signatories": [
                  "ed01207233bfc89dcbd68c19fde6ce6158225298ec1131b6a130d1aeb454c1ab5183c0"
                ],
                "metadata": {
                  "key": {
                    "U128": 1
                  }
                }
              }
            }
          }
        },
        {
          "Register": {
            "Identifiable": {
              "NewAssetDefinition": {
                "id": "rose#wonderland",
                "value_type": "Quantity",
                "mintable": "Infinitely",
                "metadata": {}
              }
            }
          }
        },
        {
          "Register": {
            "Identifiable": {
              "NewDomain": {
                "id": "garden_of_live_flowers",
                "logo": null,
                "metadata": {}
              }
            }
          }
        },
        {
          "Register": {
            "Identifiable": {
              "NewAccount": {
                "id": "carpenter@garden_of_live_flowers",
                "signatories": [
                  "ed01207233bfc89dcbd68c19fde6ce6158225298ec1131b6a130d1aeb454c1ab5183c0"
                ],
                "metadata": {}
              }
            }
          }
        },
        {
          "Register": {
            "Identifiable": {
              "NewAssetDefinition": {
                "id": "cabbage#garden_of_live_flowers",
                "value_type": "Quantity",
                "mintable": "Infinitely",
                "metadata": {}
              }
            }
          }
        },
        {
          "Register": {
            "Identifiable": {
              "PermissionTokenDefinition": {
                "id": "can_unregister_asset_with_definition",
                "params": {
                  "asset_definition_id": "Id"
                }
              }
            }
          }
        },
        {
          "Register": {
            "Identifiable": {
              "PermissionTokenDefinition": {
                "id": "can_burn_asset_with_definition",
                "params": {
                  "asset_definition_id": "Id"
                }
              }
            }
          }
        },
        {
          "Register": {
            "Identifiable": {
              "PermissionTokenDefinition": {
                "id": "can_burn_user_assets",
                "params": {
                  "asset_id": "Id"
                }
              }
            }
          }
        },
        {
          "Register": {
            "Identifiable": {
              "PermissionTokenDefinition": {
                "id": "can_set_key_value_in_user_assets",
                "params": {
                  "asset_id": "Id"
                }
              }
            }
          }
        },
        {
          "Register": {
            "Identifiable": {
              "PermissionTokenDefinition": {
                "id": "can_remove_key_value_in_user_assets",
                "params": {
                  "asset_id": "Id"
                }
              }
            }
          }
        },
        {
          "Register": {
            "Identifiable": {
              "PermissionTokenDefinition": {
                "id": "can_set_key_value_in_user_metadata",
                "params": {
                  "account_id": "Id"
                }
              }
            }
          }
        },
        {
          "Register": {
            "Identifiable": {
              "PermissionTokenDefinition": {
                "id": "can_remove_key_value_in_user_metadata",
                "params": {
                  "account_id": "Id"
                }
              }
            }
          }
        },
        {
          "Register": {
            "Identifiable": {
              "PermissionTokenDefinition": {
                "id": "can_set_key_value_in_asset_definition",
                "params": {
                  "asset_definition_id": "Id"
                }
              }
            }
          }
        },
        {
          "Register": {
            "Identifiable": {
              "PermissionTokenDefinition": {
                "id": "can_remove_key_value_in_asset_definition",
                "params": {
                  "asset_definition_id": "Id"
                }
              }
            }
          }
        },
        {
          "Register": {
            "Identifiable": {
              "PermissionTokenDefinition": {
                "id": "can_mint_user_asset_definitions",
                "params": {
                  "asset_definition_id": "Id"
                }
              }
            }
          }
        },
        {
          "Register": {
            "Identifiable": {
              "PermissionTokenDefinition": {
                "id": "can_transfer_user_assets",
                "params": {
                  "asset_id": "Id"
                }
              }
            }
          }
        },
        {
          "Register": {
            "Identifiable": {
              "PermissionTokenDefinition": {
                "id": "can_transfer_only_fixed_number_of_times_per_period",
                "params": {
                  "count": "U32",
                  "period": "U128"
                }
              }
            }
          }
        },
        {
          "Mint": {
            "object": {
              "U32": 13
            },
            "destination_id": {
              "Id": {
                "AssetId": "rose##alice@wonderland"
              }
            }
          }
        },
        {
          "Mint": {
            "object": {
              "U32": 44
            },
            "destination_id": {
              "Id": {
                "AssetId": "cabbage#garden_of_live_flowers#alice@wonderland"
              }
            }
          }
        },
        {
          "Register": {
            "Identifiable": {
              "PermissionTokenDefinition": {
                "id": "allowed_to_do_stuff",
                "params": {}
              }
            }
          }
        },
        {
          "Register": {
            "Identifiable": {
              "NewRole": {
                "inner": {
                  "id": "USER_METADATA_ACCESS",
                  "permissions": [
                    {
                      "definition_id": "can_remove_key_value_in_user_metadata",
                      "params": {
                        "account_id": {
                          "Id": {
                            "AccountId": "alice@wonderland"
                          }
                        }
                      }
                    },
                    {
                      "definition_id": "can_set_key_value_in_user_metadata",
                      "params": {
                        "account_id": {
                          "Id": {
                            "AccountId": "alice@wonderland"
                          }
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        },
        {
          "Grant": {
            "object": {
              "PermissionToken": {
                "definition_id": "allowed_to_do_stuff",
                "params": {}
              }
            },
            "destination_id": {
              "Id": {
                "AccountId": "alice@wonderland"
              }
            }
          }
        },
        {
          "Register": {
            "Identifiable": {
              "NewRole": {
                "inner": {
                  "id": "staff_that_does_stuff_in_genesis",
                  "permissions": [
                    {
                      "definition_id": "allowed_to_do_stuff",
                      "params": {}
                    }
                  ]
                }
              }
            }
          }
        }
      ]
    }
  ]
}
``` 

</p>
</details>

<details><summary> <code>genesis.json</code> for DEV</summary>
<p>

[gist link](https://gist.github.com/QuentinI/191c32516b59f2305fcd1989662c4c29)

</p>
</details> 

Both files attached differ only with value type of example metadata, which is U128 instead of String. They were created by modifying relevant line in kagami and re-generating genesis (genesis for dev is also edited by hand to correct for another bug we have on dev)

### PR DESCRIPTION
**Pull request by appetrosyan**
## Description

As a workaround for the upstream issue in `serde` we must manually implement the code that would be generated by `serde(untagged)`. This also has the added benefit of preserving the error messages, but unfortunately comes at the cost of using `serde_json::Value`, and a `Clone::clone` call to the entire candidate value. 

Unfortunately, until the issue is fixed upstream, there is no better way to handle this. 

### Linked issue

Closes #3330 in `iroha2-dev`. Fix was already implemented in `iroha2-lts`. 

### Benefits

Fully-functional deserialization. 

### Checklist

- [X] I've read `CONTRIBUTING.md`
- [X] I've used the standard signed-off commit format (or will squash just before merging)
- [X] All applicable CI checks pass (or I promised to make them pass later)
- [X] (optional) I've written unit tests for the code changes
- [X] I replied to all comments after code review, marking all implemented changes with thumbs up

### CODE REVIEW

File: data_model/derive/src/partially_tagged.rs [hunk 1]
```diff
@@ -223,12 +232,64 @@ pub fn impl_partially_tagged_deserialize(enum_: &PartiallyTaggedEnum) -> TokenSt
...
+                    fn deserialize<D: ::serde::Deserializer<'de>>(
+                        deserializer: D,
+                    ) -> Result<Self, D::Error> {
+                        #[cfg(feature = "std")]
+                        let mut errors = Vec::new();
+
+                        let content = serde_json::Value::deserialize(deserializer)?;
+                        #(
+                            {
+                                // FIXME: Elide expensive clone.
```
Comment (Erigara) [inline data_model/derive/src/partially_tagged.rs:247]: `&'de Value` implement [`Deserializer<'de>`](https://docs.rs/serde_json/latest/serde_json/enum.Value.html#impl-Deserializer%3C'de%3E-for-%26'de+Value) isn't it possible to use `&content` instead of `clone`?

**Review by Erigara — APPROVED** [review]

File: data_model/derive/src/partially_tagged.rs (hunk 1 above)
Comment (appetrosyan) [reply data_model/derive/src/partially_tagged.rs:247]: Indeed. Fixing now.

**Review by Erigara — APPROVED** [review]

**Review by pesterev — APPROVED** [review]
