### PR TITLE
fix(torii): close ws properly in blocks/events stream

### LINKED ISSUE #5004: [BUG] As many WebSocket ERRORs as transactions handled
### OS and Environment

Linux, `test_env.py`

### GIT commit hash

76dafdc

### Minimum working example / Steps to reproduce

Prepare `transaction.json` ([example](https://github.com/hyperledger/iroha/issues/4952#issuecomment-2275820415)) with a few instructions and,

```zsh
git checkout 76dafdc
cargo build
LOG_LEVEL=ERROR ./scripts/test_env.py setup
cd test
while true; do curl http://127.0.0.1:8080/status; cat transaction.json | ./iroha json transaction &; sleep 0.5; done
```

### Actual result

On block commit, peer logs as many WebSocket ERRORs as the transactions it has handled during the round.

`test/peers/iroha0/log.txt`

```txt
  2024-08-22T15:26:03.287294Z ERROR iroha_torii: Failure during event streaming, error: WebSocket error: WebSocket protocol error: Sending after closing is not allowed
    at torii/src/lib.rs:215
```

This is not seen in other peers

### Expected result

There should be no ERROR level logs in normal use

### Logs

See [Actual result](#actual-result) section

### Who can help to reproduce?

@s8sato

### Notes

_No response_

### PR DESCRIPTION
**Pull request by Erigara**
## Context

Closes #5004.

Problem was that iroha tried to unconditionally closed websocket by writing into it.

During another problems were discovered as well:
- on client side sync and async websocket stream wasn't properly closed (not reads until handshake completion)
- on client async websocket `Stream` implementation was incorrect by not registering itself on receiving non binary message

### Solution

Fix mentioned problems + refactoring.

### CODE REVIEW

**Review by dima74 — APPROVED** [review]

File: crates/iroha_torii/src/stream.rs [hunk 1]
```diff
@@ -17,124 +15,97 @@ const TIMEOUT: Duration = Duration::from_millis(1000);
...
-
-    /// Message type used by the underlying stream
-    type Message: StreamMessage;
-
-    /// Receives and decodes message from the stream
-    async fn recv(&mut self) -> Result<R, Error<Self::Err>> {
-        let subscription_request_message = tokio::time::timeout(TIMEOUT, self.next())
+impl WebSocketScale {
+    /// Send message encoded in scale
+    pub async fn send<M: Encode + Send>(&mut self, message: M) -> Result<(), Error> {
```
Comment (DCNick3) [inline crates/iroha_torii/src/stream.rs:37]: Would it make sense to lift these generics (along with the ones on `recv`) to the `WebSocketScale` type? I don't think we expect to receive different types of messages during the lifetime of the connection.

Something like `struct WebSocketScale<ReceivedMessage, SentMessage>`

File: crates/iroha_torii/src/routing.rs [hunk 2]
```diff
@@ -103,110 +97,143 @@ pub async fn handle_post_configuration(
...
+    use super::*;
+    use crate::block;
+
+    /// Type for any error during blocks streaming
+    #[derive(Debug, displaydoc::Display, thiserror::Error)]
+    enum Error {
+        /// Block consumption resulted in an error: {_0}
+        Consumer(#[from] Box<block::Error>),
+        /// Event reception error
+        Event(#[from] tokio::sync::broadcast::error::RecvError),
```
Comment (DCNick3) [inline crates/iroha_torii/src/routing.rs:114]: Is this error variant used anywhere? I don't see any broadcast channels being used for blocks..

**Review by DCNick3 — COMMENTED** [review]
This seems like quite a good improvement over what we had before

File: crates/iroha_torii/src/routing.rs (hunk 2 above)
Comment (Erigara) [reply crates/iroha_torii/src/routing.rs:114]: Indeed, removed.

File: crates/iroha_torii/src/stream.rs (hunk 1 above)
Comment (Erigara) [reply crates/iroha_torii/src/stream.rs:37]: I think placing generic on `recv` and `send` allow implementing handshake procedure:
1. recv/send handshake msg type
2. exchange ordinary messages

**Review by DCNick3 — APPROVED** [review]

**Review by dima74 — APPROVED** [review]
