### PR TITLE
[fix] #3592: fix config files updating on release

### LINKED ISSUE #3592: [CI] Fix config update on release

### PR DESCRIPTION
**Pull request by mversic**
### Linked issue

Closes #3592 

### Checklist

- [ ] I've read `CONTRIBUTING.md`
- [ ] I've used the standard signed-off commit format (or will squash just before merging)
- [ ] All applicable CI checks pass (or I promised to make them pass later)
- [ ] (optional) I've written unit tests for the code changes
- [ ] I replied to all comments after code review, marking all implemented changes with thumbs up

### CODE REVIEW

File: scripts/update_configs.sh [hunk 1]
```diff
@@ -17,9 +17,9 @@ if [ "$1" != "stable" ] && [ "$1" != "lts" ]; then
     echo $MSG && exit 1
 fi
 
-wget https://raw.githubusercontent.com/hyperledger/iroha/iroha2-stable/configs/peer/config.json -O "$(dirname "${BASH_SOURCE[0]}")/client_cli/$1/config.json"
-wget https://raw.githubusercontent.com/hyperledger/iroha/iroha2-lts/configs/peer/config.json -O "$(dirname "${BASH_SOURCE[0]}")/client_cli/$1/config.json"
+wget https://raw.githubusercontent.com/hyperledger/iroha/iroha2-stable/configs/peer/config.json -O "./configs/client/$1/config.json"
```
Comment (appetrosyan) [inline scripts/update_configs.sh:20]: Either one of them is brittle. We should probably agree on a directory structure. Namely we should probably put everything Iroha related into `.config` or some other standard XDG-compliant directory and atleast use `$HOME` or other env vars.

**Review by appetrosyan — APPROVED** [review]

File: scripts/update_configs.sh (hunk 1 above)
Comment (mversic) [reply scripts/update_configs.sh:20]: or the script can take the path argument

**Review by BAStos525 — APPROVED** [review]

**Comment by BAStos525** [comment]
I guess that [this workflow step](https://github.com/mversic/iroha/blob/2cd2d4aa0822478df89b72cd72f8265c15f7a658/.github/workflows/iroha2-release.yml#LL71C6-L71C6) will fail because of github user within the necessary permissions is not specified. Anyway, we could merge and see. If it will be, I'll try to fix.
