### PR TITLE
[test] #2506: Add more tests on block validation

### LINKED ISSUE #2506: [PERFORMANCE BUG] When sending ~ 5000 assets in a row then Iroha 2 down without information in logs.
### GIT commit hash

e3cd89bd

### Minimum working example

```rust
fn main() {
     // Steps to reproduce …
     // Steps to reproduce …
}
```

### Expected behaviour

I have a script which creates ~650 assets and then query findAllAssets to print total size. After like ~30k assets script starts to print same size after every new iteration (because findAllAssets returns old data). Btw all requests are sync. But after some  iterations data will be updated and Iroha returns all new assets. But after ~30k assets it doesn't update after every new bunch of assets.

### Actual behaviour

👆👆👆

### Operating system

macos

### LibC type and version

_No response_

### Current environment

Docker Hub

### Logs in JSON format

<details>
  <summary>Log contents</summary>
  
  ```json
  Replace this text with a JSON log,
  so it doesn't grow too large and has highlighting.
  ```
</details>

### Who can help?

_No response_

### PR DESCRIPTION
**Pull request by pesterev**
Signed-off-by: Vladimir Pesterev <pesterev@pm.me>

### Description of the Change

This test reproduces the root error of #2506. A detailed explanation of the bug is [here](https://github.com/hyperledger/iroha/issues/2506#issuecomment-1316913752).

### Issue

Closes #2506

### Benefits

Add more tests on the block validation.

### Possible Drawbacks

None

### CODE REVIEW

File: core/src/block.rs [hunk 1]
```diff
@@ -1145,4 +1150,64 @@ mod tests {
...
+                alice_id.clone(),
+                [create_asset_definition.clone()].into(),
+                4000,
+            )
+            .sign(alice_keys.clone())
+            .expect("Valid");
+            crate::VersionedAcceptedTransaction::from_transaction(tx, &transaction_limits)
+                .expect("Valid")
+        };
+        let tx_b = {
```
Comment (QuentinI) [inline core/src/block.rs:1193]: Couldn't we just clone here?

**Review by QuentinI — APPROVED** [review]

**Review by Erigara — APPROVED** [review]

**Review by QuentinI — APPROVED** [review]

**Review by Erigara — APPROVED** [review]
