### PR TITLE
fix: Add range check to signature index

### LINKED ISSUE #5104: [BUG] Sumeragi panics with "index out of bounds" message after unregistering a peer
### OS and Environment

macOs 14.16.1

### GIT commit hash

3e86d7b3d (in #5087)

### Minimum working example / Steps to reproduce

_Occured while re-implementing test network #5087, test `connected_peers.rs` integration test suite_

1. Create network with 7 peers, start, wait for genesis
2. Unregister a random one

### Actual result

_Sometimes_ one of the remaining peers may panic:

```
thread 'sumeragi' panicked at crates/iroha_core/src/sumeragi/main_loop.rs:626:38:
index out of bounds: the len is 6 but the index is 6
```

At this index access:

https://github.com/hyperledger/iroha/blob/7144f4e83d405bda553a99d7177c5a189452221e/crates/iroha_core/src/sumeragi/main_loop.rs#L626

### Expected result

Expected to not panic at any time.

### Logs

https://pastebin.com/LXtRDLNe

### Who can help to reproduce?

@0x009922

### Notes

Used `release` target of Iroha.

### PR DESCRIPTION
**Pull request by SamHSmith**
## Context

The bug is triggered if a a peer is unregistered from the topology while Sumeragi Messages are still in flight. This
is the only place where we use and array index operation that can panic. It is very hard to write a test for this case
that is guaranteed to show the issue each time.

Closes #5104 
### Solution

- Describe the approach taken to achieve the objective / resolve the issue.

### Migration Guide (optional)

- If this PR contains a breaking change relative to the `main` branch, provide an instruction on how affected parties might need to adapt to the change.

---

### Review notes (optional)

- For complex PRs, try to provide some information on how to approach the review more effectively.
- For example, is there a natural order in which the affected files should be reviewed?

### Checklist

- [ ] I've read [`CONTRIBUTING.md`](../CONTRIBUTING.md).
- [ ] (optional) I've written unit tests for the code changes.
- [ ] All review comments have been resolved.
- [ ] All CI checks pass.

### CODE REVIEW

**Comment by mversic** [comment]
what's the corresponding issue for this?

**Comment by 0x009922** [comment]
Linked it: #5104

File: crates/iroha_core/src/sumeragi/main_loop.rs [hunk 1]
```diff
@@ -628,6 +628,16 @@ impl Sumeragi {
...
+                        error!(
+                            peer_id=%self.peer_id,
+                            role=%self.role(),
+                            ?signatory_idx,
+                            topology_size=%self.topology.as_ref().len(),
+                            "Signature index is out of range."
+                        );
+                        return;
+                    }
                     let signatory = &self.topology.as_ref()[signatory_idx];
```
Comment (0x009922) [inline crates/iroha_core/src/sumeragi/main_loop.rs:641]: Out of bounds check is good, but it doesn't target the core issue - the data race in Sumeragi. The problem isn't really solved: imagine if the topology changed, but a certain index is still within the bounds - it wouldn't be an error, but Sumeragi will mess the peers between each other accidentally and can make incorrect decisions.

So, shouldn't there be a general solution for the data race condition instead?

Comment (mversic) [inline crates/iroha_core/src/sumeragi/main_loop.rs:641]:
```suggestion
                    let signatory = &self.topology.as_ref().get(signatory_idx) else {
                            error!(
                                peer_id=%self.peer_id,
                                role=%self.role(),
                                ?signatory_idx,
                                topology_size=%self.topology.as_ref().len(),
                                "Unknown signatory"
                            );
                            
                            return;
                    };
```

Comment (mversic) [reply crates/iroha_core/src/sumeragi/main_loop.rs:641]: data races are inherent to distributed systems. It was incorrect to assume that received signatures are valid at this point. This can happen in regular sumeragi operation.

**Review by 0x009922 — APPROVED** [review]
