### PR TITLE
[fix] #4097: Fix warp noise in logs

### LINKED ISSUE #4097: [BUG]: Fix warp noise in logs
Every request to iroha is polluted with the following log entry.

```
warp::filters::trace: unable to serve request (client error) status=404 error=Some(Rejection(NotFound))
```

### PR DESCRIPTION
**Pull request by Erigara**
## Description

- `warp::trace::request()` was attached twice for some endpoints, which lead to noise in logs
- logging error inside queue push was redundant because error should be handled on caller site

### Linked issue

Closes #4097 

### Benefits

Less noise in logs.

### CODE REVIEW

File: core/src/queue.rs [hunk 1]
```diff
@@ -199,8 +198,13 @@ impl Queue {
         let entry = match self.txs.entry(hash) {
             Entry::Occupied(mut old_tx) => {
                 // MST case
+                let signatures_amount_before = old_tx.get().signatures().len();
                 assert!(old_tx.get_mut().merge_signatures(tx));
-                info!("Signature added to existing multisignature transaction");
```
Comment (Erigara) [inline core/src/queue.rs:203]: Most of the time this would entry produce logs for just transaction duplicate, received through gossiping, so i decided to only log if signatures amount increased.

File: core/src/queue.rs [hunk 2]
```diff
@@ -189,7 +189,6 @@ impl Queue {
     pub fn push(&self, tx: AcceptedTransaction, wsv: &WorldStateView) -> Result<(), Failure> {
         trace!(?tx, "Pushing to the queue");
         if let Err(err) = self.check_tx(&tx, wsv) {
-            warn!("Failed to evaluate signature check. Error = {}", err);
```
Comment (Erigara) [inline core/src/queue.rs:192]: Should be handled on caller site.

File: cli/src/torii/routing.rs [hunk 3]
```diff
@@ -528,9 +528,7 @@ impl Torii {
                 })
             });
 
-        let ws_router = events_ws_router
-            .or(blocks_ws_router)
-            .with(warp::trace::request());
+        let ws_router = events_ws_router.or(blocks_ws_router);
```
Comment (DCNick3) [inline cli/src/torii/routing.rs:531]: I don't see those handlers having a `warp::trace::request()` middleware attached to them. Are they logging with some other mechanism?

Comment (Erigara) [reply cli/src/torii/routing.rs:531]: They are handled together with other endpoints at line 544.

**Review by mversic — APPROVED** [review]

File: cli/src/torii/routing.rs (hunk 3 above)
Comment (DCNick3) [reply cli/src/torii/routing.rs:531]: Oooh, I see, it was after that.

**Review by DCNick3 — APPROVED** [review]
