### PR TITLE
fix: add missing getters for data model structs

### LINKED ISSUE #4420: [BUG]: Data model structs data isn't accessible
We need to make sure that data model structs' fields are accessible inside client and data model through getters.

Currently it's often omitted due to restrictions of `iroha_ffi`.

### PR DESCRIPTION
**Pull request by Erigara**
## Description

Add missing getters.

### Linked issue

Closes #4420 

### Benefits

Struct fields could be accessed from wasm or client.

### CODE REVIEW

File: data_model/src/events/data/events.rs [hunk 1]
```diff
@@ -700,6 +700,23 @@ impl DataEvent {
     }
 }
 
+impl<ID> MetadataChanged<ID> {
+    /// Getter for `target_id`
+    pub fn target_id(&self) -> &ID {
+        &self.target_id
+    }
```
Comment (nxsaken) [inline data_model/src/events/data/events.rs:707]:
```suggestion
impl<Id> MetadataChanged<Id> {
    /// Getter for `target_id`
    pub fn target_id(&self) -> &Id {
        &self.target_id
    }
```

**Review by mversic — APPROVED** [review]

**Review by mversic — APPROVED** [review]

**Review by nxsaken — APPROVED** [review]
