### PR TITLE
fix(kura): Inline kura initialization into constructor

### LINKED ISSUE #4603: Kura panics after restart
After restarting peer kura fails with a message: "The block to be written cannot be None, see store_block function."

Looks like it happens because `Kura::start` is called before `Kura::init`.
It was the opposite before.

### PR DESCRIPTION
**Pull request by Erigara**
## Description

Due `init` was separate functions error was introduced where `start` was called before initialization which cause panic in kura.

Fix for that is to inline `init` inside constructor.

### Linked issue

Closes #4603 

### How to reproduce

1. start iroha
2. submit few blocks
3. restart iroha

Previously kura would crash, but iroha would continue working without ability to write new blocks to the disk.

### CODE REVIEW

File: cli/src/lib.rs [hunk 1]
```diff
@@ -215,12 +215,10 @@ impl Iroha {
             config.sumeragi.trusted_peers.clone(),
         );
 
-        let kura = Kura::new(&config.kura)?;
+        let (kura, block_count) = Kura::new(&config.kura)?;
         let kura_thread_handler = Kura::start(Arc::clone(&kura));
```
Comment (mversic) [inline cli/src/lib.rs:219]: can this also be inlined?

**Review by mversic — DISMISSED** [review]

File: cli/src/lib.rs (hunk 1 above)
Comment (Erigara) [reply cli/src/lib.rs:219]: yeah, but my thinking was that for testing purposes we don't need starting write to disk loop

**Review by VAmuzing — DISMISSED** [review]

**Review by mversic — APPROVED** [review]

**Review by VAmuzing — APPROVED** [review]

**Comment by Erigara** [comment]
There is failling test `executor_upgrade_should_run_migration` with error introduced by 9d91c77c1 commit. 
Going to merge as is and fix issue later since already have approvals.
