### PR TITLE
[fix] #2581: reduce noise in logs

### LINKED ISSUE #2581: Reduce noise in logs
In a real deployment it is almost impossible to combine health-checks and actual log investigation, because `warp` produces logs regardless of whether or not they're useful. 

In this example, we have two lines taken up by what is effectively noise. 

At a minimum we should be able to reduce the log level of `warp` independently. 

The default should be set to `DEBUG` or better `TRACE` as the information is effectively a filter trace, which isn't particularly useful at our stage of development, but might be useful for debugging purposes.

### PR DESCRIPTION
**Pull request by 0x009922**
## Description

I've researched for possible ways on how to configure logging in `warp`. I found that it's not easy.

Provided warp's tracing filter has hard-coded log levels. To implement something similar, but with patched levels, we need to implement `Filter`. This is not possible because [library authors decided](https://github.com/seanmonstar/warp/issues/555#issuecomment-622568143) that this should be kept internally and consumers should build their filters in a "convenient" way with `warp::any()`.

So, we decided to exclude `/health` route from logging at all, as this is the primary issue.

Also, I found that `WasmSmartContract` debug repr was not that is expected, and fixed it.

### Linked issue

Closes #2581  

### Benefits

- less noise in logs
- less noise in TRACE logs (fixed WASM debug repr)

### Checklist

- [x] I've read `CONTRIBUTING.md`
- [x] I've used the standard signed-off commit format (or will squash just before merging)
- [ ] All applicable CI checks pass (or I promised to make them pass later)
- [ ] (optional) I've written unit tests for the code changes
- [ ] I replied to all comments after code review, marking all implemented changes with thumbs up

### CODE REVIEW

File: data_model/src/transaction.rs [hunk 1]
```diff
@@ -165,7 +165,7 @@ model! {
     ///
     /// Uses **base64** (de-)serialization format.
     #[derive(DebugCustom, Clone, PartialEq, Eq, Hash, Constructor, Decode, Encode, Deserialize, Serialize, IntoSchema)]
-    #[debug(fmt = "WASM binary(len = {})", self.0.len())]
+    #[debug(fmt = "WASM binary(len = {})", "self.0.len()")]
```
Comment (mversic) [inline data_model/src/transaction.rs:168]: @Arjentix I believe this is how it should be done

Comment (0x009922) [reply data_model/src/transaction.rs:168]: Without it it was `[0, 1, 2, 3]` etc with all the bytes inside.

**Review by appetrosyan — APPROVED** [review]
