### PR TITLE
[fix] #4030, #4063, #4064, #4079: re-architect logger and dynamic configuration

### LINKED ISSUE #4030: [suggestion] Move `logger.terminal_colors` setting to the CLI layer
## Description

I propose to move `logger.terminal_colors` out of the configuration file to the layer of application's CLI args parsing, which happens before the config file is read and parsed.

### Why

"Terminal colors" configure whether the overall Command Line Interface should be colorized or not. Therefore, it belongs to the layer of CLI args, not the config file. Moreover, I don't see a reason why logger output colors in terminal should differ from any other terminal output of Iroha.

Also, configuration parsing happens after CLI arguments parsing. The process of configuration parsing itself might involve logging of hints/warnings/errors with or without colors. If `terminal_colors` is set in the config file, it will be only available _after_ the config is parsed. Thus, this option should be known before configuration parsing stage.

### Changes

- Remove `logger.terminal_colors` parameter from config file
- Introduce `--terminal-colors` CLI argument with a corresponding ENV var (e.g. `TERMINAL_COLORS`)

### Also

- Currently terminal colors is automatically enabled/disabled accordingly to TTY color detection (if `logger.terminal_colors` is not set). This behaviour will stay the same.

### PR DESCRIPTION
**Pull request by 0x009922**
## Description

Started by updating configuration endpoints according to #4063, this PR expanded to major update of dynamic configuration mechanism, Logger configuration (#4030, #4064) and initialisation.

Logger initialisation is a global one-time thing, which was done with `iroha_logger::init(Configuration)`  function, which might accept the config and initialise logger, or might not, without an error. While initialising, it injected a `ReloadHandle` into the configuration instance, so that all updates to `config.logger.max_log_level` would trigger updates set up within `iroha_logger::init`. Than that `config` was copied many times in `Torii` and log level was actually reloaded on `POST /configuration` updates.

However, the configuration value update was not reflected in subsequent `GET /configuration` requests (#4079), because each time `config` is copied (it was copied for each request), it was editing a copy of `config` without affecting an original one. Since a copy of `config` was still containing `ReloadHandle` from Logger, the log level was updated.

Another problem appeared because of combination of configuration & logger architecture, in tests. It appeared that some tests ran concurrently, each calling `iroha_logger::init` with  independent `Configuration`s. However, only one `iroha_logger::init` might succeed, and another silently pretends that everything is ok. It worked fine, until one of Iroha instances fails to update the log level, because its `Configuration` passed into `iroha_logger::init` was not injected with a `ReloadHandle`.

Shortly, the system was *unsound*, i.e. it was easy to misuse. 

**Changes in this PR:**

- Remove `ReloadHandle` and `SyncValue` from configuration
- Introduce Kiso (jp 基礎 - foundation; basis): an actor responsible for holding the configuration state and broadcasting its updates across the system in a fire-and-forget way
- Update Logger configuration according to #4030 and #4064
- Introduce Logger actor, which might be initialised only once per process, and which is responsible for log level reloading and telemetry subscriptions
- Update Logger initialisation: split `init(Configuration) -> Result<Option<Telemetries>>` into
    - `init_global(Configuration) -> Result<LoggerHandle>`, initialising the Logger actor once per process, and failing if it was done already
    - `test_logger() -> LoggerHandle`, lazily initialising the Logger actor with pre-defined configuration, suitable for tests

**Chores:**

- Remove redundant fields from Kura configuration
- Refactor telemetry broadcasting mechanisms

### Linked issue

Closes #4030 #4063 #4064 #4079

### Benefits

- Improves configuration UX
- Improves system soundness

### Checklist

- [x] Refactor Kiso in a fire-and-forget manner
- [x] Play with logger manually
  - [x] Check if `bunyan` can parse current JSON output
- [x] Update logger config in py test env
- [x] Update README logger documentation
- [x] Use `202 Accepted` for `POST /configuration`

#### Update Logger configuration

In the configuration file, under `LOGGER.*` namespace:

- Rename `MAX_LOG_LEVEL` to `LEVEL`
- Remove `COMPACT_MODE`; use `FORMAT: "full"` (if `false`) and `FORMAT: "compact"` (if `true`) instead
- Remove `LOG_FILE_PATH`; use `FORMAT: "json"` instead and redirect stdout to a file, e.g. `iroha > log.json`
- Remove `TERMINAL_COLORS`; use `--terminal-colors`/`--no-terminal-colors` CLI arguments instead
- Remove `TELEMETRY_CAPACITY`

Env variables:

- `LOG_LEVEL`: instead of `MAX_LOG_LEVEL`
- `LOG_FORMAT`: new parameter
- `LOG_TOKIO_CONSOLE_ADDR`: instead of `TOKIO_CONSOLE_ADDR`

Example file before:

```json
{
  "LOGGER": {
    "MAX_LOG_LEVEL": "INFO",
    "TELEMETRY_CAPACITY": 1000,
    "COMPACT_MODE": false,
    "LOG_FILE_PATH": null,
    "TERMINAL_COLORS": true
  }
}
```

Example file after:

```json
{
  "LOGGER": {
    "LEVEL": "INFO",
    "FORMAT": "full"
  }
}
```

#### Update Kura configuration

In the configuration file, under `KURA.*` namespace, remove `ACTOR_CHANNEL_CAPACITY` and `BLOCKS_PER_STORAGE_FILE` fields.

#### Update configuration endpoints usage

- `GET /configuration` now returns JSON with only `{ logger: { level } }`.
- `POST /configuration` now accepts JSON in the same shape

`POST /configuration` request before:

```json
{"LogLevel":"DEBUG"}
```

`POST /configuration` request after:

```json
{"logger":{"level":"DEBUG"}}
```

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -49,3 +49,6 @@ result
 /test/
 /iroha-java/
 /lcov.info
+
+/rust-toolchain.toml
+.cargo/config.toml
```
Comment (Erigara) [inline .gitignore:54]: Do we really want to ignore this files?

File: cli/src/main.rs
Comment (Erigara) [inline cli/src/main.rs:1]: At some point we might consider to rewrite this using `clap`.

File: core/src/kiso.rs [hunk 2]
```diff
@@ -0,0 +1,143 @@
...
+        tokio::spawn(async move { actor.run().await });
+
+        Self { sender }
+    }
+
+    /// Fetch the [`ConfigurationDTO`] from the actor's state.
+    ///
+    /// # Errors
+    /// If communication with actor fails.
+    pub async fn get_dto(&self) -> Result<ConfigurationDTO, Error> {
```
Comment (Erigara) [inline core/src/kiso.rs:52]: Why do you choose message sending to propagate configuration? 

Some time ago i discovered [`arc_swap` ](https://github.com/vorner/arc-swap) create, from it's [usage patterns](https://docs.rs/arc-swap/latest/arc_swap/docs/patterns/index.html) i can see some benefits:

- it would allow to decouple configuration actor and configuration, so every configuration user will just have shared configuration type (or wrapper around it), not actor handle
- reduced amount of message sending to load configuration

File: scripts/test_env.py [hunk 3]
```diff
@@ -118,18 +118,19 @@ def run(self, is_genesis: bool = False):
 
         os.environ["KURA_BLOCK_STORE_PATH"] = str(peer_dir.joinpath("storage"))
         os.environ["SNAPSHOT_DIR_PATH"] = str(peer_dir.joinpath("storage"))
-        os.environ["LOG_FILE_PATH"] = str(peer_dir.joinpath("log.json"))
-        os.environ["MAX_LOG_LEVEL"] = "TRACE"
+        os.environ["LOG_LEVEL"] = "TRACE"
+        # FIXME: should it be JSON here?
```
Comment (Erigara) [inline scripts/test_env.py:122]: Not sure on this one, for quick debugging at least for me it's more convenient to read plain text.

File: .gitignore (hunk 1 above)
Comment (DCNick3) [reply .gitignore:54]: I don't know _why_ we have been ignoring those files, but I've accomplished this by listing them `.git/info/exclude`, which works the same way as gitignore, but isn't committed.

I think it does make sense to commit them to ensure everybody uses the same toolchain we use in CI and to not make people enable lints feature by hand.

I also have a snippet that  enables the usage of `mold` there:

```toml
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]
```

File: README.md [hunk 4]
```diff
@@ -178,17 +178,13 @@ For example, if your Iroha instance is running at `127.0.0.1:8080` and you want
 curl -X POST \
     -H 'content-type: application/json' \
     http://127.0.0.1:8080/configuration \
-    -d '{"LogLevel": "DEBUG"}' -i
+    -d '{"logger": {"level": "DEBUG"}}' -i
 ```
 </details>
 
-#### JSON Logging Mode
+Logger supports multiple output formats: `full` (default), `compact`, `pretty`, and `json`.
```
Comment (DCNick3) [inline README.md:185]: I think this should mention the name of the setting changing the output format

File: cli/src/main.rs
Comment (DCNick3) [reply cli/src/main.rs:1]: Created https://github.com/hyperledger/iroha/issues/4105

File: .gitignore (hunk 1 above)
Comment (Erigara) [reply .gitignore:54]: > but I've accomplished this by listing them .git/info/exclude

Oh, thanks for the tip

File: cli/src/main.rs [hunk 5]
```diff
@@ -109,7 +129,7 @@ async fn main() -> Result<(), color_eyre::Report> {
     }
 
     let config = iroha::combine_configs(&args)?;
-    let telemetry = iroha_logger::init(&config.logger)?;
+    let telemetry = iroha_logger::init_global(&config.logger, terminal_colors)?;
```
Comment (DCNick3) [inline cli/src/main.rs:132]: This is no longer telemetry, but a logger handle, probably needs renaming

File: cli/src/main.rs
Comment (0x009922) [reply cli/src/main.rs:1]: I was going to rewrite the main CLI as a next step, anyway it is related to the config RFC.

File: core/src/kiso.rs (hunk 2 above)
Comment (0x009922) [reply core/src/kiso.rs:52]: `arc_swap` seems to be a good option in case of sharing mutable state.

Some notes:

- Actually, now the config itself is almost not shared. The initial values are read and directly stored in actors, and only `Torii` holds the whole structure and interacts with it.
- We have a stateful system with many actors, which is not the same as patterns described in `arc_swap`. If in future we add more dynamic configurations related to internal logic of actors, it wouldn't be enough to just share the state: we will need a notification mechanism so that actors might react to changes. `Kiso` might propagate updates naturally.
- With `arc_swap`, each holder of the config will be able to not only read, but also write changes. It makes mutations decentralised and the architecture might become confusing to maintain and change, some subtle semantic bugs might appear etc. A central responsible point makes things clear, and it seems for me not achievable with `arc_swap`'s design.
- Shared mutable state is not idiomatic in the actor model.
- If in future we will need to share big parts of the config frequently, it is still achievable with `Kiso` and careful design of caching and notifications.
- Currently all dynamic configuration interactions happen only during configuration endpoints handling, which I guess is not that part that will be invoked frequently. So, I don't think message passing overhead is significant. Anyway, caching might always be used on top of that in future.

File: scripts/test_env.py (hunk 3 above)
Comment (0x009922) [reply scripts/test_env.py:122]: I think it's better to use `pretty` in this case.

File: .gitignore (hunk 1 above)
Comment (0x009922) [reply .gitignore:54]: Ah, just forgot to remove them from `staged`
Will move to `.git/info/exclude`, although I would like to see them in the repo permanently anyway.

File: logger/src/telemetry.rs [hunk 6]
```diff
@@ -82,70 +82,74 @@ impl Telemetry {
...
+/// A pair of [`Channel`] associated with [`Event`]
+pub struct ChannelEvent(pub Channel, pub Event);
+
+/// Supported telemetry channels
+#[derive(Copy, Clone)]
+pub enum Channel {
+    /// Regular telemetry
+    Regular,
+    /// Future telemetry (?)
+    // FIXME: what is the "future"?
```
Comment (DCNick3) [inline logger/src/telemetry.rs:153]: I think the "future" telemetry is collected from futures instrumented with `iroha_futures::TelemetryFuture`. It logs on every poll and reports how long did it take.

I am not sure if this feature is used by anyone though

File: core/src/kura.rs [hunk 7]
```diff
@@ -51,21 +51,23 @@ impl Kura {
     /// to access the block store indicated by the provided
     /// path.
     pub fn new(
-        mode: Mode,
-        block_store_path: &Path,
-        debug_output_new_blocks: bool,
+        config: &Configuration,
+        // mode: Mode,
```
Comment (DCNick3) [inline core/src/kura.rs:55]: These commented-out arguments can probably be removed

File: config/src/kura.rs [hunk 8]
```diff
@@ -17,11 +15,11 @@ pub struct Configuration {
     /// Initialization mode: `strict` or `fast`.
     pub init_mode: Mode,
     /// Path to the existing block store folder or path to create new folder.
-    pub block_store_path: String,
-    /// Maximum number of blocks to write into a single storage file.
-    pub blocks_per_storage_file: NonZeroU64,
-    /// Default buffer capacity of actor's MPSC channel.
-    pub actor_channel_capacity: u32,
+    pub block_store_path: PathBuf,
+    // /// Maximum number of blocks to write into a single storage file.
```
Comment (DCNick3) [inline config/src/kura.rs:19]: Commented code

as an aside note: curious how we ended up with these unused configuration options

File: core/src/kiso.rs (hunk 2 above)
Comment (Erigara) [reply core/src/kiso.rs:52]: Thanks for detailed explanation, your arguments seem reasonable to me

File: client/benches/tps/oneshot.rs [hunk 9]
```diff
@@ -20,7 +20,7 @@ fn main() {
         flush_guard = Some(flame_layer.flush_on_drop());
 
         tracing_subscriber::registry().with(flame_layer).init();
-        iroha_logger::disable_logger();
+        iroha_logger::disable_global().expect("Logger wasn't set yet");
```
Comment (DCNick3) [inline client/benches/tps/oneshot.rs:23]: I think `disable_global` fails in the opposite way - if the logger was already set

File: client/tests/integration/config.rs [hunk 10]
```diff
@@ -1,27 +1,44 @@
...
+
+    // Retrieving through API
+    let mut dto = test_client.get_config().expect("Client can always get it");
+    assert_eq!(dto.logger.level, init_log_level);
+
+    // Updating the log level
+    dto.logger.level = NEW_LOG_LEVEL;
+    test_client.set_config(dto).expect("New config is valid");
+
+    // FIXME: The updated value is not reflected
```
Comment (DCNick3) [inline client/tests/integration/config.rs:34]: Is this still true? The PR title suggest that it addresses #4079

File: config/src/logger.rs [hunk 11]
```diff
@@ -29,77 +22,49 @@ pub fn into_tracing_level(level: Level) -> tracing::Level {
...
-    }
-}
-
-impl Eq for SyncLevel {}
-
 /// 'Logger' configuration.
 #[derive(Debug, Clone, PartialEq, Eq, Deserialize, Serialize, Proxy, Documented)]
 #[serde(rename_all = "UPPERCASE")]
+#[config(env_prefix = "LOG_")]
+// `tokio_console_addr` is not `Copy`, but warning appears without `tokio-console` feature
```
Comment (DCNick3) [inline config/src/logger.rs:29]: Now that it has a type of `SocketAddr`, it _is_ actually `Copy`, so it can be derived here

File: core/src/kiso.rs [hunk 12]
```diff
@@ -0,0 +1,143 @@
...
+        dto: ConfigurationDTO,
+        respond_to: oneshot::Sender<Result<(), Error>>,
+    },
+}
+
+/// TODO
+#[derive(thiserror::Error, Debug)]
+pub enum Error {
+    /// TODO
+    #[error("cannot dynamically update the configuration")]
```
Comment (DCNick3) [inline core/src/kiso.rs:92]:
```suggestion
    #[error("failed to dynamically update the configuration")]
```

File: core/src/kiso.rs [hunk 13]
```diff
@@ -0,0 +1,143 @@
...
+    Update(#[from] iroha_logger::ReloadError),
+    /// TODO
+    #[error("cannot get actor's response")]
```
Comment (DCNick3) [inline core/src/kiso.rs:95]:
```suggestion
    #[error("failed to get actor's response")]
```

File: futures/tests/basic.rs [hunk 14]
```diff
@@ -32,15 +31,13 @@ async fn test_sleep() {
...
     ];
 
-    let (_, telemetry_future) = iroha_logger::init(
-        &ConfigurationProxy::default()
-            .build()
-            .expect("Default logger config always builds"),
-    )
-    .unwrap()
-    .unwrap();
+    let telemetry_future = iroha_logger::test_logger()
```
Comment (DCNick3) [inline futures/tests/basic.rs:34]:
```suggestion
    let future_telemetry = iroha_logger::test_logger()
```

File: core/src/kiso.rs [hunk 15]
```diff
@@ -0,0 +1,143 @@
...
+            LoggerError::LevelReload(err) => Self::from(err),
+            LoggerError::Communication(err) => Self::from(err),
+        }
+    }
+}
+
+struct Actor {
+    receiver: mpsc::Receiver<Message>,
+    state: Configuration,
+    logger: LoggerHandle,
```
Comment (DCNick3) [inline core/src/kiso.rs:111]: Just an idea: if we would add dynamic configuration for other more general-purpuse actors, we _might_ want to use a separate "handle" type not to conflate the cfg-related commands/messages with the actual actor functionality

File: logger/tests/setting_logger.rs [hunk 16]
```diff
@@ -1,21 +1,17 @@
...
-    assert!(second_init.unwrap().is_none());
+    let cfg = ConfigurationProxy::default()
+        .build()
+        .expect("Default logger config always builds");
+
+    let first = init_global(&cfg, false);
+    assert!(first.is_ok());
+
+    let second = init_global(&cfg, false);
+    assert!(second.is_ok());
```
Comment (DCNick3) [inline logger/tests/setting_logger.rs:14]: I think this shouldn't succeed, as the logger was already initialized?

File: scripts/test_env.py (hunk 3 above)
Comment (DCNick3) [reply scripts/test_env.py:122]: I _think_ with bunyan format we had before this PR it was possible to use a [cli tool](https://www.npmjs.com/package/bunyan) to print it in a pretty form with colors, which is nice. I learned of it just now, after researching what is this format :sweat_smile:

File: cli/src/lib.rs [hunk 17]
```diff
@@ -389,35 +413,34 @@ impl Iroha {
...
     #[cfg(feature = "telemetry")]
     async fn start_telemetry(
-        telemetry: Option<(
-            iroha_logger::SubstrateTelemetry,
-            iroha_logger::FutureTelemetry,
-        )>,
-        config: &Configuration,
+        logger: &LoggerHandle,
+        config: &TelemetryConfiguration,
     ) -> Result<bool> {
```
[the remark this answers is not in the document]
Comment (0x009922) [reply cli/src/lib.rs:418]: Thanks! Actually, I don't really like `Result<bool>` here...

File: client/benches/tps/oneshot.rs (hunk 9 above)
Comment (0x009922) [reply client/benches/tps/oneshot.rs:23]: It's true. I put this message with "What assumption I _expect_ to be true?" in mind.

This would be clearer:

```rust
iroha_logger::disable_global().expect("Logger should not be set yet");
```

File: config/src/kura.rs (hunk 8 above)
Comment (0x009922) [reply config/src/kura.rs:19]: Don't know the history of `blocks_per_storage_file`. For `actor_channel_capacity` you can look here: https://github.com/hyperledger/iroha-2-docs/issues/392#issuecomment-1722872161

File: client/benches/tps/oneshot.rs (hunk 9 above)
Comment (DCNick3) [reply client/benches/tps/oneshot.rs:23]: Hm, I usually think of `expect` not as "this is why it should never fire", but in terms of "what the user sees when this gets fired", hence the confusion. Your proposed message serves both goals fine I think

File: core/src/kiso.rs (hunk 15 above)
Comment (0x009922) [reply core/src/kiso.rs:111]: Hmm, I can't get wdym. Could you give an example?

File: core/src/kiso.rs [hunk 18]
```diff
@@ -0,0 +1,143 @@
...
+                        logger: LoggerDTO { level: new_level },
+                    },
+                respond_to,
+            } => {
+                if let Err(err) = self.logger.reload_level(new_level).await {
+                    let _ = respond_to.send(Err(err.into()));
+                    return;
+                }
+                self.state.logger.level = new_level;
+                let _ = respond_to.send(Ok(()));
```
[the remark this answers is not in the document]
Comment (0x009922) [reply core/src/kiso.rs:139]: So, you mean to use fire-and-forget configuration updates propagation.

Currently I designed `Kiso` in kind of transactional (but not atomic) way: it first tries to apply all updates, and only then updates the actual state. If something goes wrong during the update, it will return an error. This way, if you `POST /configuration`, `200 OK` will mean that the changes are applied, and if not, an error will return.

With fire-and-forget, `POST /configuration` will not return an error, but will always return `202 ACCEPTED`, and `GET /configuration` will return updated config which might not be really applied in the system.

I am fine either way and not sure which option is better. IMO the current design makes Iroha more reliable.

File: logger/src/lib.rs [hunk 19]
```diff
@@ -1,159 +1,139 @@
...
 
-    if configuration.compact_mode {
-        add_bunyan(configuration, layer.compact())
-    } else {
-        add_bunyan(configuration, layer)
+    match configuration.format {
+        Format::Full => step2(configuration, layer),
+        Format::Compact => step2(configuration, layer.compact()),
+        Format::Pretty => step2(configuration, layer.pretty()),
+        Format::Json => step2(configuration, layer.json()),
```
[the remark this answers is not in the document]
Comment (0x009922) [reply logger/src/lib.rs:64]: I _guess_ `bunyan` might read `tracing`'s JSON logs without issues (I will check). `tracing` docs [says](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/fmt/format/struct.Json.html) it might be used by some `jq` or a JSON log viewer.

Anyway, we should communicate this change to users, for sure. They will need to change logger configuration anyway.

File: logger/tests/setting_logger.rs (hunk 16 above)
Comment (0x009922) [reply logger/tests/setting_logger.rs:14]: Indeed, will fix

File: logger/src/lib.rs [hunk 20]
```diff
@@ -1,159 +1,139 @@
...
+/// # Errors
+/// If global logger was already initialised/disabled.
+pub fn disable_global() -> Result<()> {
+    try_set_logger()
 }
 
-fn add_bunyan<L>(configuration: &Configuration, layer: L) -> Result<Telemetries>
+fn step2<L>(configuration: &Configuration, layer: L) -> Result<LoggerHandle>
 where
     L: tracing_subscriber::Layer<Registry> + Debug + Send + Sync + 'static,
```
[the remark this answers is not in the document]
Comment (DCNick3) [reply logger/src/lib.rs:108]: Well, the `L` type is different for each match arm calling it. It would either need dynamic dispatch (is `Layer` object safe?) or a static dispatch via an enum, both of which would bring more problems than a separated generic function for `step2` imo

[the remark this answers is not in the document]
Comment (0x009922) [reply logger/src/lib.rs:108]: I see, thanks.

File: core/src/kiso.rs (hunk 15 above)
Comment (0x009922) [reply core/src/kiso.rs:111]: Hmm, actually now I see a way how to both use `watch` to propagate changes, but also update the actual config value in Kiso only when the change is applied. 

```mermaid
classDiagram
  class Kiso {
    Config config
    watch::Sender~LogLevelUpdate~ log_level_broadcast
    log_level_watcher() watch::Receiver~LogLevelUpdate~
  }
  class LogLevelUpdate {
    Level value
    oneshot::Sender~none~ respond_to
  }
  class Logger {
    watch_log_level(watch::Receiver~LogLevelUpdate~)
  }

  Logger <-- Kiso: sets log level
  Logger --> Kiso: notifies that log level is updated
```

```rust
let kiso: KisoHandle = _;
let logger: LoggerHandle = _;

logger.watch_log_level(kiso.log_level_watcher())
```

_Not sure how much this diagram helps_



My idea is that receiving part of `watch` channels might receive messages with `oneshot` channels to which they might reply when the change is actually applied. Therefore, when `Kiso` receives that update, it might update its `config` value, so that `GET /configuration` requests before actual value application will not return inaccurate information.

Anyway, this seem to make the whole system a little more complicated...

Comment (DCNick3) [reply core/src/kiso.rs:111]: Yeah, if we don't want it to be "fire and forget", it would probably should work like this. Though, in this case, I think, watch channels don't bring much to the table and can be just a separate `mpsc`.

Fire-and-forget or not, what I want is separation of for the actors: I think configuration updates should not go into the "main" channel, as it would require adding additional enum variants to each actor's messages and instead be handled via a separate and reusable channel type.

Though this change only makes sense if we are planning to add more updatable configuration options, otherwise it is indeed an unnecessary complication.

Comment (0x009922) [reply core/src/kiso.rs:111]: Indeed, sounds convincing. Since implementing atomicity and transaction semantics would be way too complex for a not-so-important subsystem of Iroha, fire-and-forget would be a good fit.

Let me refactor.

File: cli/src/torii/routing.rs [hunk 21]
```diff
@@ -478,7 +451,7 @@ impl Torii {
                     warp::path(uri::TRANSACTION)
                         .and(add_state!(self.queue, self.sumeragi))
                         .and(warp::body::content_length_limit(
-                            self.iroha_cfg.torii.max_content_len.into(),
+                            self.instructions_max_content_length,
```
[the remark this answers is not in the document]
Comment (0x009922) [reply cli/src/torii/routing.rs:454]: Agreed. I was confused because the function itself is still `handle_instructions`. Will rename both.

File: config/src/logger.rs (hunk 11 above)
Comment (0x009922) [reply config/src/logger.rs:29]: It is actually not:

```
error[E0204]: the trait `std::marker::Copy` cannot be implemented for this type
  --> config/src/logger.rs:26:17
   |
26 | #[derive(Debug, Copy, Clone, PartialEq, Eq, Deserialize, Serialize, Proxy, Documented)]
   |                 ^^^^
...
37 |     pub tokio_console_addr: SocketAddr,
   |     ---------------------------------- this field does not implement `std::marker::Copy`
   |
```

And it cannot be `Copy` because `SocketAddr::Host` -> `SocketAddrHost` contains `BoxedString` within.

File: cli/src/main.rs (hunk 5 above)
Comment (0x009922) [reply cli/src/main.rs]: Fixed

File: cli/src/lib.rs (hunk 17 above)
[the remark this answers is not in the document]
Comment (0x009922) [reply cli/src/lib.rs]: Refactored.

File: logger/src/telemetry.rs (hunk 6 above)
Comment (0x009922) [reply logger/src/telemetry.rs]: Updated the docstring

File: core/src/kura.rs (hunk 7 above)
Comment (0x009922) [reply core/src/kura.rs]: Removed

File: config/src/kura.rs (hunk 8 above)
Comment (0x009922) [reply config/src/kura.rs]: Removed dead code

File: cli/src/torii/routing.rs (hunk 21 above)
[the remark this answers is not in the document]
Comment (0x009922) [reply cli/src/torii/routing.rs]: Renamed both

File: client/benches/tps/oneshot.rs (hunk 9 above)
Comment (0x009922) [reply client/benches/tps/oneshot.rs]: Updated the message.

File: logger/tests/setting_logger.rs (hunk 16 above)
Comment (0x009922) [reply logger/tests/setting_logger.rs]: Fixed.

File: .gitignore (hunk 1 above)
Comment (0x009922) [reply .gitignore]: Restored `.gitignore`.

File: core/src/kiso.rs (hunk 18 above)
[the remark this answers is not in the document]
Comment (Erigara) [reply core/src/kiso.rs:139]: Looks like this error pop up when either logger layer was either poisoned or dropped, not smt we can handle meaningfully.

File: config/src/logger.rs (hunk 11 above)
Comment (DCNick3) [reply config/src/logger.rs:29]: Oh, I confused it with std's `SocketAddr`

File: core/src/kiso.rs (hunk 15 above)
Comment (0x009922) [reply core/src/kiso.rs]: Refactored.

My main goal was to loose modules coupling. Now Iroha spawns another task on startup which is responsible for updates broadcasting. It listens for `watch` updates from Kiso and forwards them to Logger, without them knowing about each other.

This seems to be the most flexible way in terms of system components independence. However, Kiso has some boilerplate which I think doesn't make sense to refactor now.

File: docs/source/references/config.md [hunk 22]
```diff
@@ -49,7 +47,8 @@ The following is the default configuration used by Iroha.
     "MAX_TRANSACTIONS_IN_BLOCK": 512,
     "ACTOR_CHANNEL_CAPACITY": 100,
     "GOSSIP_BATCH_SIZE": 500,
-    "GOSSIP_PERIOD_MS": 1000
+    "GOSSIP_PERIOD_MS": 1000,
+    "DEBUG_FORCE_SOFT_FORK": false
```
Comment (Erigara) [inline docs/source/references/config.md]: Looks like you generated `config.md` with `debug` profile. Can you please recreate it with `release`, because we don't expose `"DEBUG_FORCE_SOFT_FORK"` parameter.

Comment (0x009922) [reply docs/source/references/config.md]: Yup, I fixed it already.

File: logger/src/lib.rs (hunk 19 above)
[the remark this answers is not in the document]
Comment (0x009922) [reply logger/src/lib.rs:64]: Nope, `bunyan` cannot read it: [it requires at least the `name` field to be set](https://github.com/trentm/node-bunyan#introduction), which `tracing` doesn't provide.

File: cli/src/torii/routing.rs [hunk 23]
```diff
@@ -79,7 +74,7 @@ fn fetch_size() -> impl warp::Filter<Extract = (FetchSize,), Error = warp::Rejec
 }
 
 #[iroha_futures::telemetry_future]
-async fn handle_instructions(
+async fn handle_transaction(
```
Comment (Erigara) [inline cli/src/torii/routing.rs:77]: Good, should be renamed long ago

**Review by Erigara — APPROVED** [review]

File: README.md (hunk 4 above)
Comment (0x009922) [reply README.md]: Done.

File: docs/source/references/config.md [hunk 24]
```diff
@@ -230,7 +230,7 @@ Has type `Option<Box<kura::ConfigurationProxy>>`[^1]. Can be configured via envi
 
 Path to the existing block store folder or path to create new folder.
 
-Has type `Option<PathBuf>`[^1]. Can be configured via environment variable `KURA_BLOCK_STORE_PATH`
+Has type `Option<String>`[^1]. Can be configured via environment variable `KURA_BLOCK_STORE_PATH`
```
[the remark this answers is not in the document]
Comment (0x009922) [reply docs/source/references/config.md]: I'd postpone this change until whole configuration refactoring, which should give flexibility in parsing and types. For now, refactoring of config is painful and sometimes has non-obvious bugs.

File: core/src/kiso.rs [hunk 25]
```diff
@@ -83,37 +92,32 @@ enum Message {
...
-/// TODO
+/// Possible errors might occur while working with [`KisoHandle`]
 #[derive(thiserror::Error, Debug)]
 pub enum Error {
-    /// TODO
-    #[error("failed to dynamically update the configuration")]
-    Update(#[from] iroha_logger::ReloadError),
-    /// TODO
+    #[allow(missing_docs)]
     #[error("failed to get actor's response")]
```
[the remark this answers is not in the document]
Comment (0x009922) [reply core/src/kiso.rs:104]: Thanks for notice, will use it.

File: cli/src/lib.rs [hunk 26]
```diff
@@ -480,6 +482,34 @@ impl Iroha {
...
+            loop {
+                tokio::select! {
+                    Ok(()) = log_level_update.changed() => {
+                        let value = *log_level_update.borrow_and_update();
+                        if let Err(error) = logger.reload_level(value).await {
+                            iroha_logger::error!("Failed to reload log level: {error}");
+                        };
+                    }
+                };
+                tokio::task::yield_now().await;
```
[the remark this answers is not in the document]
Comment (0x009922) [reply cli/src/lib.rs:509]: I blindly followed the pattern in other `select!`s. It turned out that in other places loops need to yield because their futures are always awailable and it might block other actors from functioning. In this case, however, messages are expected to be rare, so I will remove it.

Original discussion: https://github.com/hyperledger/iroha/pull/3346#discussion_r1155532000

File: core/src/kiso.rs (hunk 25 above)
[the remark this answers is not in the document]
Comment (0x009922) [reply core/src/kiso.rs]: Done.

File: cli/src/lib.rs (hunk 26 above)
[the remark this answers is not in the document]
Comment (0x009922) [reply cli/src/lib.rs]: Removed.

File: core/src/kiso.rs [hunk 27]
```diff
@@ -83,37 +92,32 @@ enum Message {
...
-        }
-    }
-}
-
 struct Actor {
-    receiver: mpsc::Receiver<Message>,
+    handle: mpsc::Receiver<Message>,
     state: Configuration,
-    logger: LoggerHandle,
+    /// Current implementation is somewhat not scalable in terms of code writing: for any
```
[the remark this answers is not in the document]
Comment (0x009922) [reply core/src/kiso.rs]: Done.

**Review by Erigara — DISMISSED** [review]

File: logger/src/telemetry.rs [hunk 28]
```diff
@@ -82,70 +82,73 @@ impl Telemetry {
...
     }
 
     /// Create new telemetry layer with specific channel size (via const generic)
     #[allow(clippy::new_ret_no_self)]
     pub fn new<const CHANNEL_SIZE: usize>(
         subscriber: S,
-    ) -> (impl Subscriber, Receiver<Telemetry>, Receiver<Telemetry>) {
+    ) -> (impl Subscriber, mpsc::Receiver<ChannelEvent>) {
         let (sender, receiver) = mpsc::channel(CHANNEL_SIZE);
-        let (sender_future, receiver_future) = mpsc::channel(CHANNEL_SIZE);
```
[the remark this answers is not in the document]
Comment (0x009922) [reply logger/src/telemetry.rs:111]: Refactored, left only `with_capacity` public method.

**Review by Erigara — APPROVED** [review]

**Review by DCNick3 — APPROVED** [review]
