### PR TITLE
[fix] #3411: Properly handle peers simultaneous connection

### LINKED ISSUE #3411: [bug]: Iroha peers simultaneous connection
At the moment when two peers are trying to connect each other at the same time it's possible to face situation when them don't get connected.

### PR DESCRIPTION
**Pull request by Erigara**
## Description

- Prevent simultaneous connections by selecting who will be passive and active when connecting.
- Prevent connection duplication by keeping track of outgoing connections.
- If simultaneous connection happen add policy to resolve which connection to preserve. 

### Linked issue

Closes #3411.

### Benefits

Test flakes at much smaller rate, i run it like 10000 times without any error + works a lot faster.

There still can be cases where we can lose message (and thus `multiple_networks` test can fail).

### Checklist

- [x] I've read `CONTRIBUTING.md`
- [x] I've used the standard signed-off commit format (or will squash just before merging)
- [x] All applicable CI checks pass (or I promised to make them pass later)
- [ ] (optional) I've written unit tests for the code changes
- [ ] I replied to all comments after code review, marking all implemented changes with thumbs up

### CODE REVIEW

File: p2p/src/lib.rs [hunk 1]
```diff
@@ -150,3 +156,15 @@ pub(crate) mod unbounded_with_len {
         }
     }
 }
+
+/// Create Blake2b hash as u64 value
+pub fn blake2b_hash(slice: impl AsRef<[u8]>) -> u64 {
```
Comment (Erigara) [inline p2p/src/lib.rs:161]: I'm not sure should i place this in `iroha_crypto` because it's used only in `iroha_p2p` crate.

Comment (mversic) [reply p2p/src/lib.rs:161]: the only difference is hash length? The proper thing to do would be to make `iroha_crypto::Hash` parametrized with hash length. Which could be a very large change through the codebase, ergo I think you should leave this here

Comment (Erigara) [reply p2p/src/lib.rs:161]: The difference is that returned value is ’u64’. I initially want to do arithmetic operations on hashes, but currently i'm using only comparison. So i think i can switch to ’Hash’ directly. But with ’u64’ we still save quite some place. 
What do you think?

**Review by SamHSmith — DISMISSED** [review]
Very good solution to the problem of which connection to preserve. I did not think of this when I was trying to rewrite p2p. Do you think the sumeragi view change indices inspired this design?

File: p2p/src/lib.rs (hunk 1 above)
Comment (appetrosyan) [reply p2p/src/lib.rs:161]: Let's leave as is.

File: p2p/src/network.rs [hunk 2]
```diff
@@ -191,40 +192,40 @@ struct NetworkBase<T: Pload, K: Kex, E: Enc> {
 
 impl<T: Pload, K: Kex, E: Enc> NetworkBase<T, K, E> {
     /// [`Self`] task.
+    #[log(skip(self), fields(listen_addr=self.listen_addr, public_key=%self.public_key))]
     async fn run(mut self) {
         // TODO: probably should be configuration parameter
-        let mut update_topology_interval = tokio::time::interval(Duration::from_millis(1000));
+        let mut update_topology_interval = tokio::time::interval(Duration::from_millis(100));
```
Comment (appetrosyan) [inline p2p/src/network.rs:198]: Ideally we shouldn't have these long-term. However, I'm conscious that sometimes arbitrary numbers have to be pulled out of a hat to make things work.

Comment (Erigara) [reply p2p/src/network.rs:198]: I agree, in theory it should be possible to remove periodic topology update at all.
We will just try to reconnect if previous connection was terminated.
But for know i think periodic approach is ok.

**Comment by Erigara** [comment]
> Do you think the sumeragi view change indices inspired this design?

Im not sure what exactly affected my design.
Initially i was thinking about adding some kind of value that one peer will send to another and this value will be used as resolve connections, but i didn't want to introduce another stage of handshake.
And then i got insight that we already have such value.

**Review by mversic — APPROVED** [review]

**Review by mversic — APPROVED** [review]

**Review by mversic — APPROVED** [review]

**Review by SamHSmith — APPROVED** [review]
