### PR TITLE
[fix] #4133: Count identical wasm for triggers

### LINKED ISSUE #4133: [BUG]: "No original smartcontract saved for trigger"
```
2023-12-08 10:57:01 thread 'sumeragi thread' panicked at 'No original smartcontract saved for trigger. This is a bug.', core/src/smartcontracts/isi/triggers/set.rs:459:22
```

Originally found by @arndey 

By a quick look at the code it seems like the corresponding field or `trigger::Set` is not (de-)serialized anyhow, which may introduce this bug.

Hower @Mingela pointed that it hapens in a [test](https://github.com/soramitsu/iroha2-tools/blob/2fad47defccc967309f042e545c86cad02050562/wasm-triggers-migration/src/test/kotlin/jp/co/soramitsu/Tests.kt#L37) without loading from snapshot, so the problem needs furthes investigation.

### PR DESCRIPTION
**Pull request by Arjentix**
- See also #4160

### Linked issue

- Closes #4133 

### Checklist

- [x] I've read `CONTRIBUTING.md`
- [x] I've used the standard signed-off commit format (or will squash just before merging)
- [x] All applicable CI checks pass (or I promised to make them pass later)
- [ ] (optional) I've written unit tests for the code changes
- [ ] I replied to all comments after code review, marking all implemented changes with thumbs up

### CODE REVIEW

**Comment by DCNick3** [comment]
So, we need to implement reference-counting for when the same wasm smart contract is subscribed to several triggers. Subtle, huh

File: core/src/smartcontracts/isi/triggers/set.rs [hunk 1]
```diff
@@ -633,52 +654,96 @@ impl Set {
...
+            } else {
+                original_contracts.remove(&blob_hash)?;
+            }
+            Some(())
+        })()
+        .expect("`Set::original_contracts` doesn't contain required hash. This is a bug");
+    }
+
+    #[allow(clippy::needless_pass_by_value)]
+    fn extract_blob_hash<F>(action: LoadedAction<F>) -> Option<HashOf<WasmSmartContract>> {
```
Comment (DCNick3) [inline core/src/smartcontracts/isi/triggers/set.rs:740]: Can this be a method on `LoadedAction`?

File: core/src/smartcontracts/isi/triggers/set.rs [hunk 2]
```diff
@@ -633,52 +654,96 @@ impl Set {
...
+    fn remove_original_trigger(
+        original_contracts: &mut IndexMap<
+            HashOf<WasmSmartContract>,
+            (WasmSmartContract, NonZeroU64),
+        >,
+        blob_hash: HashOf<WasmSmartContract>,
+    ) {
+        (|| {
+            let count = &mut original_contracts.get_mut(&blob_hash)?.1;
+            if let Some(new_count) = NonZeroU64::new(count.get() - 1) {
```
Comment (DCNick3) [inline core/src/smartcontracts/isi/triggers/set.rs:729]: Weird that NonZero* types do not have `saturating_sub`, but there is some argument against them: https://internals.rust-lang.org/t/checked-sub-and-saturating-sub-for-nonzero-unsigned-integers/19898/7

File: core/src/smartcontracts/isi/triggers/set.rs [hunk 3]
```diff
@@ -633,52 +654,96 @@ impl Set {
...
+    /// Panics if `blob_hash` is not in the [`Set::original_contracts`].
+    fn remove_original_trigger(
+        original_contracts: &mut IndexMap<
+            HashOf<WasmSmartContract>,
+            (WasmSmartContract, NonZeroU64),
+        >,
+        blob_hash: HashOf<WasmSmartContract>,
+    ) {
+        (|| {
+            let count = &mut original_contracts.get_mut(&blob_hash)?.1;
```
Comment (DCNick3) [inline core/src/smartcontracts/isi/triggers/set.rs:728]: I think using `.entry` might be nicer here? By pattern matching on it, you would have only one case to raise the "`Set::original_contracts` doesn't contain required hash" panic without having to use 

Something like:

```rust
match original_contracts.entry(blob_hash) {
  Occupied(o) => {
    let (_, count) = o.get(); // I think get_mut won't work here without polonius
    if ... {
      *o.get_mut().1 = new_count;
    } else {
      o.remove_entry();
    }
  }
  Vacant(_) => panic!("..."),
}
```

File: core/src/smartcontracts/isi/triggers/set.rs (hunk 2 above)
Comment (Erigara) [reply core/src/smartcontracts/isi/triggers/set.rs:729]: Do we need `NonZero` here in the first place? It would save us some space in case of `Option<NonZero>`.
But in this case i don't see many benefits in using it.

Comment (DCNick3) [reply core/src/smartcontracts/isi/triggers/set.rs:729]: That's... Also fair

While it is true that we have an invariant that the u64 must not be zero, `NonZeroU64`'s hit to ergonomics kinda makes it not worth it to enforce the invariant at the type system level..

**Comment by Erigara** [comment]
> So, we need to implement reference-counting for when the same wasm smart contract is subscribed to several triggers. Subtle, huh

Afaik trigger id should be unique so instead of mapping (hash, (wasm,counter)) we can have (id, wasm).
It would have redundant entities, but code should be a bit more clear i guess

File: core/src/smartcontracts/isi/triggers/set.rs (hunk 2 above)
Comment (Arjentix) [reply core/src/smartcontracts/isi/triggers/set.rs:729]: I think it's more robust than just an integer type, because it introduces invariants which are useful in this scenario. Count should either be > 0 or doesn't exist

Comment (Arjentix) [reply core/src/smartcontracts/isi/triggers/set.rs:729]: It's also a documentation for future developers

Comment (Arjentix) [reply core/src/smartcontracts/isi/triggers/set.rs:729]: > NonZeroU64's hit to ergonomics kinda makes it not worth it to enforce the invariant at the type system level..

I don't think having just an unsigned integer type would help much, because I will still need to check for zero case

Comment (DCNick3) [reply core/src/smartcontracts/isi/triggers/set.rs:729]: I just don't like the `NonZeroU64::new(v.get() - 1)` dance, but no strong feelings, it can stay.

File: core/src/smartcontracts/isi/triggers/set.rs (hunk 3 above)
Comment (Arjentix) [reply core/src/smartcontracts/isi/triggers/set.rs:728]: You're right. Currently I'm doing the search twice. Don't know how I missed that

File: core/src/smartcontracts/isi/triggers/set.rs [hunk 4]
```diff
@@ -633,52 +663,92 @@ impl Set {
...
+    /// or remove it if the counter reaches zero.
+    ///
+    /// # Panics
+    ///
+    /// Panics if `blob_hash` is not in the [`Set::original_contracts`].
+    fn remove_original_trigger(
+        original_contracts: &mut IndexMap<
+            HashOf<WasmSmartContract>,
+            (WasmSmartContract, NonZeroU64),
+        >,
```
Comment (Erigara) [inline core/src/smartcontracts/isi/triggers/set.rs:733]: Can we make type alias for this type? 

```rust
type WasmSmartContractMap = IndexMap<HashOf<WasmSmartContract>,(WasmSmartContract, NonZeroU64)>;
```

**Review by Erigara — APPROVED** [review]

**Review by DCNick3 — APPROVED** [review]
