### PR TITLE
ci: use Nextest, remove broken rust-cache, more unit test coverage

### LINKED ISSUE #4499: Investigate why `actions/setup-python@v5` fails sometimes in `I2::CI::check_for_incorrect_images`
The `I2::CI::check_for_incorrect_images` job fails sometimes with the following:

```
Error: The version '3.11' with architecture 'x64' was not found for this operating system.
```

[Example log](https://github.com/hyperledger/iroha/actions/runs/8796269117/job/24138820362#step:2:270)

### LINKED ISSUE #4854: Restore no-default-features unit tests
I think we also used to have tests for no-default-features

_Originally posted by @nxsaken in https://github.com/hyperledger/iroha/pull/4835#discussion_r1675504442_

### PR DESCRIPTION
**Pull request by nxsaken**
## Context

This PR sets up `cargo nextest` for running Rust tests, and makes other CI-related improvements:

- Run unit tests with `no-default-features` (closes #4854)
- Retry client pytests (follow-up ticket: https://github.com/hyperledger/iroha/issues/5014)
- Do not build/download the default executor where it's not needed (post #4931)
- ~Caching dependencies should actually work now (switch from [`rust-cache`](https://github.com/Swatinem/rust-cache) to [`cargo-cache`](https://github.com/Leafwing-Studios/cargo-cache)), cache is shared between similar jobs~
  - Self-hosted runners don't work with `cargo-cache`, and `rust-cache` never seems to hit the cache even though it writes to it.
- Fixes #4499 (specifies the exact Ubuntu version)

---

### Checklist

- [x] Finish fixing client pytests
- [x] I've read [`CONTRIBUTING.md`](../CONTRIBUTING.md).
- [ ] (optional) I've written unit tests for the code changes.
- [ ] All review comments have been resolved.

### CODE REVIEW

File: scripts/tests/consistency.sh [hunk 1]
```diff
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
```
Comment (mversic) [inline scripts/tests/consistency.sh:1]: there is no need for this?

File: .github/workflows/iroha2-release.yml [hunk 2]
```diff
@@ -7,24 +7,29 @@ on:
...
       - uses: Swatinem/rust-cache@v2
       - name: Build iroha executor
-        run: cargo run --bin iroha_wasm_builder -- build ./wasm_samples/default_executor --optimize --out-file ${{ env.DOCKER_COMPOSE_PATH }}/executor.wasm
+        run: cargo run --bin iroha_wasm_builder -- build ./wasm_samples/default_executor --optimize --out-file ${{ env.DEFAULTS_PATH }}/executor.wasm
       - name: Upload executor to reuse in other jobs
         uses: actions/upload-artifact@v4
         with:
           name: executor.wasm
-          path: ${{ env.DOCKER_COMPOSE_PATH }}/executor.wasm
+          path: ${{ env.DEFAULTS_PATH }}/executor.wasm
```
Comment (mversic) [inline .github/workflows/iroha2-release.yml:32]: don't change this name

**Review by mversic — DISMISSED** [review]

File: .github/workflows/iroha2-dev-pr-wasm.yaml [hunk 3]
```diff
@@ -41,20 +49,26 @@ jobs:
...
+          # needed to build smart contracts
+          components: rust-src
+      - uses: Leafwing-Studios/cargo-cache@v2
+        with:
+          sweep-cache: true
       - name: Install iroha_wasm_test_runner
         run: cargo install --path tools/wasm_test_runner
       - name: Run smart contract tests on WebAssembly VM
         working-directory: smart_contract
-        run: mold --run cargo test -p iroha_smart_contract -p iroha_smart_contract_utils --release --tests --target wasm32-unknown-unknown --no-fail-fast --quiet
```
Comment (BAStos525) [inline .github/workflows/iroha2-dev-pr-wasm.yaml:60]: Is it better without mold?

File: .github/workflows/iroha2-dev-pr.yml [hunk 4]
```diff
@@ -161,54 +236,30 @@ jobs:
...
-        run: cargo doc --no-deps --quiet
-      - name: Upload clippy report artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: clippy.json
-          path: clippy.json
-
-  torii-api-client-cli-tests:
-    runs-on: [self-hosted, Linux, iroha2]
+  docker-compose-and-pytests:
```
Comment (BAStos525) [inline .github/workflows/iroha2-dev-pr.yml:239]: Did you test it?

File: .github/workflows/iroha2-dev-nightly.yml [hunk 5]
```diff
@@ -3,17 +3,25 @@ name: I2::Dev::Nightly::Publish
...
 
 env:
+  RUST_TOOLCHAIN: nightly-2024-04-18
   DOCKER_COMPOSE_PATH: defaults
 
 jobs:
   build_executor:
-    runs-on: ubuntu-latest
-    container:
-      image: hyperledger/iroha2-ci:nightly-2024-04-18
```
Comment (BAStos525) [inline .github/workflows/iroha2-dev-nightly.yml:12]: We don't need `Dockerfile.build` then

File: .github/workflows/iroha2-dev-pr-wasm.yaml (hunk 3 above)
Comment (nxsaken) [reply .github/workflows/iroha2-dev-pr-wasm.yaml:60]: There's no mold on mac (except a commercial version), and mac's linker is as good as mold

File: .github/workflows/iroha2-dev-nightly.yml (hunk 5 above)
Comment (nxsaken) [reply .github/workflows/iroha2-dev-nightly.yml:12]: There is at least one job left that still uses the self-hosted runner. I'll see if I can move it too

File: .github/workflows/iroha2-dev-pr.yml (hunk 4 above)
Comment (BAStos525) [reply .github/workflows/iroha2-dev-pr.yml:239]: Yeah, it has different name, sorry. We have to filter the job with old name

**Review by BAStos525 — APPROVED** [review]

**Review by Erigara — APPROVED** [review]

**Comment by nxsaken** [comment]
Squashed commits to resolve conflicts faster, removed retries in `extra_functional` tests. Nothing else changed

File: .github/workflows/iroha2-dev-nightly.yml [hunk 6]
```diff
@@ -3,17 +3,26 @@ name: I2::Dev::Nightly::Publish
...
+    runs-on: macos-latest
     timeout-minutes: 30
     steps:
       - uses: actions/checkout@v4
-      - uses: Swatinem/rust-cache@v2
+      - uses: dtolnay/rust-toolchain@master
+        with:
+          toolchain: ${{ env.RUST_TOOLCHAIN }}
+          targets: aarch64-apple-darwin,wasm32-unknown-unknown
```
Comment (mversic) [inline .github/workflows/iroha2-dev-nightly.yml:18]: why both targets?

File: .github/workflows/iroha2-dev-nightly.yml [hunk 7]
```diff
@@ -3,17 +3,26 @@ name: I2::Dev::Nightly::Publish
...
+          # needed to build smart contracts
+          components: rust-src
+      - uses: Leafwing-Studios/cargo-cache@v2
```
Comment (mversic) [inline .github/workflows/iroha2-dev-nightly.yml:21]: how's it different/better than `rust-cache`?

Comment (nxsaken) [reply .github/workflows/iroha2-dev-nightly.yml:21]: `rust-cache` never hits the cache for some reason

File: .github/workflows/iroha2-dev-nightly.yml [hunk 8]
```diff
@@ -3,17 +3,26 @@ name: I2::Dev::Nightly::Publish
...
 env:
+  RUST_TOOLCHAIN: nightly-2024-04-18
   DOCKER_COMPOSE_PATH: defaults
 
 jobs:
   build_executor:
-    runs-on: ubuntu-latest
-    container:
-      image: hyperledger/iroha2-ci:nightly-2024-04-18
+    runs-on: macos-latest
```
Comment (mversic) [inline .github/workflows/iroha2-dev-nightly.yml:11]: what was the reason for the switch? also, we don't get to use `mold` anymore

Comment (nxsaken) [reply .github/workflows/iroha2-dev-nightly.yml:11]: Building on M1 should be faster, and Apple's `ld-prime` is as good as `mold`

File: .github/workflows/iroha2-dev-nightly.yml (hunk 6 above)
Comment (nxsaken) [reply .github/workflows/iroha2-dev-nightly.yml:18]: Forgot to remove it

**Comment by 0x009922** [comment]
Looks good, what prevents from merging it?

**Comment by nxsaken** [comment]
@0x009922 the self-hosted runners seem to be working fine again, and macOS runners stopped being faster. We agreed with @BAStos525 a while ago to wait and compare before deciding whether to ditch the macOS runners and merge the rest of the changes. I'll pick this up today

**Comment by nxsaken** [comment]
The caching action doesn't seem to work with a self-hosted runner :/

File: .github/workflows/iroha2-custom-image.yml [hunk 9]
```diff
@@ -41,15 +42,19 @@ env:
...
-    runs-on: ubuntu-latest
+    runs-on: [self-hosted, Linux, iroha2]
     container:
       image: hyperledger/iroha2-ci:nightly-2024-09-09
     timeout-minutes: 30
     steps:
       - uses: actions/checkout@v4
         with:
           ref: ${{ github.event.inputs.CHECKOUT_REF }}
-      - uses: Swatinem/rust-cache@v2
```
Comment (BAStos525) [inline .github/workflows/iroha2-custom-image.yml:52]: May be to continue to use the old rust cache Action if the new one doesn't always work?

Comment (nxsaken) [reply .github/workflows/iroha2-custom-image.yml:52]: The old one is broken. It never hits the cache despite writing to it

File: .github/workflows/iroha2-ci-image.yml [hunk 10]
```diff
@@ -9,7 +9,9 @@ on:
 
 jobs:
   dockerhub:
-    runs-on: ubuntu-latest
```
Comment (BAStos525) [inline .github/workflows/iroha2-ci-image.yml:12]: For some jobs that are not really heavy and sensitive to execution time, no reason to use paid runners. I would revert to `ubuntu-latest`

File: .github/workflows/iroha2-custom-image.yml [hunk 11]
```diff
@@ -41,15 +42,19 @@ env:
 
 jobs:
   build_executor:
-    runs-on: ubuntu-latest
+    runs-on: [self-hosted, Linux, iroha2]
```
Comment (BAStos525) [inline .github/workflows/iroha2-custom-image.yml:45]: It's not so heavy. May be on self-hosted it will be a bit faster, but we lose in time to rise up the runner and cost management

File: .github/workflows/iroha2-dev-nightly.yml [hunk 12]
```diff
@@ -24,7 +30,7 @@ jobs:
           retention-days: 1
 
   dockerhub:
-    runs-on: ubuntu-latest
+    runs-on: [self-hosted, Linux, iroha2]
```
Comment (BAStos525) [inline .github/workflows/iroha2-dev-nightly.yml:33]: same

**Review by BAStos525 — CHANGES_REQUESTED** [review]

File: .github/workflows/iroha2-no-incorrect-image.yml [hunk 13]
```diff
@@ -8,12 +8,12 @@ on:
 
 jobs:
   check:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-22.04
```
Comment (BAStos525) [inline .github/workflows/iroha2-no-incorrect-image.yml:11]: What is the need? Is it related to Python installation?

Comment (nxsaken) [reply .github/workflows/iroha2-no-incorrect-image.yml:11]: If you don't specify the version, the install-python action breaks randomly: https://github.com/hyperledger/iroha/issues/4499

**Comment by nxsaken** [comment]
@BAStos525 UI tests fail with the memory issue you've mentioned before, should they also use the self-hosted runners?

File: .github/workflows/iroha2-no-incorrect-image.yml (hunk 13 above)
Comment (BAStos525) [reply .github/workflows/iroha2-no-incorrect-image.yml:11]: Okay. What about `ubuntu-24.04` then?

**Comment by BAStos525** [comment]
> @BAStos525 UI tests fail with the disk space issue you've mentioned before, should they also use the self-hosted runners?

Sure. We can try self-hosted runners

File: .github/workflows/iroha2-no-incorrect-image.yml (hunk 13 above)
Comment (nxsaken) [reply .github/workflows/iroha2-no-incorrect-image.yml:11]: I don't remember why I picked 22.04, don't mind switching to 24.04.

**Review by BAStos525 — APPROVED** [review]

**Review by 0x009922 — APPROVED** [review]
