### PR TITLE
[fix] #2880: Close websocket connection properly

### LINKED ISSUE #2880: [BUG] Block Streaming API doesn't work as a stream
### GIT commit hash

b783f10fa7de26ed1fdd4c526bd162f8636f1a65

### Minimum working example

- Start Iroha with any configuration, peers amount and genesis
- Listen for Blocks Stream via any existing client
- Inspect incoming blocks

### Expected behaviour

I expected to see how blocks are sent from Iroha on-the-fly when they appear in the blockchain.

### Actual behaviour

I got all existing blocks Iroha had (depending on the `height` param I've provided on the handshake) and then Iroha halted the connection.

[Spec](https://github.com/appetrosyan/iroha/blob/iroha2-staging/docs/source/references/api_spec.md#blocks-stream) says:

> Via this endpoint client first provides the starting block number(i.e. height) in the subscription request. After sending the confirmation message, server starts streaming all the blocks from the given block number up to the current block and continues to stream blocks as they are added to the blockchain.

### Operating system

Both on local macOS 12.2.1 and in a docker image you can explore [here](https://github.com/hyperledger/iroha-javascript/blob/f90aaffaeae9f2332b2a567b54f3f7cb879ec7e8/Jenkinsfile) 

### LibC type and version

On macOS I can't determine; what is within the docker image - same

### Current environment

Source code build

### Logs in JSON format

<details>
  <summary>Log contents (log from the automated test)</summary>
  
  ```
[2022-10-18T13:53:21.026Z] 2022-10-18T13:53:20.958Z @iroha2/test-peer:stdout 2022-10-18T13:53:20.958135Z  INFO iroha: Hyperledgerいろは2にようこそ！
[2022-10-18T13:53:21.026Z] 2022-10-18T13:53:20.958Z @iroha2/test-peer:stdout 2022-10-18T13:53:20.958155Z  INFO iroha: (translation) Welcome to Hyperledger Iroha 2!
[2022-10-18T13:53:21.026Z] 2022-10-18T13:53:20.958Z @iroha2/test-peer:stdout 2022-10-18T13:53:20.958815Z  INFO iroha: Starting peer listen_addr=127.0.0.1:1337
[2022-10-18T13:53:21.027Z] 2022-10-18T13:53:20.958Z @iroha2/test-peer:stdout 2022-10-18T13:53:20.958831Z  INFO iroha_p2p::network: Binding listener listen_addr=127.0.0.1:1337
[2022-10-18T13:53:21.027Z] 2022-10-18T13:53:20.958Z @iroha2/test-peer:stdout 2022-10-18T13:53:20.958866Z  INFO iroha_p2p::network: Starting network actor listen_addr=127.0.0.1:1337
[2022-10-18T13:53:21.027Z] 2022-10-18T13:53:20.961Z @iroha2/test-peer:stdout 2022-10-18T13:53:20.961077Z  INFO iroha_core::kura: Loaded 0 blocks at init.
[2022-10-18T13:53:21.027Z] 2022-10-18T13:53:20.962Z @iroha2/test-peer:stdout 2022-10-18T13:53:20.962445Z ERROR iroha: Telemetry did not start
[2022-10-18T13:53:21.027Z] 2022-10-18T13:53:20.962Z @iroha2/test-peer:stdout 2022-10-18T13:53:20.962772Z  INFO iroha: Starting Iroha
[2022-10-18T13:53:21.027Z] 2022-10-18T13:53:21.007Z @iroha2/test-peer:stdout 2022-10-18T13:53:21.007667Z  INFO request{method=GET path=/health version=HTTP/1.1 remote.addr=127.0.0.1:55636}: warp::filters::trace: processing request
[2022-10-18T13:53:21.027Z] 2022-10-18T13:53:21.007Z @iroha2/test-peer:stdout 2022-10-18T13:53:21.007739Z  INFO request{method=GET path=/health version=HTTP/1.1 remote.addr=127.0.0.1:55636}: warp::filters::trace: finished processing with success status=200
[2022-10-18T13:53:21.027Z] 2022-10-18T13:53:21.009Z @iroha2/test-peer:stdout 2022-10-18T13:53:21.009093Z  INFO request{method=GET path=/status version=HTTP/1.1 remote.addr=127.0.0.1:42540}: warp::filters::trace: processing request
[2022-10-18T13:53:21.027Z] 2022-10-18T13:53:21.009Z @iroha2/test-peer:stdout 2022-10-18T13:53:21.009136Z  INFO request{method=GET path=/status version=HTTP/1.1 remote.addr=127.0.0.1:42540}: warp::filters::trace: finished processing with success status=200
[2022-10-18T13:53:21.282Z] 2022-10-18T13:53:21.212Z @iroha2/test-peer:stdout 2022-10-18T13:53:21.212836Z  INFO run{shutdown_receiver=Receiver { inner: Some(Inner { state: State { is_complete: false, is_closed: false, is_rx_task_set: false, is_tx_task_set: false } }) }}: iroha_core::sumeragi::main_loop: Initializing iroha using the genesis block.
[2022-10-18T13:53:21.282Z] 2022-10-18T13:53:21.213Z @iroha2/test-peer:stdout 2022-10-18T13:53:21.212889Z  INFO run{shutdown_receiver=Receiver { inner: Some(Inner { state: State { is_complete: false, is_closed: false, is_rx_task_set: false, is_tx_task_set: false } }) }}: iroha_core::sumeragi::main_loop: Publishing genesis block. block_hash=e70e18a61d4fc0cd66fba31b8a0985ff881cbaafea0925bafacfebfc5dbf88c4
[2022-10-18T13:53:21.282Z] 2022-10-18T13:53:21.213Z @iroha2/test-peer:stdout 2022-10-18T13:53:21.213303Z  INFO run{shutdown_receiver=Receiver { inner: Some(Inner { state: State { is_complete: false, is_closed: false, is_rx_task_set: false, is_tx_task_set: false } }) }}: iroha_core::sumeragi::main_loop: Created a block to commit. peer_role=Leader block_hash=2348e1537306cb3ab812c22a85c74cc6130ffc3fd8683b9428d6e01a442ac8da
[2022-10-18T13:53:21.282Z] 2022-10-18T13:53:21.213Z @iroha2/test-peer:stdout 2022-10-18T13:53:21.213755Z ERROR run{shutdown_receiver=Receiver { inner: Some(Inner { state: State { is_complete: false, is_closed: false, is_rx_task_set: false, is_tx_task_set: false } }) }}: iroha_core::sumeragi::main_loop: Some events failed to be sent e=channel closed
[2022-10-18T13:53:21.282Z] 2022-10-18T13:53:21.213Z @iroha2/test-peer:stdout 2022-10-18T13:53:21.213775Z ERROR run{shutdown_receiver=Receiver { inner: Some(Inner { state: State { is_complete: false, is_closed: false, is_rx_task_set: false, is_tx_task_set: false } }) }}: iroha_core::sumeragi::main_loop: Some events failed to be sent e=channel closed
[2022-10-18T13:53:21.282Z] 2022-10-18T13:53:21.213Z @iroha2/test-peer:stdout 2022-10-18T13:53:21.213798Z  INFO run{shutdown_receiver=Receiver { inner: Some(Inner { state: State { is_complete: false, is_closed: false, is_rx_task_set: false, is_tx_task_set: false } }) }}: iroha_core::sumeragi::main_loop: Committing block prev_peer_role=Leader new_peer_role=Leader new_block_height=1 block_hash=2348e1537306cb3ab812c22a85c74cc6130ffc3fd8683b9428d6e01a442ac8da
[2022-10-18T13:53:21.282Z] 2022-10-18T13:53:21.259Z @iroha2/test-peer:stdout 2022-10-18T13:53:21.259760Z  INFO request{method=GET path=/status version=HTTP/1.1 remote.addr=127.0.0.1:42542}: warp::filters::trace: processing request
[2022-10-18T13:53:21.282Z] 2022-10-18T13:53:21.259Z @iroha2/test-peer:stdout 2022-10-18T13:53:21.259828Z  INFO request{method=GET path=/status version=HTTP/1.1 remote.addr=127.0.0.1:42542}: warp::filters::trace: finished processing with success status=200
[2022-10-18T13:53:21.282Z] 2022-10-18T13:53:21.261Z @iroha2/client:blocks-stream:websocket opening connection to 'ws://127.0.0.1:8080/block/stream'
[2022-10-18T13:53:21.282Z] 2022-10-18T13:53:21.262Z @iroha2/test-peer:stdout 2022-10-18T13:53:21.262124Z  INFO request{method=GET path=/block/stream version=HTTP/1.1 remote.addr=127.0.0.1:55642}: warp::filters::trace: processing request
[2022-10-18T13:53:21.282Z] 2022-10-18T13:53:21.262Z @iroha2/test-peer:stdout 2022-10-18T13:53:21.262197Z  INFO request{method=GET path=/block/stream version=HTTP/1.1 remote.addr=127.0.0.1:55642}: warp::filters::trace: finished processing with status status=101 error=None
[2022-10-18T13:53:21.282Z] 2022-10-18T13:53:21.262Z @iroha2/client:blocks-stream:websocket connection opened
[2022-10-18T13:53:21.282Z] 2022-10-18T13:53:21.262Z @iroha2/client:blocks-stream:websocket message Uint8Array(2) [ 1, 0 ]
[2022-10-18T13:53:21.282Z] 2022-10-18T13:53:21.263Z @iroha2/client:blocks-stream subscription accepted
[2022-10-18T13:53:21.282Z] 2022-10-18T13:53:21.264Z @iroha2/client:blocks-stream:websocket message Uint8Array(1957) [
[2022-10-18T13:53:21.282Z]     1,   1,   1,  60, 201,  94, 235, 131,   1,   0,   0,   0,
[2022-10-18T13:53:21.282Z]     0,   0,   0,   0,   0,   0,   0, 208,   7,   0,   0,   0,
[2022-10-18T13:53:21.282Z]     0,   0,   0,   1,   0,   0,   0,   0,   0,   0,   0,   0,
[2022-10-18T13:53:21.282Z]     0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
[2022-10-18T13:53:21.282Z]     0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
[2022-10-18T13:53:21.282Z]     0,   0,   0,   0,   0,   0,   0,  49,  86, 120, 244, 149,
[2022-10-18T13:53:21.282Z]    19, 148, 118, 168, 159, 206, 242, 128, 104,  40, 131,  22,
[2022-10-18T13:53:21.282Z]    95, 111,  82, 246, 183,  74, 141,  34,  87,  39,  88, 244,
[2022-10-18T13:53:21.282Z]   133, 165,  93,   0,
[2022-10-18T13:53:21.282Z]   ... 1857 more items
[2022-10-18T13:53:21.282Z] ]
[2022-10-18T13:53:21.283Z] 2022-10-18T13:53:21.267Z @iroha2/client:blocks-stream new block: Enum { tag: 'V1', value: { header: { timestamp: 1666101201212n, consensus_estimation: 2000n, height: 1n, previous_block_hash: [Uint8Array], transactions_hash: [Uint8Array], rejected_transactions_hash: [Uint8Array], genesis_topology: [Enum] }, rejected_transactions: [], transactions: [ [Enum] ], event_recommendations: [], signatures: { signatures: [Map] } } }
[2022-10-18T13:53:21.283Z] 2022-10-18T13:53:21.277Z @iroha2/client:blocks-stream:websocket message Uint8Array(1957) [
[2022-10-18T13:53:21.283Z]     1,   1,   1,  60, 201,  94, 235, 131,   1,   0,   0,   0,
[2022-10-18T13:53:21.283Z]     0,   0,   0,   0,   0,   0,   0, 208,   7,   0,   0,   0,
[2022-10-18T13:53:21.283Z]     0,   0,   0,   1,   0,   0,   0,   0,   0,   0,   0,   0,
[2022-10-18T13:53:21.283Z]     0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
[2022-10-18T13:53:21.283Z]     0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
[2022-10-18T13:53:21.283Z]     0,   0,   0,   0,   0,   0,   0,  49,  86, 120, 244, 149,
[2022-10-18T13:53:21.283Z]    19, 148, 118, 168, 159, 206, 242, 128, 104,  40, 131,  22,
[2022-10-18T13:53:21.283Z]    95, 111,  82, 246, 183,  74, 141,  34,  87,  39,  88, 244,
[2022-10-18T13:53:21.283Z]   133, 165,  93,   0,
[2022-10-18T13:53:21.283Z]   ... 1857 more items
[2022-10-18T13:53:21.283Z] ]
[2022-10-18T13:53:21.283Z] 2022-10-18T13:53:21.279Z @iroha2/client:blocks-stream new block: Enum { tag: 'V1', value: { header: { timestamp: 1666101201212n, consensus_estimation: 2000n, height: 1n, previous_block_hash: [Uint8Array], transactions_hash: [Uint8Array], rejected_transactions_hash: [Uint8Array], genesis_topology: [Enum] }, rejected_transactions: [], transactions: [ [Enum] ], event_recommendations: [], signatures: { signatures: [Map] } } }
[2022-10-18T13:53:21.283Z] 2022-10-18T13:53:21.279Z @iroha2/test-peer:stdout 2022-10-18T13:53:21.277348Z  INFO request{method=POST path=/transaction version=HTTP/1.1 remote.addr=127.0.0.1:55644}: warp::filters::trace: processing request
[2022-10-18T13:53:21.283Z] 2022-10-18T13:53:21.279Z @iroha2/test-peer:stdout 2022-10-18T13:53:21.277615Z  INFO request{method=POST path=/transaction version=HTTP/1.1 remote.addr=127.0.0.1:55644}: warp::filters::trace: finished processing with success status=200
[2022-10-18T13:53:21.539Z] 2022-10-18T13:53:21.289Z @iroha2/test-peer:stdout 2022-10-18T13:53:21.289618Z  INFO request{method=POST path=/transaction version=HTTP/1.1 remote.addr=127.0.0.1:55646}: warp::filters::trace: processing request
[2022-10-18T13:53:21.539Z] 2022-10-18T13:53:21.289Z @iroha2/client:blocks-stream:websocket connection closed; code: 1006, reason: '', was clean: false
[2022-10-18T13:53:21.539Z] 2022-10-18T13:53:21.290Z @iroha2/test-peer:stdout 2022-10-18T13:53:21.289843Z  INFO request{method=POST path=/transaction version=HTTP/1.1 remote.addr=127.0.0.1:55646}: warp::filters::trace: finished processing with success status=200
[2022-10-18T13:53:21.539Z] 2022-10-18T13:53:21.375Z @iroha2/test-peer:stdout 2022-10-18T13:53:21.375896Z  INFO run{shutdown_receiver=Receiver { inner: Some(Inner { state: State { is_complete: false, is_closed: false, is_rx_task_set: false, is_tx_task_set: false } }) }}: iroha_core::sumeragi::main_loop: sumeragi Doing block with 2 txs.
[2022-10-18T13:53:21.539Z] 2022-10-18T13:53:21.376Z @iroha2/test-peer:stdout 2022-10-18T13:53:21.376556Z ERROR run{shutdown_receiver=Receiver { inner: Some(Inner { state: State { is_complete: false, is_closed: false, is_rx_task_set: false, is_tx_task_set: false } }) }}: iroha_core::sumeragi::main_loop: Some events failed to be sent e=channel closed
[2022-10-18T13:53:21.539Z] 2022-10-18T13:53:21.376Z @iroha2/test-peer:stdout 2022-10-18T13:53:21.376573Z ERROR run{shutdown_receiver=Receiver { inner: Some(Inner { state: State { is_complete: false, is_closed: false, is_rx_task_set: false, is_tx_task_set: false } }) }}: iroha_core::sumeragi::main_loop: Some events failed to be sent e=channel closed
[2022-10-18T13:53:21.539Z] 2022-10-18T13:53:21.376Z @iroha2/test-peer:stdout 2022-10-18T13:53:21.376577Z ERROR run{shutdown_receiver=Receiver { inner: Some(Inner { state: State { is_complete: false, is_closed: false, is_rx_task_set: false, is_tx_task_set: false } }) }}: iroha_core::sumeragi::main_loop: Some events failed to be sent e=channel closed
[2022-10-18T13:53:21.539Z] 2022-10-18T13:53:21.376Z @iroha2/test-peer:stdout 2022-10-18T13:53:21.376594Z  INFO run{shutdown_receiver=Receiver { inner: Some(Inner { state: State { is_complete: false, is_closed: false, is_rx_task_set: false, is_tx_task_set: false } }) }}: iroha_core::sumeragi::main_loop: Committing block prev_peer_role=Leader new_peer_role=Leader new_block_height=2 block_hash=d3d161d659abcc6635b3ce0960538eeb029b9406a4ffd8142682471cbd42937e
[2022-10-18T13:53:26.832Z] 2022-10-18T13:53:26.263Z @iroha2/test-peer Killing peer...
[2022-10-18T13:53:26.832Z] 2022-10-18T13:53:26.266Z @iroha2/test-peer:stdout 2022-10-18T13:53:26.265920Z  INFO run{shutdown_receiver=Receiver { inner: Some(Inner { state: State { is_complete: false, is_closed: false, is_rx_task_set: false, is_tx_task_set: false } }) }}: iroha_core::sumeragi::main_loop: Sumeragi Thread is being shutdown shut down.
[2022-10-18T13:53:26.832Z] 2022-10-18T13:53:26.266Z @iroha2/test-peer:stdout 2022-10-18T13:53:26.266813Z  INFO iroha_core::kura: Kura block thread is being shut down
[2022-10-18T13:53:26.832Z] 2022-10-18T13:53:26.266Z @iroha2/test-peer:stdout 2022-10-18T13:53:26.266834Z  INFO iroha_core::kura: Kura block thread is shutting down
[2022-10-18T13:53:26.832Z] 2022-10-18T13:53:26.268Z @iroha2/test-peer Peer exited: [ 0, null ]
[2022-10-18T13:53:26.832Z] 2022-10-18T13:53:26.269Z @iroha2/test-peer Peer is killed
  ```
</details>

### Who can help?

@appetrosyan

### PR DESCRIPTION
**Pull request by Erigara**
Signed-off-by: Shanin Roman <shanin1000@yandex.ru>

### Description of the Change

Close websocket connection properly.

### Issue

Closes #2880. 

### Benefits

Properly closed connection. 

### Possible Drawbacks

None.

### CODE REVIEW

**Comment by appetrosyan** [comment]
Can we also fix `panic_on_invalid_genesis.sh`?

File: cli/src/torii/routing.rs [hunk 1]
```diff
@@ -296,7 +321,7 @@ async fn stream_blocks(
         if let BlockSubscriberMessage::BlockReceived = message.into_v1() {
             *from_height += 1;
         } else {
-            return Err(eyre!("Expected `BlockReceived` message"));
+            eyre::bail!("Expected `BlockReceived` message")
```
Comment (appetrosyan) [inline cli/src/torii/routing.rs:324]: Specify what we got instead.

**Review by appetrosyan — APPROVED** [review]

**Review by pesterev — APPROVED** [review]
LGTM
