### PR TITLE
fix(crypto): do not panic if the passed Ed25519Sha512 public key is of invalid length

### LINKED ISSUE #4649: `iroha_crypto` panic
when I try to decode `04000001aeeba99f825cf8e4e6d7270b30fd927aa4c5b030df2ff891f28c2cc5b6d5d7990000
` hex string with `parity_scale_decoder` I get a panic like this:

```
thread 'main' panicked at crypto/src/signature/ed25519.rs:31:31:
range end index 32 out of range for slice of length 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This happens on `v2.0.0-pre-rc.21.3` branch so it may not be a problem anymore

### PR DESCRIPTION
**Pull request by DCNick3**
## Description

Change the conversion of unsized slice to array reference to be infallible and form a better error message.

This prevents a panic during `parity_scale_cli`'s type probing

### Linked issue

Closes #4649 

### Checklist

- [ ] make CI pass

### CODE REVIEW

File: crypto/src/signature/ed25519.rs [hunk 1]
```diff
@@ -11,7 +11,23 @@ pub type PublicKey = ed25519_dalek::VerifyingKey;
 pub type PrivateKey = ed25519_dalek::SigningKey;
 
 #[cfg(not(feature = "std"))]
-use alloc::{string::ToString as _, vec::Vec};
+use alloc::{format, string::ToString as _, vec::Vec};
+
+fn parse_fixed_size<T, E, F, const SIZE: usize>(payload: &[u8], f: F) -> Result<T, ParseError>
```
Comment (VAmuzing) [inline crypto/src/signature/ed25519.rs:16]: We have both `f`'s and custom names for `Fn...` in the code. Do you think we should name it `f` here or maybe use some custom name?
Besides that everything looks good.

**Review by VAmuzing — DISMISSED** [review]

File: crypto/src/signature/ed25519.rs (hunk 1 above)
Comment (DCNick3) [reply crypto/src/signature/ed25519.rs]: Yeah, naming things is good. Renamed to `fixed_parser` (because it parses a fixed-size array)

**Review by VAmuzing — APPROVED** [review]

**Review by mversic — APPROVED** [review]
