### PR TITLE
fix: Fix `iroha_genesis` compilation without `transparent_api` feature

### LINKED ISSUE #5049: Cannot compile `iroha_genesis`: uses private fields from `iroha_data_model`
## Context

Using `iroha_data_model` crate as a dependency _without_ `transparent_api` feature.

Getting these compilation errors from dependent `iroha_genesis`:

```
error[E0616]: field `sumeragi` of struct `iroha_data_model::parameter::Parameters` is private
   --> iroha/genesis/src/lib.rs:358:18
    |
358 |         Sumeragi(sumeragi.max_clock_drift_ms) => SumeragiParameter::MaxClockDriftMs,
    |                  ^^^^^^^^ private field

```

- Was introduced by: #5020 
- General issue: #5050

### Fix

Add `transparent_api` feature:

https://github.com/hyperledger/iroha/blob/b4329102eeff4623ea27a23bdc3c86c26ee8a920/genesis/Cargo.toml#L16

### PR DESCRIPTION
**Pull request by dima74**
## Context

Fixes #5049

### Solution

* Moved `apply_parameter` function to the `data_model`
* Also fixed port for some tests:
  * `reported_length_should_be_accurate` used port 11_170 which conflicts with `register_offline_peer`
  * `json_and_scale_statuses_equality` used port 11_200 which conflicts with `restarted_peer_should_have_the_same_asset_amount`

### Checklist

- [ ] I've read [`CONTRIBUTING.md`](../CONTRIBUTING.md).
- [ ] (optional) I've written unit tests for the code changes.
- [ ] All review comments have been resolved.
- [ ] All CI checks pass.

### CODE REVIEW

File: data_model/src/parameter.rs [hunk 1]
```diff
@@ -458,6 +458,41 @@ impl Parameters {
             )
             .chain(self.custom.values().cloned().map(Parameter::Custom))
     }
+
+    /// Set `parameter` value to corresponding parameter in `self`
+    pub fn apply_parameter(&mut self, parameter: Parameter) {
```
Comment (mversic) [inline data_model/src/parameter.rs:463]:
```suggestion
    pub fn set_parameter(&mut self, parameter: Parameter) {
```

**Review by mversic — DISMISSED** [review]

**Review by 0x009922 — DISMISSED** [review]

**Review by nxsaken — DISMISSED** [review]

**Review by nxsaken — APPROVED** [review]

**Review by mversic — APPROVED** [review]
