### PR TITLE
[fix] #3396: Store block in kura before emitting block comitted event

### LINKED ISSUE #3396: [bug]: Tps benchmark fails block missing
I see two reasons why it can happen currently: 

1. In case of soft fork block committed event will be emitted twice with only advancing height once.
2. Block committed event is emitted before block is actually stored by kura, so there is possibility that client will ask for block not yet stored by kura.

### PR DESCRIPTION
**Pull request by Erigara**
### Linked issue

Closes #3396  

### Benefits

No situation when block is committed but not yet in kura.

### Checklist

- [x] I've read `CONTRIBUTING.md`
- [x] I've used the standard signed-off commit format (or will squash just before merging)
- [x] All applicable CI checks pass (or I promised to make them pass later)
- [ ] (optional) I've written unit tests for the code changes
- [ ] I replied to all comments after code review, marking all implemented changes with thumbs up

### CODE REVIEW

File: core/src/sumeragi/main_loop.rs [hunk 1]
```diff
@@ -318,16 +318,14 @@ impl Sumeragi {
...
         self.cache_transaction();
     }
 
     fn replace_top_block(&mut self, block: impl Into<VersionedCommittedBlock>) {
-        let committed_block = block.into();
+        let committed_block = Arc::new(block.into());
 
         self.wsv = self.finalized_wsv.clone();
-        self.update_state(&committed_block);
+        self.update_state(&Arc::clone(&committed_block), Kura::replace_top_block);
```
Comment (appetrosyan) [inline core/src/sumeragi/main_loop.rs:328]: Nice.

File: core/src/sumeragi/main_loop.rs [hunk 2]
```diff
@@ -367,22 +363,30 @@ impl Sumeragi {
         self.connect_peers(&self.current_topology);
     }
 
-    fn update_state(&mut self, committed_block: &VersionedCommittedBlock) {
+    fn update_state(
+        &mut self,
+        committed_block: &Arc<VersionedCommittedBlock>,
```
Comment (appetrosyan) [inline core/src/sumeragi/main_loop.rs:368]: We don't want to increment the refcount, but at the same time we don't want to generify with an `AsRef`, to not accept any other smart pointer?

**Review by appetrosyan — DISMISSED** [review]
LGTM. Minor comments only.

File: core/src/kura.rs [hunk 3]
```diff
@@ -319,17 +319,17 @@ impl Kura {
...
-            .lock()
-            .push((block.hash(), Some(Arc::new(block))));
+    pub fn store_block(&self, block: impl Into<Arc<VersionedCommittedBlock>>) {
+        let block = block.into();
+        self.block_data.lock().push((block.hash(), Some(block)));
     }
 
     /// Replace the block in `Kura`'s in memory block store.
-    pub fn replace_top_block(&self, block: VersionedCommittedBlock) {
+    pub fn replace_top_block(&self, block: impl Into<Arc<VersionedCommittedBlock>>) {
```
[the remark this answers is not in the document]
Comment (Erigara) [reply core/src/kura.rs:328]: I want to make changes in such a way that don't break previous code, and such signature work just fin in this case.

File: core/src/sumeragi/main_loop.rs (hunk 2 above)
Comment (Erigara) [reply core/src/sumeragi/main_loop.rs:368]: It's just clippy complaining that this value could be passed by reference instead of value.
I decide to obey instead of adding ignore because see no harm in such signature.

File: core/src/sumeragi/main_loop.rs [hunk 4]
```diff
@@ -367,22 +363,30 @@ impl Sumeragi {
...
             .expect("Failed to apply block on WSV. Bailing.");
 
         self.send_events(self.wsv.events_buffer.replace(Vec::new()));
 
         // Parameters are updated before updating public copy of sumeragi
         self.update_params();
 
+        // Block must be stored by kura after updating WSV because apply block might fail and we will store corrupted block
+        // but before updating public copy of wsv and emitting BlockCommitted event to avoid situation when block is not yet stored in kura
+        kura_store_block(&self.kura, Arc::clone(committed_block));
```
Comment (0x009922) [inline core/src/sumeragi/main_loop.rs:382]:
```suggestion
        // https://github.com/hyperledger/iroha/issues/3396:
        // Iroha should emit `BlockCommitted` event only after Kura stored the block.
        // However, WSV update should happen first, in order to avoid storaging a corrupted block
        kura_store_block(&self.kura, Arc::clone(committed_block));
```

**Review by SamHSmith — APPROVED** [review]

File: client/benches/tps/utils.rs [hunk 5]
```diff
@@ -294,7 +294,7 @@ impl MeasurerUnit {
         let transfer_rose = TransferBox::new(
             asset_id(self.name),
             1_u32.to_value(),
-            asset_id(self.next_name),
+            account_id(self.next_name),
```
Comment (ilchu) [inline client/benches/tps/utils.rs:297]: So the benchmark too was doing a somewhat off thing? I wonder if it would help if we could have the benchmarks integrated in our CI.

**Review by ilchu — APPROVED** [review]

File: client/benches/tps/utils.rs (hunk 5 above)
Comment (Erigara) [reply client/benches/tps/utils.rs:297]: Yes, basically API was changed, but benchmark is not.
I think it will help a lot to at least run tps oneshot in the CI. 
Because i fixed such errors on multiple occasions already.

File: core/src/sumeragi/main_loop.rs [hunk 6]
```diff
@@ -367,22 +363,31 @@ impl Sumeragi {
...
             .expect("Failed to apply block on WSV. Bailing.");
 
         self.send_events(self.wsv.events_buffer.replace(Vec::new()));
 
         // Parameters are updated before updating public copy of sumeragi
         self.update_params();
 
+        // https://github.com/hyperledger/iroha/issues/3396
+        // Iroha should emit `BlockCommitted` event only after Kura stored the block.
+        // However, WSV update should happen first, in order to avoid storing a corrupted block
```
[the remark this answers is not in the document]
Comment (Erigara) [reply core/src/sumeragi/main_loop.rs:382]: I like wording on this i will put this in the other PR.
