### PR TITLE
[fix] #3741: Fix tempfile error in `kagami validator`

### LINKED ISSUE #3741: [BUG] Kagami cannot access the cloned repo in the tmp dir
### OS and Environment

macOS 13.4 (22F66)

### GIT commit hash

2ebc38e0

### Minimum working example / Steps to reproduce

Run the following in the repo root:

1. `cargo build --release --bin kagami`
2. `./target/release/kagami validator`

### Actual result

Kagami fails with the following output:

```
Initialized empty Git repository in /private/var/folders/ft/3d510379563__2qpwn299g4r0000gn/T/.tmpfMMCcQ/iroha-cloned/.git/
remote: Enumerating objects: 734, done.
remote: Counting objects: 100% (734/734), done.
remote: Compressing objects: 100% (655/655), done.
remote: Total 734 (delta 83), reused 311 (delta 33), pack-reused 0
Receiving objects: 100% (734/734), 975.72 KiB | 294.00 KiB/s, done.
Resolving deltas: 100% (83/83), done.
From https://github.com/hyperledger/iroha
 * branch            2ebc38e051b90b8190b3795c7576094a9299982e -> FETCH_HEAD
HEAD is now at 2ebc38e [fix] #3445: make `POST configuration` work again
Error: 
   0: Failed to canonicalize path: /var/folders/ft/3d510379563__2qpwn299g4r0000gn/T/.tmpfMMCcQ/iroha-cloned/default_validator
   1: No such file or directory (os error 2)

Location:
   wasm_builder/src/lib.rs:113
```

As you can see, initially it clones the repo into `/var/folders/ft/3d510379563__2qpwn299g4r0000gn/T/.tmpfMMCcQ` temporary directory. It comes from here: 

https://github.com/hyperledger/iroha/blob/2ebc38e051b90b8190b3795c7576094a9299982e/tools/kagami/src/validator.rs#L25

Then, _for some reason_, this directory disappears before it is actually used by Kagami. 

### Expected result

Expected to build the validator successfully.

### Who can help to reproduce?

_No response_

### Notes

I think that the cause might be an incorrect usage of `tempfile` crate.

### PR DESCRIPTION
**Pull request by ilchu**
## Description

Getting rid of `tempdir` was a driveby fix I did in the CI PR that wasn't merged. Also fixing two other smaller bugs that didn't even have an issue assigned.

### Linked issue

Closes #3741. 

### Benefits
`kagami validator` and `kagami swarm` working as expected.

### Checklist

- [x] I've read `CONTRIBUTING.md`
- [x] I've used the standard signed-off commit format (or will squash just before merging)
- [ ] All applicable CI checks pass (or I promised to make them pass later)
- [ ] (optional) I've written unit tests for the code changes
- [ ] I replied to all comments after code review, marking all implemented changes with thumbs up

### CODE REVIEW

**Review by QuentinI — APPROVED** [review]

File: tools/kagami/src/validator.rs [hunk 1]
```diff
@@ -22,13 +22,11 @@ pub fn compute_validator_path() -> Result<PathBuf> {
     // command, otherwise it is called as a standalone
     std::env::var("CARGO_MANIFEST_DIR").map_or_else(
         |_| {
-            let source_dir = tempfile::tempdir()
-                .wrap_err("Failed to create temp dir for default runtime validator sources")?;
-            let out_dir = AbsolutePath::try_from(source_dir.path().join(DIR_CLONE))?;
+            let out_dir = AbsolutePath::try_from(PathBuf::from(".").join(DIR_CLONE))?;
             swarm::shallow_git_clone(GIT_ORIGIN, GIT_REVISION, &out_dir)?;
```
Comment (0x009922) [inline tools/kagami/src/validator.rs:26]: So, now the repo is cloned directly to the working dir. Why is it a more preferable default than using a temporary directory?

**Review by 0x009922 — COMMENTED** [review]
It works locally on my machine. However, I am confused by the fact that now `iroha-cloned` directory is produced in the working directory. I am not sure that this is a desirable behaviour. Anyway, if we proceed with this solution, it should be documented in the CLI help of the `validator` subcommand.

File: tools/kagami/src/validator.rs (hunk 1 above)
Comment (appetrosyan) [reply tools/kagami/src/validator.rs:26]: It seems to work. But I don't honestly think that it is preferable.

**Review by appetrosyan — APPROVED** [review]

**Review by 0x009922 — CHANGES_REQUESTED** [review]
It works, but when I ran `swarm`, it produced a `target` dir in my CWD:

```bash
kagami swarm -p 4 dir --build /path/to/iroha ./swarm
```

The `tree` after execution:

```
.
├── swarm
│   ├── config
│   │   ├── config.json
│   │   ├── genesis.json
│   │   └── validator.wasm
│   └── docker-compose.yml
└── target
    ├── release
    │   ├── build
    │   │   ├── compiler_builtins-6e378bf3cc48b617
    │   │   │   ├── build-script-build
    │   │   │   ├── build_script_build-6e378bf3cc48b617
    │   │   │   └── build_script_build-6e378bf3cc48b617.d
    │   │   ├── dlmalloc-cd1a25882d084ea9
    │   │   │   ├── build-script-build
    │   │   │   ├── build_script_build-cd1a25882d084ea9
    │   │   │   └── build_script_build-cd1a25882d084ea9.d
...
```

I guess the solution might be to use the source repo (provided with `--build` argument) as a CWD when the validator is being built. I could not really say why it happens, tbh.

**Comment by ilchu** [comment]
> It works, but when I ran `swarm`, it produced a `target` dir in my CWD:
> 
> ```shell
> kagami swarm -p 4 dir --build /path/to/iroha ./swarm
> ```
> 
> The `tree` after execution:
> 
> ```
> .
> ├── swarm
> │   ├── config
> │   │   ├── config.json
> │   │   ├── genesis.json
> │   │   └── validator.wasm
> │   └── docker-compose.yml
> └── target
>     ├── release
>     │   ├── build
>     │   │   ├── compiler_builtins-6e378bf3cc48b617
>     │   │   │   ├── build-script-build
>     │   │   │   ├── build_script_build-6e378bf3cc48b617
>     │   │   │   └── build_script_build-6e378bf3cc48b617.d
>     │   │   ├── dlmalloc-cd1a25882d084ea9
>     │   │   │   ├── build-script-build
>     │   │   │   ├── build_script_build-cd1a25882d084ea9
>     │   │   │   └── build_script_build-cd1a25882d084ea9.d
> ...
> ```
> 
> I guess the solution might be to use the source repo (provided with `--build` argument) as a CWD when the validator is being built. I could not really say why it happens, tbh.

Seems it was a `wasm_builder` quirk, fixed.

**Comment by Arjentix** [comment]
> Seems it was a wasm_builder quirk, fixed.

I wonder, how did you fix that?

File: tools/kagami/src/validator.rs [hunk 2]
```diff
@@ -6,46 +6,63 @@ use swarm::AbsolutePath;
...
+        };
+        let path = compute_validator_path(clone_dir.as_path())?;
         writer
             .write_all(&construct_validator(path)?)
             .wrap_err("Failed to write wasm validator into the buffer.")
     }
 }
-pub fn compute_validator_path() -> Result<PathBuf> {
+
+pub fn compute_validator_path(out_dir: impl AsRef<Path>) -> Result<PathBuf> {
```
Comment (Arjentix) [inline tools/kagami/src/validator.rs:35]: Please, add some doc comments to this function.

I see this code for the first time

File: tools/kagami/src/validator.rs [hunk 3]
```diff
@@ -6,46 +6,63 @@ use swarm::AbsolutePath;
...
             format!(
                 "Failed to construct absolute path for: {}",
-                swarm_dir.as_ref().display(),
+                build_dir.as_ref().display(),
             )
-        })
+        });
+    // Setting this so that [`Builder`](iroha_wasm_builder::Builder) doesn't pollute
+    // the swarm output dir with a `target` remnant
+    std::env::set_var("OUT_DIR", build_dir.as_ref());
```
Comment (Arjentix) [inline tools/kagami/src/validator.rs:64]: Hm... Can you use `out_dir()` of Builder instead? Or at least consider using `IROHA_WASM_BUILDER_OUT_DIR`

**Comment by ilchu** [comment]
> I wonder, how did you fix that?

This behaviour only occurred when the kagami was run directly (i.e. without cargo) and from a different dir than build dir, with the `wasm_builder` defaulting to an `out_dir` named `target` (AKA the usecase that we actually want to discourage, but still). So yeah, as you stated above, either calling `.out_dir()` or setting one of the env variables does the trick.

File: tools/kagami/src/validator.rs (hunk 3 above)
Comment (ilchu) [reply tools/kagami/src/validator.rs:64]: Is `OUT_DIR` a common env variable that could be used by other programs? I'd rather just set the latter variable then, because otherwise it would require a bit more refactoring than I'd like for an already marginal usecase.

**Comment by Arjentix** [comment]
**530** files have been changed?? You probably forgot to ignore them

**Comment by ilchu** [comment]
> **530** files have been changed?? You probably forgot to ignore them

Good thing it happened. Rather than ignoring, I forgot to set the out dir to `target`, and had it point to Iroha root instead. That's why it was happening 😢 Double checked again, release or not, now it's all fixed.

**Review by Arjentix — APPROVED** [review]

File: tools/kagami/src/validator.rs (hunk 3 above)
Comment (Arjentix) [reply tools/kagami/src/validator.rs]: > Is OUT_DIR a common env variable that could be used by other programs?

Yes, it's Rust-specific env var AFAIK. So I've made `Builder` to be able to use `IROHA_WASM_BUILDER_OUT_DIR` and `OUT_DIR` if the first one is not set.

File: tools/kagami/src/validator.rs [hunk 4]
```diff
@@ -6,46 +6,67 @@ use swarm::AbsolutePath;
...
+                build_dir.as_ref().display(),
             )
-        })
+        });
+    // Setting this so that [`Builder`](iroha_wasm_builder::Builder) doesn't pollute
+    // the swarm output dir with a `target` remnant
+    std::env::set_var(
+        "IROHA_WASM_BUILDER_OUT_DIR",
+        build_dir.as_ref().join("target"),
+    );
```
Comment (0x009922) [inline tools/kagami/src/validator.rs:68]: Seems like it produces a hard-to-track dependency between parts of the code. It might make future refactoring harder.

**Review by 0x009922 — APPROVED** [review]

**Review by appetrosyan — APPROVED** [review]

**Comment by timofeevmd** [comment]
after run a comand ./target/release/kagami validator
below you can see the output of the validator

[validator_output.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaXdoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--476180bf7e23c2ac8db232b31468f4bad2aa56f4/validator_output.txt)

**Comment by ilchu** [comment]
> after run a comand ./target/release/kagami validator below you can see the output of the validator
> 
> [validator_output.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaXdoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--476180bf7e23c2ac8db232b31468f4bad2aa56f4/validator_output.txt)

That's the intended behaviour. Basically the validator if no output redirection is specified just prints all the raw bytes to stdout, and that's what that mangled thing actually is.
