### PR TITLE
[fix] #4226: Prevent registering genesis Domain or Account

### LINKED ISSUE #4226: Prevent registering genesis Domain or Account
We have to make sure that instructions that try to register "genesis" domain or "genesis@genesis" account are always rejected. Tests should be added as well. Additionally, if there are none, tests should be added that confirm that any transaction signed by the "genesis@genesis" is rejected

### PR DESCRIPTION
**Pull request by dima74**
## Description

Disallow registering `genesis` domain or `genesis@genesis` account

### Linked issue

Closes #4226

### Checklist

- [x] I've read `CONTRIBUTING.md`
- [x] I've used the standard signed-off commit format (or will squash just before merging)
- [ ] All applicable CI checks pass (or I promised to make them pass later)
- [x] (optional) I've written unit tests for the code changes
- [ ] I replied to all comments after code review, marking all implemented changes with thumbs up

### CODE REVIEW

File: core/src/smartcontracts/isi/domain.rs [hunk 1]
```diff
@@ -55,6 +55,12 @@ pub mod isi {
                 .validate_len(state_transaction.config.ident_length_limits)
                 .map_err(Error::from)?;
 
+            if account_id == *iroha_genesis::GENESIS_ACCOUNT_ID {
```
Comment (Asem-Abdelhady) [inline core/src/smartcontracts/isi/domain.rs:58]: Is the best way to prevent the domain and the account by hardcoding a checking step in the isi?  
what is your opinion @Erigara

Comment (mversic) [reply core/src/smartcontracts/isi/domain.rs:58]: This is the 1st place in the core that this check can be placed at. We could put this check into executor, but I don't think this should be optional so this is the appropriate place for it

On the other hand, you might be on to something. We can place this check into a custom `Deserialize`/`Decode` for `Register<Account>`. But that would require us to hardcode `GENESIS_ACCOUNT_ID` in the `data_model`

so I'm thinking it's fine like this

**Review by mversic — APPROVED** [review]

**Review by Asem-Abdelhady — APPROVED** [review]

File: core/src/smartcontracts/isi/domain.rs (hunk 1 above)
Comment (Erigara) [reply core/src/smartcontracts/isi/domain.rs:58]: Yeah, i also think that this place is good
