### PR TITLE
[fix] #3762: Fix `irrefutable_let_patterns` in the `#[model]` macro

### LINKED ISSUE #3762: [refactor] Fix `irrefutable_let_patterns` lint generated in the `#[model]` macro.
Fix `irrefutable_let_patterns` lint generated in the `#[model]` macro.

_Originally posted by @appetrosyan in https://github.com/hyperledger/iroha/pull/3707#discussion_r1277799750_

### PR DESCRIPTION
**Pull request by ilchu**
## Description
Slightly amended `#[derive(FromVariant)]` macro to account for the degenerate case of a single variant enum, thus fixing the lint.

### Linked issue

Closes #3762. 

### Benefits
No annoying warnings

### Checklist

- [x] I've read `CONTRIBUTING.md`
- [x] I've used the standard signed-off commit format (or will squash just before merging)
- [ ] All applicable CI checks pass (or I promised to make them pass later)
- [ ] I replied to all comments after code review, marking all implemented changes with thumbs up

### CODE REVIEW

**Comment by DCNick3** [comment]
IMO it would be better for the macro to just suppress the lints, instead of increasing complexity of the macro code

The only reason that lint is there is to help humans write more concise code. The generated code doesn't really need to follow that

File: macro/derive/src/lib.rs [hunk 1]
```diff
@@ -268,6 +268,27 @@ fn from_variant(
...
+    enum_ty: &syn2::Ident,
+    variant: &syn2::Ident,
+    variant_ty: &syn2::Type,
+    generics: &syn2::Generics,
+) -> TokenStream {
+    let (impl_generics, ty_generics, where_clause) = generics.split_for_impl();
+
+    quote_spanned! { span =>
+        impl #impl_generics TryFrom<#enum_ty #ty_generics> for #variant_ty #where_clause {
+            type Error = iroha_macro::error::ErrorTryFromEnum<#enum_ty #ty_generics, Self>;
```
Comment (appetrosyan) [inline macro/derive/src/lib.rs:282]:
```suggestion
            type Error = ::iroha_macro::error::ErrorTryFromEnum<#enum_ty #ty_generics, Self>;
```

File: macro/derive/src/lib.rs [hunk 2]
```diff
@@ -268,6 +268,27 @@ fn from_variant(
...
+    span: Span,
+    enum_ty: &syn2::Ident,
+    variant: &syn2::Ident,
+    variant_ty: &syn2::Type,
+    generics: &syn2::Generics,
+) -> TokenStream {
+    let (impl_generics, ty_generics, where_clause) = generics.split_for_impl();
+
+    quote_spanned! { span =>
+        impl #impl_generics TryFrom<#enum_ty #ty_generics> for #variant_ty #where_clause {
```
Comment (appetrosyan) [inline macro/derive/src/lib.rs:281]:
```suggestion
        impl #impl_generics core::convert::TryFrom<#enum_ty #ty_generics> for #variant_ty #where_clause {
```

File: macro/derive/src/lib.rs [hunk 3]
```diff
@@ -297,42 +318,44 @@ fn impl_from_variant(ast: &FromVariantInput) -> TokenStream {
...
-            } else {
-                from_variant(span, name, &variant.ident, variant_type, generics, false)
-            };
-
-            Some(quote!(
-                #try_into
-                #from
-            ))
-        });
+        .expect("BUG: this should've been checked when parsing FromVariantInput");
```
Comment (appetrosyan) [inline macro/derive/src/lib.rs:325]: The GitHub diff got confused here.

File: macro/derive/src/lib.rs [hunk 4]
```diff
@@ -297,42 +318,44 @@ fn impl_from_variant(ast: &FromVariantInput) -> TokenStream {
...
+    let froms = enum_data.into_iter().filter_map(|variant| {
+        if !variant.fields.is_newtype() {
+            return None;
+        }
+        let span = variant.span();
+        let field = variant
+            .fields
+            .iter()
+            .next()
+            .expect("BUG: this should've been checked when parsing FromVariantInput");
```
Comment (appetrosyan) [inline macro/derive/src/lib.rs:336]: Not your code, but there's an opportunity for improvement. 

The panic message should act as a comment explaining what invariant must be enforced. Consider saying the **what**.

**Review by appetrosyan — DISMISSED** [review]

**Comment by appetrosyan** [comment]
> The only reason that lint is there is to help humans write more concise code. The generated code doesn't really need to follow that

I respectfully disagree. While it is *unlikely* that most users will see the generated code, if you are in a position of needing to `cargo expand` this macro, readability counts a lot more than in ordinary code. 

And while most macros are encouraged to use fully-qualified names this is a sacrifice (that can often be compensated by looking at the `use` statements at the top of the file and shortening the paths that resolve to the correct one). 

Macro code absolutely needs to be readable and conform to the same quality standards as the rest of the program.

**Comment by ilchu** [comment]
> IMO it would be better for the macro to just suppress the lints, instead of increasing complexity of the macro code
> 
> The only reason that lint is there is to help humans write more concise code. The generated code doesn't really need to follow that

I tend to agree with @appetrosyan here. I feel that this level of duplication doesn't introduce too much complexity as long as it's readable enough and self-descriptive. And there's already been specialized function variants in that module, e.g. `from_variant_internal` and `from_container_variant_internal`. Though I do agree the improvement overall is pretty marginal.

**Review by pesterev — APPROVED** [review]

File: macro/derive/src/lib.rs [hunk 5]
```diff
@@ -297,42 +318,43 @@ fn impl_from_variant(ast: &FromVariantInput) -> TokenStream {
...
+        } else {
+            try_into_variant(span, name, &variant.ident, variant_type, generics)
+        };
+        let from = if field.skip_from {
+            quote!()
+        } else if field.skip_container {
+            from_variant(span, name, &variant.ident, variant_type, generics, true)
+        } else {
+            from_variant(span, name, &variant.ident, variant_type, generics, false)
+        };
```
Comment (0x009922) [inline macro/derive/src/lib.rs:351]:
```suggestion
        } else {
            from_variant(span, name, &variant.ident, variant_type, generics, field.skip_container)
        };
```

**Review by 0x009922 — APPROVED** [review]
