### PR TITLE
[fix] #4099: Fix of the websocket request builder

### LINKED ISSUE #4099: [BUG]  Websocket and Basic Auth Proxy on s1.tst.iroha2.iroha.tech
### OS and Environment

- MacOS, Docker (Windows as well)
- Proxy Server: Basic Auth Enabled
- TORII_API_URL: http://s1.tst.iroha2.iroha.tech/
- Client: iroha_client_cli
- Network: Proxy enabled environment

### GIT commit hash

794fe35

### Minimum working example / Steps to reproduce

1. Configure the iroha_client_cli to use the TORII_API_URL http://s1.tst.iroha2.iroha.tech/ (with Basic Auth enabled on the proxy server)
2. Execute the command: ./iroha_client_cli events pipeline

### Actual result
Error: 
   0: Failed to listen for events.
   1: HTTP error: 400 Bad Request
telegram-cloud-photo-size-2-5422658007092809261-y

### Expected result
Successfully events listening

### Who can help to reproduce?

@AlexStroke @Stukalov-A-M

### PR DESCRIPTION
**Pull request by Stukalov-A-M**
## Description

Fixed the web socket bug which gives HTTP 400.
All library versions saved as-is

### Linked issue

- Closes #4099: 

### Checklist

- [x] I've read `CONTRIBUTING.md`
- [x] I've used the standard signed-off commit format (or will squash just before merging)
- [x] All applicable CI checks pass (or I promised to make them pass later)
- [x] (optional) I've written unit tests for the code changes
- [x] I replied to all comments after code review, marking all implemented changes with thumbs up

### CODE REVIEW

File: client/src/http_default.rs [hunk 1]
```diff
@@ -117,21 +119,21 @@ impl DefaultWebSocketRequestBuilder {
...
+            .into_client_request()?;
+        if let Some(auth_header) = builder
+            .headers_ref()
+            .ok_or(eyre!("No headers found"))?
+            .get("Authorization")
+        {
+            request
+                .headers_mut()
+                .insert("Authorization", auth_header.clone());
+        }
```
Comment (Arjentix) [inline client/src/http_default.rs:135]:
```suggestion
        for (header, value) in builder.headers().ok_or(eyre!("No headers found"))? {
            request
                .headers()
                .entry(header)
                .or_insert(value);
        }
```

I think this will be more robust. Currently you check only for one header `Authorization` but user (I mean this function user) may specify any other header as well

**Review by Arjentix — CHANGES_REQUESTED** [review]
Same for PR to stable branch

**Review by mversic — APPROVED** [review]

**Review by Arjentix — APPROVED** [review]
