### PR TITLE
fix: Introduce p2p idle timeout

### LINKED ISSUE #4267: [BUG] incorrect metric connected_peers with istio service mesh
### OS and Environment

Linux, K8s

### GIT commit hash

eca8569b

### Minimum working example / Steps to reproduce

1. Raise five peers in Kubernetes
2. Istio must be turned off
3. Metric `connected_peers` = 4 on all peers
3. Turn on istio, restart the pods. Metric `connected_peers` = 4
4. Restart the pods again.
5. Check the metric for peer0, peer1, peer4 `connected_peers` = 4,
6. Check the `connected_peers` metric for peer2 and peer3. It should be equal to `connected_peers` = 3.

Peculiarities
1. There are no errors in the logs related to the connection between peers
2. Go to peer 3 (where connected_peers = 3), make a transaction - it should receive commit status.
3. We go to another peer, for example peer1, where connected_peers = 4 - the transaction should be displayed in this peer

### Actual result

The metric for peer0, peer1, peer4 connected_peers = 4,
The `connected_peers` metric for peer2 and peer3. It should be equal to connected_peers = 3.

### Expected result

The metric `connected_peers` should be equal 4 in all peers

### Logs in JSON format

<details>
  <summary>Log contents</summary>
  
  ```json
see attachments
  ```
</details>

### Who can help to reproduce?

@BAStos525

### Notes

_No response_

### PR DESCRIPTION
**Pull request by Erigara**
## Description

Backport of #4398.

### Linked issue

Closes #4267 

### Benefits

No problem with connectivity on rc20.

### CODE REVIEW

File: p2p/src/network.rs [hunk 1]
```diff
@@ -26,6 +26,9 @@ use crate::{
     unbounded_with_len, Broadcast, Error, NetworkMessage, OnlinePeers, Post, UpdateTopology,
 };
 
+/// Timeout after which disconnect from idle side
+const IDLE_TIMEOUT: Duration = Duration::from_secs(60);
```
Comment (Erigara) [inline p2p/src/network.rs:30]: Not configurable, to reduce amount of changes.

**Review by mversic — APPROVED** [review]

**Review by DCNick3 — APPROVED** [review]
