### PR TITLE
[fix] #3129: Fix `Parameter` de/serialization

### LINKED ISSUE #3129: [bug]: Fix `Parameter` deserialization

### PR DESCRIPTION
**Pull request by Erigara**
Signed-off-by: Shanin Roman <shanin1000@yandex.ru>

### Description of the Change

- Add test to check de/serialization consistency of `Parameter`.
- Fix `Parameter` de/serialization.
- Add `CanChangeConfigParameters` into default permission tokens.

### Issue

Closes #3129.

### Benefits

No bug.

### Possible Drawbacks

None.

### Usage Examples or Tests

```
cargo test --package iroha_data_model --lib -- tests::test_parameter_serialize_deserialize_consistent --exact --nocapture
```

### CODE REVIEW

File: permissions_validators/src/public_blockchain/mod.rs [hunk 1]
```diff
@@ -44,6 +44,8 @@ pub enum PredefinedPermissionToken {
     TransferOnlyFixedNumberOfTimesPerPeriod(transfer::CanTransferOnlyFixedNumberOfTimesPerPeriod),
     /// Can un-register asset with the corresponding asset definition.
     UnregisterAssetWithDefinition(unregister::CanUnregisterAssetWithDefinition),
+    /// Can change configuration parameters.
+    CanChangeConfigParameters(set_parameter::CanChangeConfigParameters),
```
Comment (Erigara) [inline permissions_validators/src/public_blockchain/mod.rs:48]: We are currently ignoring `NewParameter` instruction inside `ChangeParametersOnlyForSignerAccount` and `GrantedChangeConfigParameters` validators. 
But since parameters currently doesn't affect anything + we are moving towards runtime validators, this is not something we want to fix right now imo.
I will create ticket to keep track of this issue.

**Review by Arjentix — APPROVED** [review]

**Review by ilchu — APPROVED** [review]
