### PR TITLE
fix!: Upgrade executor in separate transaction in genesis block

### LINKED ISSUE #4743: Validate genesis instructions
> A thing that I have noticed. We don't validate genesis instructions at all anymore because there is no initial executor. This is a bug, only the 1st instruction (which is upgrade) should not be validated, all others should

_Originally posted by @mversic in https://github.com/hyperledger/iroha/issues/4739#issuecomment-2178400860_

### PR DESCRIPTION
**Pull request by dima74**
## Description

`GenesisBlock` now have two transactions, first with single `Upgrade` instruction to set executor, and second with all other instructions. If there are no other instructions, second transaction will be omitted.

### Linked issue

Closes #4743

### Checklist

- [x] I've read `CONTRIBUTING.md`
- [x] I've used the standard signed-off commit format (or will squash just before merging)
- [ ] All applicable CI checks pass (or I promised to make them pass later)
- [ ] (optional) I've written unit tests for the code changes
- [ ] I replied to all comments after code review, marking all implemented changes with thumbs up

### CODE REVIEW

File: core/src/block.rs [hunk 1]
```diff
@@ -695,23 +694,34 @@ mod valid {
...
+        for transaction in transactions {
+            if transaction.value.authority() != genesis_account {
+                return Err(InvalidGenesisError::UnexpectedAuthority);
+            }
+            if transaction.error.is_some() {
+                return Err(InvalidGenesisError::ContainsErrors);
+            }
+            let Executable::Instructions(_) = transaction.value.instructions() else {
+                return Err(InvalidGenesisError::InvalidInstructions);
+            };
```
Comment (mversic) [inline core/src/block.rs:706]: I think you could have put many of these checks into `SignedBlock::deserialize` and reject eagerly

**Review by mversic — APPROVED** [review]

File: data_model/src/block.rs [hunk 2]
```diff
@@ -280,16 +280,18 @@ impl SignedBlock {
 
     /// Creates genesis block signed with genesis private key (and not signed by any peer)
     pub fn genesis(
-        genesis_transaction: SignedTransaction,
+        genesis_transactions: Vec<SignedTransaction>,
```
Comment (0x009922) [inline data_model/src/block.rs:283]: [Parse, don’t validate](https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/)

Maybe it would be good to define a stricter type for `GenesisTransactions`, which will verify on construction/deserialization that the first TX has only one `Upgrade` ISI?

```rs
// (De-)serializes as `Vec<SignedTransaction>` with validation
struct GenesisTransactions {
  upgrade: SignedTransaction,
  rest: Vec<SignedTransaction>
}

impl GenesisTransactions {
  fn new(upgrade: SignedTransaction, rest: Vec<SignedTransaction>) -> Result<Self, SomeError> {
    // validate that `upgrade` is appropriate
  }

  fn get_upgrade(&self) -> Upgrade {
    // can `unwrap` `self.upgrade` safely thanks to validation on creation
  }
}
```

**Review by 0x009922 — APPROVED** [review]
Anyway, clean work.

File: data_model/src/block.rs [hunk 3]
```diff
@@ -339,13 +345,50 @@ mod candidate {
...
         }
 
+        fn validate_genesis(&self) -> Result<(), &'static str> {
+            let transactions = self.payload.transactions.as_slice();
+            for transaction in transactions {
+                if transaction.error.is_some() {
+                    return Err("Genesis transaction must not contain errors");
+                }
+                let Executable::Instructions(_) = transaction.value.instructions() else {
+                    return Err("Genesis transaction must contain instructions");
```
[the remark this answers is not in the document]
Comment (mversic) [reply data_model/src/block.rs:365]: It's fine atm. We don't even have a way to represent it in json

File: data_model/src/block.rs (hunk 2 above)
Comment (mversic) [reply data_model/src/block.rs:283]: Let's make it a separate issue and merge as is
