### PR TITLE
[fix] #2787: Notify every listener to shutdown on panic

### LINKED ISSUE #2787: [bug]: Iroha panic handler not working correctly
Currently `iroha` on panic notify only single listener about shutdown.

### PR DESCRIPTION
**Pull request by Erigara**
Signed-off-by: Shanin Roman <shanin1000@yandex.ru>

### Description of the Change

Replaced `.notify_one()` with `.notify_waiters()` in order to notify every waiter about shutdown.

### Issue

Closes #2787.

### Benefits

Iroha actually shutdown. 

### Possible Drawbacks

There is still possibility of deadlock if `.notified().await` would be called after `.notify_waiters()` was called, but this seems to be very unlikely case , because either start warp (in this case waiters would be ready) or warp not started yet (int this case nothing will prevent iroha from shutdown).

### Usage Examples or Tests *[optional]*

```
cargo test --package iroha --lib -- tests::iroha_should_notify_on_panic --exact --nocapture
```

### Alternate Designs *[optional]*

- Replace `Notify` channel with different sync primitive.
- Every `waiter` must call `.notify_one()` after receiving notification: more verbose, but solve case of possible deadlock.

### CODE REVIEW

File: cli/src/lib.rs [hunk 1]
```diff
@@ -390,6 +391,7 @@ where
                 _ = sigterm.recv() => {},
             }
 
+            // NOTE: shutdown all currently listening waiters
```
Comment (appetrosyan) [inline cli/src/lib.rs:394]: Do we **really** need this comment?

**Review by appetrosyan — APPROVED** [review]

File: cli/src/lib.rs (hunk 1 above)
Comment (Erigara) [reply cli/src/lib.rs:394]: no, i can remove it if you want

Comment (appetrosyan) [reply cli/src/lib.rs:394]: Please remove.

**Review by ilchu — APPROVED** [review]
