### PR TITLE
[fix] #4256: Introduce predictable ordering after too many failed view changes

### LINKED ISSUE #4256: consensus `TopologyMismatch` bug
[ymls.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTh2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--21f6ee2895b357a10c54435832343ef0830a1c40/ymls.zip)
[logs.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkF2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--816e30d42f9298bd0382aeba972d52c0c92f586d/logs.zip)
[nodes conf.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkV2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e566a0dfaaaf407746e7d800ee2dd4a487b200eb/nodes%20conf.zip)

blockstore files are too big. Ask @mversic to provide them offline

### PR DESCRIPTION
**Pull request by mversic**
### Linked issue

Closes #4256
Created #4265

### Checklist

- [ ] I've read `CONTRIBUTING.md`
- [ ] I've used the standard signed-off commit format (or will squash just before merging)
- [ ] All applicable CI checks pass (or I promised to make them pass later)
- [ ] (optional) I've written unit tests for the code changes
- [ ] I replied to all comments after code review, marking all implemented changes with thumbs up

### CODE REVIEW

**Review by SamHSmith — APPROVED** [review]
I think the limit should probably be 15 instead of 5. And we should definitely remove this long term. It's an okay solution for now since it's not directly exploitable by attackers.

File: core/src/sumeragi/main_loop.rs [hunk 1]
```diff
@@ -650,8 +651,14 @@ impl Sumeragi {
                         .chain(current_view_change_index, &mut new_wsv)
                         .sign(&self.key_pair);
 
+                        let created_in = create_block_start_time.elapsed();
                         if let Some(current_topology) = current_topology.is_consensus_required() {
-                            info!(%addr, block_payload_hash=%new_block.payload().hash(), "Block created");
+                            info!(%addr, created_in_ms=%created_in.as_millis(), block_payload_hash=%new_block.payload().hash(), "Block created");
+
+                            if created_in > self.pipeline_time() / 2 {
```
Comment (mversic) [inline core/src/sumeragi/main_loop.rs:658]: what would be appropriate here?

Comment (SamHSmith) [reply core/src/sumeragi/main_loop.rs:658]: Half I think is good. Full block will get committed as fast as possible anyways.

**Review by SamHSmith — DISMISSED** [review]

**Review by 6r1d — DISMISSED** [review]
