### PR TITLE
[fix] #3031: Fix the UI/UX of missing configuration parameters

### LINKED ISSUE #3031: Enhance `ConfigurationProxy` failure reporting
> With that said, we should print *all* of the missing fields, not just the first. Given that these errors are generated in a macro, I think there can be some reusable logic

I.e. refactor the config proxy build and/or generation routine so that it lists all the fields which did not have acceptable values that would allow it to build.

Second, make the build message more informative instead of just `Proxy failed at build stage`.

Finally, `eprintln!` the received proxy to make debugging less painful.

### PR DESCRIPTION
**Pull request by appetrosyan**
### Description of the Change

Improve UI/UX of incorrect configuration specification. 

### Issue

Closes #3031 

### Benefits

Better UI

### Possible Drawbacks

Slightly worse readability of the `iroha_cli` crate, particularly the `main.rs` file.

### CODE REVIEW

File: config/src/lib.rs [hunk 1]
```diff
@@ -1,5 +1,5 @@
 //! Aggregate configuration for different Iroha modules.
-
+#![feature(absolute_path)]
```
Comment (mversic) [inline config/src/lib.rs:2]: do we have to use unstable feature? It's only for `Display` implementation

File: config/src/iroha.rs [hunk 2]
```diff
@@ -88,48 +87,56 @@ impl ConfigurationProxy {
...
+                    });
                 }
             } else {
-                eyre::bail!(ConfigError::ProxyBuildError(
-                    "Torii config should have at least `p2p_addr` provided for sumeragi finalisation"
-                        .to_owned()
-                ))
+                return Err(ConfigError::MissingField{
+                    field: "p2p_addr",
+					message: "Torii config should have at least `p2p_addr` provided for sumeragi finalisation",
```
Comment (mversic) [inline config/src/iroha.rs:138]: you have tabs in a few places

File: cli/src/main.rs [hunk 3]
```diff
@@ -52,10 +70,19 @@ async fn main() -> Result<(), color_eyre::Report> {
...
             print_help(&styling)?;
+			// NOTE: because of how `color_eyre` works, we need to
+			// install the hook before creating any instance of
+			// `eyre::Report`, otherwise the `eyre` default reporting
+			// hook is going to be installed automatically.
+
+			// This results in a nasty repetition of the
+			// `color_eyre::install().unwrap()` pattern, which is the
+			// lesser of two evils
+			color_eyre::install().expect("CRITICAL");
```
Comment (mversic) [inline cli/src/main.rs:85]: I assume this is related to #2212

Comment (mversic) [reply cli/src/main.rs:85]: Also, I see this hook install around the codebase in different crates. If it's expected to fail, you think we could make it into a function?

File: cli/src/main.rs [hunk 4]
```diff
@@ -84,7 +116,42 @@ async fn main() -> Result<(), color_eyre::Report> {
         }
     }
 
-    <iroha::Iroha>::new(&args).await?.start().await?;
+    // <iroha::Iroha>::new(&args).await?.start().await?;
```
Comment (mversic) [inline cli/src/main.rs:119]: seems accidental?

**Review by mversic — CHANGES_REQUESTED** [review]

File: cli/src/main.rs (hunk 3 above)
Comment (appetrosyan) [reply cli/src/main.rs:85]: It's not expected to fail, the point of this particular implementation is that we know for sure that we haven't installed the hook. And we have no reason to expect that the user would want to disable it (vic config params, because they're unreadable). Afterwards, it's a different story.

File: config/src/lib.rs (hunk 1 above)
Comment (appetrosyan) [reply config/src/lib.rs:2]: In this case, there's a good reason: `std::fs::absolute` is `unstable`, but it does exactly what we need. 

Given that we're using a `nightly` only toolchain, and this function will very likely be added without changes, I took the liberty of adding this feature. If we do move back to `stable` we might want to reconsider it, but for now it does what we need.

File: config/src/iroha.rs (hunk 2 above)
Comment (appetrosyan) [reply config/src/iroha.rs:138]: I'm guessing `rustfmt` isn't replacing them with spaces.

File: config/base/src/lib.rs [hunk 5]
```diff
@@ -300,54 +299,82 @@ pub mod derive {
...
+        },
 
-        /// To be used for [`Self::UnknownField`] variant construction.
-        #[inline]
-        pub fn concat_error_string(field: &[String]) -> String {
-            field.join(".")
-        }
+        // /// Used in [`Builder`] trait for build errors
+        // #[error("Proxy failed at build stage due to: {0}")]
+        // ProxyBuildError(String),
```
Comment (ilchu) [inline config/base/src/lib.rs:368]: Commented code. Also good to know this source of confusion is finally gone.

File: config/base/src/lib.rs [hunk 6]
```diff
@@ -300,54 +299,82 @@ pub mod derive {
...
+        #[error("The value {} of {} is wrong. \nPlease change the value.", .value, .field)]
+        #[serde(skip)]
+        InsaneValue {
+            /// The value of the field that's incorrect
+            value: String,
+            /// Field name that contains invalid value
+            field: &'static str,
+            /// Additional message to be added as `color_eyre::suggestion`
+            message: String,
+            // docstring: &'static str,  // TODO: Inline the docstring for easy access
```
Comment (ilchu) [inline config/base/src/lib.rs:363]: Or maybe generating a link such as `iroha/docs/source/references/config.md#queuetransaction_time_to_live_ms` would be easier?

File: config/src/iroha.rs [hunk 7]
```diff
@@ -88,48 +87,56 @@ impl ConfigurationProxy {
...
+    pub fn finish(&mut self) -> Result<(), ConfigError> {
         if let Some(sumeragi_proxy) = &mut self.sumeragi {
             // First, iroha public/private key and sumeragi keypair are interchangeable, but
             // the user is allowed to provide only the former, and keypair is generated automatically,
             // bailing out if key_pair provided in sumeragi no matter its value
             if sumeragi_proxy.key_pair.is_some() {
-                eyre::bail!(ConfigError::ProxyBuildError(
-                    "Sumeragi should not be provided with `key_pair` directly as it is instantiated via Iroha config. Please set the `KEY_PAIR` to `null` or omit them entirely."
-                        .to_owned()))
+                return Err(ConfigError::ProvidedInferredField{
```
Comment (ilchu) [inline config/src/iroha.rs:96]:
```suggestion
                return Err(ConfigError::ProvidedInferredField {
```

File: config/base/src/lib.rs [hunk 8]
```diff
@@ -356,24 +383,27 @@ pub mod runtime_upgrades;
...
 
     /// Marker traits for types for which views are implemented
     pub trait HasView {}
 
     /// Wrapper structure used to check if type implements `[HasView]`
-    /// If `T` doesn't implement [`HasView`] then `NoView::IS_HAS_VIEW` (`false`) will be used
-    /// Otherwise `IsHasView::IS_HAS_VIEW` (`true`) from `impl` block will shadow `NoView::IS_HAS_VIEW`
-    pub struct IsHasView<T>(core::marker::PhantomData<T>);
+    /// If `T` doesn't implement [`HasView`] then
+    /// [`NoView::IS_INSTANCE_HAS_VIEW`] (`false`) will be used Otherwise
```
Comment (ilchu) [inline config/base/src/lib.rs:399]:
```suggestion
    /// [`NoView::IS_INSTANCE_HAS_VIEW`] (`false`) will be used, otherwise
```

File: cli/src/lib.rs [hunk 9]
```diff
@@ -154,93 +157,25 @@ impl Handler<iroha_core::NetworkMessage> for FromNetworkBaseRelay {
...
         //
         // A downside of this approach is that this panic hook will not work for
         // threads created by Iroha itself (e.g. Sumeragi thread).
         //
-        // # TODO
-        //
-        // Remove this when all Rust integrations tests will be converted to a
-        // separate Python tests.
+        // # TODO: Remove this when all Rust integrations tests will
+        // be converted to a separate Python tests.
```
Comment (ilchu) [inline cli/src/lib.rs:178]:
```suggestion
        // be converted to separate Python tests.
```

File: logger/src/lib.rs [hunk 10]
```diff
@@ -283,6 +283,7 @@ pub fn install_panic_hook() -> Result<(), Report> {
         .compare_exchange(false, true, Ordering::SeqCst, Ordering::SeqCst)
         .is_ok()
     {
+        println!("Installing eyre hook");
```
Comment (ilchu) [inline logger/src/lib.rs:286]: Why not use `self::prelude::trace!` here? And also maybe a bit more specific:
```suggestion
        println!("Installing eyre hook for test network");
```

File: cli/src/lib.rs [hunk 11]
```diff
@@ -497,6 +432,71 @@ impl Iroha {
...
+                    // escape codes from logs redirected from STDOUT. If you
+                    // need syntax highlighting, use JSON logging instead.
+                    config.logger.terminal_colors = false;
+                }
+                config
+            }
+            Err(e) => {
+                use iroha_config::base::derive::Error::*;
+
+                color_eyre::install()?;
```
Comment (ilchu) [inline cli/src/lib.rs:475]: Do we really need to call it here as long as the hook is already installed in `cli/src/main.rs` and that's its only call site?

File: cli/src/main.rs [hunk 12]
```diff
@@ -56,6 +74,16 @@ async fn main() -> Result<(), color_eyre::Report> {
...
+            // WORKAROUND for #2212: because of how `color_eyre`
+            // works, we need to install the hook before creating any
+            // instance of `eyre::Report`, otherwise the `eyre`
+            // default reporting hook is going to be installed
+            // automatically.
+
+            // This results in a nasty repetition of the
+            // `color_eyre::install().unwrap()` pattern, which is the
+            // lesser of two evils
+            color_eyre::install().expect("CRITICAL");
```
Comment (ilchu) [inline cli/src/main.rs:86]: This is a bit confusing to me as we call the hook inside this function and a few times in `.map_err(..)` invocations. Is it really needed or would moving the call to the top of `main()` help?

File: config/src/lib.rs (hunk 1 above)
Comment (appetrosyan) [reply config/src/lib.rs]: > Tracking issue https://github.com/rust-lang/rust/issues/92750#issuecomment-1476829107 mentions that we can use Path::canonicalize() instead.

No because a lot of the time, we don't care if the file exists.

File: config/src/path.rs [hunk 13]
```diff
@@ -15,13 +15,13 @@ pub const ALLOWED_CONFIG_EXTENSIONS: [&str; 2] = ["json", "json5"];
 pub enum ExtensionError {
     /// User provided config file without extension.
     #[error(
-        "Provided config file has no extension, allowed extensions are: {:?}.",
+        "No valid file extension found. Allowed file extensions are: {:?}.",
```
[the remark this answers is not in the document]
Comment (appetrosyan) [reply config/src/path.rs:20]: Also used with genesis. So config is confusing.

File: config/base/src/lib.rs (hunk 6 above)
Comment (appetrosyan) [reply config/base/src/lib.rs:363]: Created #3326

File: config/src/lib.rs (hunk 1 above)
Comment (mversic) [reply config/src/lib.rs]: I'm up for any solution which doesn't rely on introducing an unstable feature. Otherwise, we should take this up for a vote with the team as we discussed on the retro

Comment (appetrosyan) [reply config/src/lib.rs]: Let's keep it to `stable` then.

File: logger/src/lib.rs (hunk 10 above)
Comment (appetrosyan) [reply logger/src/lib.rs:286]: Actually I meant to remove it.

File: cli/src/lib.rs (hunk 11 above)
Comment (appetrosyan) [reply cli/src/lib.rs:475]: We do. Courtesy of `eyre` installing a default hook when a `Report` is constructed, the hook installation being irreversible and us having the brilliant foresight of introducing a config parameter for colors, rather than using XDG standards, we actually have to initialise the correct hook **each** time we return an error.

File: config/src/iroha.rs (hunk 7 above)
Comment (appetrosyan) [reply config/src/iroha.rs:96]: Wonder why `rustfmt` doesn't fix this.

File: cli/src/main.rs [hunk 14]
```diff
@@ -27,6 +29,17 @@ const REQUIRED_ENV_VARS: [(&str, &str); 7] = [
...
+/// To make `Iroha` peer work all actors should be started first.
+/// After that moment it you can start it with listening to torii events.
+///
+/// # Side effect
+/// - Prints welcome message in the log
+///
+/// # Errors
+/// - Reading genesis from disk
+/// - Reading telemetry configs
+/// - telemetry setup
```
Comment (0x009922) [inline cli/src/main.rs:41]:
```suggestion
/// - Telemetry setup
```

File: config/base/src/lib.rs [hunk 15]
```diff
@@ -356,24 +380,27 @@ pub mod runtime_upgrades;
 pub mod view {
     //! Module for view related traits and structs
 
-    /// Marker trait to set default value `IS_HAS_VIEW` to `false`
+    /// Marker trait to set default value [`IsInstanceHasView::IS_INSTANCE_HAS_VIEW`] to `false`
     pub trait NoView {
         /// [`Self`] doesn't implement [`HasView`]
         const IS_HAS_VIEW: bool = false;
```
Comment (0x009922) [inline config/base/src/lib.rs:386]: Maybe it would be more idiomatic to use "strong type" instead of a `bool`:

```rust
enum ViewExistence {
  Exists,
  Absent
}
```

File: config/src/client.rs [hunk 16]
```diff
@@ -124,20 +124,30 @@ impl ConfigurationProxy {
         if let Some(tx_ttl) = self.transaction_time_to_live_ms {
             // Really small TTL would be detrimental to performance
             if tx_ttl < TTL_TOO_SMALL_THRESHOLD {
-                eyre::bail!(
-                    ConfigError::ProxyBuildError("`TRANSACTION_TIME_TO_LIVE_MS`, network throughput may be compromised for values less than {TTL_TOO_SMALL_THRESHOLD}".to_owned())
-                );
+                eyre::bail!(ConfigError::InsaneValue {
+                    field: "TRANSACTION_TIME_TO_LIVE_MS",
```
Comment (0x009922) [inline config/src/client.rs:128]: I believe that hard-coding SCREAMING field name should be replaced with _at least_ a `const`:

```rust
struct ConfigFieldsScreaming;

impl ConfigFieldsScreaming {
  pub const TxTimeToLiveMs: &'static str = "TRANSACTION_TIME_TO_LIVE_MS";
}

ConfigError::InsaneValue { field: ConfigFieldsScreaming::TxTimeToLiveMs }
```

File: config/base/src/lib.rs (hunk 15 above)
Comment (appetrosyan) [reply config/base/src/lib.rs:386]: The biggest benefit of this approach is that you need to use a `match` or an `if let` instead of `if`. Users of the library don't expect a yes/no question to be answered with an enum, unless there's a good reason. using 
```rust 
enum HasView {
  Has(View),
  Not
}
```
would be better, but I don't see how to do it yet.

File: config/src/client.rs (hunk 16 above)
Comment (appetrosyan) [reply config/src/client.rs:128]: In theory, yes. In practice, 1. Rustc would complain that your constant isn't upper-snake-case (screaming), and 2. The Rust-y name for the constant is going to be precisely the same as its string representation. 

Best practices from other languages would suggest that naming a constant is a good idea, citing refactoring ability. These don't apply here for the following reasons: 
1. The symbol name is straightforward to find/replace, and it would also affect docs (which is good). 
2. And if you did change the string, you probably also need to change the variable name, because it is misleading. 
3. We don't want the config parameters to change names often if at all. Most headaches that @BAStos525 @ilchu and @Mingela are facing are because we change this too frequently.

File: data_model/src/asset.rs [hunk 17]
```diff
@@ -387,6 +388,12 @@ impl fmt::Display for AssetId {
     }
 }
 
+impl fmt::Debug for AssetId {
```
Comment (appetrosyan) [inline data_model/src/asset.rs:391]: I know this is kind-of inconsistent, but I didn't really want to abuse proc-macros too much.

File: data_model/src/isi.rs [hunk 18]
```diff
@@ -18,41 +18,57 @@ use crate::{model, Registered};
 
 model! {
     /// Sized structure for all possible Instructions.
-    #[derive(Debug, Display, Clone, PartialEq, Eq, Hash, FromVariant, EnumDiscriminants, Decode, Encode, Deserialize, Serialize, IntoSchema)]
+    #[derive(DebugCustom, Display, Clone, PartialEq, Eq, Hash, FromVariant, EnumDiscriminants, Decode, Encode, Deserialize, Serialize, IntoSchema)]
     #[strum_discriminants(name(InstructionType), derive(Display), cfg_attr(any(feature = "ffi_import", feature = "ffi_export"), derive(iroha_ffi::FfiType)), allow(missing_docs), repr(u8))]
     #[ffi_type(opaque)]
     pub enum InstructionBox {
         /// `Register` variant.
+        #[debug(fmt = "{_0:?}")]
```
Comment (appetrosyan) [inline data_model/src/isi.rs:26]: Unfortunately, putting this once at the header didn't work.

File: crypto/src/lib.rs [hunk 19]
```diff
@@ -177,6 +177,46 @@ ffi::ffi_item! {
...
+        match source {
+            ursa::CryptoError::NoSuchAlgorithm(_) => Self::NoSuchAlgorithm,
+            ursa::CryptoError::ParseError(source) => Self::Parse(source),
+            ursa::CryptoError::SigningError(source) => Self::Signing(source),
+            ursa::CryptoError::KeyGenError(source) => Self::KeyGen(source),
+            ursa::CryptoError::DigestGenError(source) => Self::DigestGen(source),
+            ursa::CryptoError::GeneralError(source) => Self::Other(source),
+        }
+    }
+}
```
Comment (mversic) [inline crypto/src/lib.rs:218]: Usually I wouldn't mind reordering but this is going to create unnecessary conflict with #3076 PR

File: config/base/derive/src/documented.rs [hunk 20]
```diff
@@ -193,7 +193,13 @@ fn impl_get_recursive(ast: &StructWithFields) -> proc_macro2::TokenStream {
...
                 [stringify!(#ident)] => {
                     serde_json::to_value(&#l_value)
-                        .map_err(|e| ::iroha_config_base::derive::Error::field_error(stringify!(#ident), e))?
+                        .map_err(
+							|error|
+							::iroha_config_base::derive::Error::FieldDeserialization {
+								field: stringify!(#ident),
+								error
+							}
+						)?
```
Comment (mversic) [inline config/base/derive/src/documented.rs:202]: tabs

File: cli/src/main.rs [hunk 21]
```diff
@@ -43,7 +61,11 @@ async fn main() -> Result<(), color_eyre::Report> {
     if env::args().any(|a| SUBMIT_ARG.contains(&a.as_str())) {
         args.submit_genesis = true;
         if let Ok(genesis_path) = env::var("IROHA2_GENESIS_PATH") {
-            args.genesis_path = Some(ConfigPath::user_provided(&genesis_path)?);
+            args.genesis_path = Some(
+                ConfigPath::user_provided(&genesis_path)
+                    .wrap_err_with(|| "Required, because `--submit-genesis` was specified.")
+                    .wrap_err_with(|| format!("Could not read `{genesis_path}`"))?,
```
Comment (mversic) [inline cli/src/main.rs:67]: I like it how you use `wrap_err` multiple times to add more messages

**Review by mversic — DISMISSED** [review]

File: crypto/src/lib.rs (hunk 19 above)
Comment (appetrosyan) [reply crypto/src/lib.rs:218]: Good point

**Review by mversic — APPROVED** [review]

File: config/base/derive/src/documented.rs (hunk 20 above)
Comment (mversic) [reply config/base/derive/src/documented.rs:202]: still tabs

File: cli/src/lib.rs [hunk 22]
```diff
@@ -271,20 +217,14 @@ impl Iroha {
     /// - Reading telemetry configs
     /// - telemetry setup
     /// - Initialization of [`Sumeragi`]
-    #[allow(clippy::too_many_lines)] // This is actually easier to understand as a linear sequence of init statements.
+    #[allow(clippy::too_many_lines)]
+    #[iroha_logger::log(name = "init", skip_all)] // This is actually easier to understand as a linear sequence of init statements.
```
Comment (QuentinI) [inline cli/src/lib.rs:221]: Explainer comment slid down a line

File: cli/src/style.rs [hunk 23]
```diff
@@ -0,0 +1,75 @@
...
+            highlight: Style::new().bold(),
+            minor: Style::new().green(),
+        }
+    }
+}
+
+/// Determine if message colourisation is to be enabled
+pub fn should_disable_color() -> bool {
+    supports_color::on(supports_color::Stream::Stdout).is_none()
+        || std::env::var("TERMINAL_COLORS")
```
Comment (QuentinI) [inline cli/src/style.rs:31]: Since `supports_color` takes [NO_COLOR](http://no-color.org/) into account, do we really need to read one more env variable?

File: config/src/iroha.rs [hunk 24]
```diff
@@ -88,48 +87,56 @@ impl ConfigurationProxy {
...
                 sumeragi_proxy.key_pair =
                     Some(KeyPair::new(public_key.clone(), private_key.clone())?);
             } else {
-                eyre::bail!(ConfigError::ProxyBuildError(
-                    "Iroha public and private key not supplied, instantiating `sumeragi` keypair is impossible. Please provide `PRIVATE_KEY` and `PUBLIC_KEY` variables."
-                        .to_owned()
-                ))
+                return Err(ConfigError::MissingField {
+                    field: "PUBLIC_KEY and PRIVATE_KEY",
+                    message: "The sumeragi keypair is not provided in the example configuration. It's done this way to ensure you don't re-use the example keys in production, and know how to generate new keys. Please have a look at \n\nhttps://hyperledger.github.io/iroha-2-docs/guide/configure/keys.html\n\nto learn more.\n\n-----",
```
Comment (QuentinI) [inline config/src/iroha.rs:107]: Maybe paraphrasing it to be impersonal would be more polite? Reading that something is fool-proofed is nicer when there's room to assume it's not _you_ who may be the fool in question.

File: crypto/src/lib.rs [hunk 25]
```diff
@@ -178,6 +178,46 @@ ffi::ffi_item! {
...
 }
 
+/// Error when dealing with cryptographic functions
+#[derive(Debug, Display, serde::Deserialize)]
+pub enum Error {
+    /// Returned when trying to create an algorithm which does not exist
+    #[display(fmt = "Algorithm doesn't exist")] // TODO: which algorithm
+    NoSuchAlgorithm,
+    /// Occurs during deserialization of a private or public key
+    #[display(fmt = "Key could not be parsed. {_0}")]
```
Comment (QuentinI) [inline crypto/src/lib.rs:188]:
```suggestion
    #[display(fmt = "`Failed to parse key. {_0}")]
```
Similar to the rest

**Review by QuentinI — APPROVED** [review]
