### PR TITLE
[fix] #4057: Fix query store message ordering issue

### LINKED ISSUE #4057: [fix]: Fix live query service ordering issue
I've discovered issues with live query service that messages was processed out of order.

### PR DESCRIPTION
**Pull request by Erigara**
## Description

Previously 2 separate queues were used to send `insert`/ `remove` request to live query service which lead to issues when `insert`, `remove` were one right after another so that ordering of message processing was screwed.

Now single queue is used for messsages which guarantee that messages are processed sequentially eliminating possibility of this bug.  

### Linked issue

Closes #4057 

### Benefits

Bug is solved.

### Checklist

- [x] I've read `CONTRIBUTING.md`
- [x] I've used the standard signed-off commit format (or will squash just before merging)
- [x] All applicable CI checks pass (or I promised to make them pass later)
- [x] (optional) I've written unit tests for the code changes
- [x] I replied to all comments after code review, marking all implemented changes with thumbs up

### CODE REVIEW

**Review by mversic — APPROVED** [review]

File: core/src/query/store.rs [hunk 1]
```diff
@@ -288,3 +286,47 @@ impl LiveQueryStoreHandle {
...
+        let query_store_handle = threaded_rt.block_on(async { query_store.start() });
+
+        for i in 0..10_000 {
+            let pagination = Pagination::default();
+            let fetch_size = FetchSize {
+                fetch_size: NonZeroU32::new(1),
+            };
+            let sorting = Sorting::default();
+
+            let query_output = LazyValue::Iter(Box::new((0..100).map(|_| Value::Bool(false))));
```
Comment (Arjentix) [inline core/src/query/store.rs:309]: Why do you need `Box` here?

**Review by Arjentix — APPROVED** [review]

File: core/src/query/store.rs (hunk 1 above)
Comment (Erigara) [reply core/src/query/store.rs:309]: Because of `Box<dyn Iterator>` type in `LazyValue::Iter`
