### PR TITLE
[fix] #3498: Fix soft-fork detection

### LINKED ISSUE #3498: [bug]: Soft-fork detection is broken
At the moment soft-fork detection doesn't work as intended.

### PR DESCRIPTION
**Pull request by Erigara**
## Description

- Remove redundant fields from sumeragi;
- Fix soft-fork detection and signatrue validation;
- Add tests.

### Linked issue

Closes #3498 

### Benefits

Topology work correctly + new tests.

### Checklist

- [x] I've read `CONTRIBUTING.md`
- [x] I've used the standard signed-off commit format (or will squash just before merging)
- [x] All applicable CI checks pass (or I promised to make them pass later)
- [x] (optional) I've written unit tests for the code changes
- [x] I replied to all comments after code review, marking all implemented changes with thumbs up

### CODE REVIEW

File: client/benches/tps/utils.rs [hunk 1]
```diff
@@ -294,7 +294,7 @@ impl MeasurerUnit {
         let transfer_rose = TransferBox::new(
             asset_id(self.name),
             1_u32.to_value(),
-            asset_id(self.next_name),
+            account_id(self.next_name),
```
Comment (appetrosyan) [inline client/benches/tps/utils.rs:297]: Good catch. It was broken but we didn't spot it, because we don't routinely run benchmarks.

File: core/src/sumeragi/network_topology.rs [hunk 2]
```diff
@@ -42,14 +42,17 @@ impl Topology {
     pub fn is_consensus_required(&self) -> bool {
         self.min_votes_for_commit() > 1
     }
+
```
Comment (appetrosyan) [inline core/src/sumeragi/network_topology.rs:45]: In general, I would avoid whitespace changes if possible. GitHub could have implemented filtering those ages ago, but they likely never will, so this is just making life harder for the reviewer.

File: core/src/sumeragi/network_topology.rs [hunk 3]
```diff
@@ -234,4 +356,202 @@ mod tests {
         topology.update_peer_list(new_peers);
         assert_eq!(extract_ports(&topology), vec![0, 2, 5, 7])
     }
+
+    #[test]
+    fn filter_by_role() {
```
Comment (appetrosyan) [inline core/src/sumeragi/network_topology.rs:361]: Very good unit test. I'd recommend that you make it parametric, so that it accepts the number of key pairs (the macro would have to be inlined), so we could convert this to a `proptest`.

File: core/src/sumeragi/network_topology.rs [hunk 4]
```diff
@@ -234,4 +356,202 @@ mod tests {
...
+            topology.filter_signatures_by_roles(&[Role::ProxyTail], signatures.iter());
+        assert_eq!(proxy_tail_signatures.len(), 1);
+        assert_eq!(proxy_tail_signatures[0].public_key(), peers[4].public_key());
+
+        let validating_peers_signatures =
+            topology.filter_signatures_by_roles(&[Role::ValidatingPeer], signatures.iter());
+        assert_eq!(validating_peers_signatures.len(), 3);
+        assert!(validating_peers_signatures
+            .iter()
+            .all(|s| peers[1..4].iter().any(|p| p.public_key() == s.public_key())));
```
Comment (appetrosyan) [inline core/src/sumeragi/network_topology.rs:392]: This isn't exactly checking for deterministic topologies. It might also miss some cases where the peers all have the same public key (which is a problem).

File: core/src/sumeragi/network_topology.rs [hunk 5]
```diff
@@ -234,4 +356,202 @@ mod tests {
...
+
+        let observing_peers_signatures =
+            topology.filter_signatures_by_roles(&[Role::ObservingPeer], signatures.iter());
+        assert_eq!(observing_peers_signatures.len(), 2);
+        assert!(observing_peers_signatures
+            .iter()
+            .all(|s| peers[5..].iter().any(|p| p.public_key() == s.public_key())));
```
Comment (appetrosyan) [inline core/src/sumeragi/network_topology.rs:399]: Same here. I would suggest defining a function which actually checks  that these match the peers you would expect iterated in the correct order.

File: core/src/sumeragi/network_topology.rs [hunk 6]
```diff
@@ -234,4 +356,202 @@ mod tests {
...
+    }
+
+    #[test]
+    fn roles() {
```
Comment (appetrosyan) [inline core/src/sumeragi/network_topology.rs:403]: Consider converting into proptest.

File: core/src/sumeragi/network_topology.rs [hunk 7]
```diff
@@ -234,4 +356,202 @@ mod tests {
...
+        }
+    }
+
+    #[test]
+    fn proxy_tail() {
+        let peers = peers![0, 1, 2, 3, 4, 5, 6];
+        let topology = Topology::new(peers.clone());
+
+        assert_eq!(topology.proxy_tail(), &peers[4]);
+    }
```
Comment (appetrosyan) [inline core/src/sumeragi/network_topology.rs:431]: Consider making a `proptest`.

File: core/src/sumeragi/network_topology.rs [hunk 8]
```diff
@@ -234,4 +356,202 @@ mod tests {
...
+
+    #[test]
+    fn leader() {
```
Comment (appetrosyan) [inline core/src/sumeragi/network_topology.rs:434]: Not a good `proptest` candidate.

File: core/src/sumeragi/network_topology.rs [hunk 9]
```diff
@@ -234,4 +356,202 @@ mod tests {
...
+        let mut signatures = key_pairs
+            .iter()
+            .enumerate()
+            .filter(|(i, _)| *i == 2) // Retain only last signature
+            .map(|(_, key_pair)| SignatureOf::new(key_pair.clone(), &dummy).expect("Failed to sign"))
+            .collect::<Result<SignaturesOf<_>, _>>()
+            .expect("Failed to create `SignaturesOf`");
+
+        let result = topology.verify_signatures(&mut signatures, HashOf::new(&dummy));
+        assert_eq!(result, Ok(()))
```
Comment (appetrosyan) [inline core/src/sumeragi/network_topology.rs:484]:
```suggestion
        assert!(topology.verify_signatures(&mut signatures, HashOf::new(&dummy)).is_ok())
```

File: core/src/sumeragi/network_topology.rs [hunk 10]
```diff
@@ -234,4 +356,202 @@ mod tests {
...
+        let mut signatures = key_pairs
+            .iter()
+            .map(|key_pair| SignatureOf::new(key_pair.clone(), &dummy).expect("Failed to sign"))
+            .collect::<Result<SignaturesOf<_>, _>>()
+            .expect("Failed to create `SignaturesOf`");
+
+        assert_eq!(
+            topology.verify_signatures(&mut signatures, HashOf::new(&dummy)),
+            Ok(())
+        );
```
Comment (appetrosyan) [inline core/src/sumeragi/network_topology.rs:461]:
```suggestion
        assert!(
            topology.verify_signatures(&mut signatures, HashOf::new(&dummy)).is_ok()
        );
```

File: core/src/sumeragi/network_topology.rs [hunk 11]
```diff
@@ -163,16 +262,39 @@ pub enum Role {
...
+    /// Error when block doesn't have proxy tail signature
+    #[error("The block doesn't have proxy tail signature")]
+    ProxyTailMissing,
+    /// Error when block doesn't have leader signature
+    #[error("The block doesn't have leader signature")]
+    LeaderMissing,
+}
+
 #[cfg(test)]
 mod tests {
```
Comment (appetrosyan) [inline core/src/sumeragi/network_topology.rs:285]: Good unit test coverage would have caught the error early. This is why it's important.

Comment (appetrosyan) [reply core/src/sumeragi/network_topology.rs:285]: For each test, I'd refer to the relevant section of the whitepaper so we can verify which parts are to-spec and which are not.

File: core/src/sumeragi/network_topology.rs [hunk 12]
```diff
@@ -163,16 +262,39 @@ pub enum Role {
     ProxyTail,
 }
 
+/// Error during signature verification
+#[derive(thiserror::Error, Debug, Clone, Copy, PartialEq, Eq)]
+pub enum SignatureVerificationError {
+    /// Error when block doesn't have enough valid signatures
+    #[error("The block doesn't have enough valid signatures to be committed ({votes_count} out of {min_votes_for_commit}).")]
```
Comment (appetrosyan) [inline core/src/sumeragi/network_topology.rs:269]: I was thinking of adding some primitive error types. We have common patterns like not enough of X, which has verbatim the same error message, that is inconsistently replicated all over the codebase. 

```rust
struct Insufficient<T: Ord> {
    expected: T, 
    actual: T, 
}
```
with some basic convenience functions.

File: core/src/sumeragi/network_topology.rs [hunk 13]
```diff
@@ -125,29 +128,125 @@ impl Topology {
...
+
+        topology.update_topology(block, new_peers);
+
+        // Rotate all once for every view_change
+        topology.rotate_all_n(view_change_index);
+
+        topology
+    }
+
+    /// Check if block's signatures meet requirements for given topology
```
Comment (appetrosyan) [inline core/src/sumeragi/network_topology.rs:198]: Please refer to requirements in the whitepaper, or (better) inline the requirements to the docstring. 

Consensus is important, and good documentation here pays off in hours saved debugging.

File: core/src/sumeragi/network_topology.rs [hunk 14]
```diff
@@ -125,29 +128,125 @@ impl Topology {
...
+            .filter_signatures_by_roles(&[Role::Leader], signatures.iter())
+            .is_empty()
+        {
+            return Err(SignatureVerificationError::LeaderMissing);
+        }
+
+        if self
+            .filter_signatures_by_roles(&[Role::ProxyTail], signatures.iter())
+            .is_empty()
+        {
```
Comment (appetrosyan) [inline core/src/sumeragi/network_topology.rs:244]: How do we tell that we have enough `ValidatinPeer` signatures? It's not obvious to me from the code.

File: core/src/sumeragi/network_topology.rs (hunk 9 above)
Comment (Erigara) [reply core/src/sumeragi/network_topology.rs:484]: I would like to keep is this way because this way we can see `rhs` and what exact error we received.

**Review by appetrosyan — CHANGES_REQUESTED** [review]

File: core/src/sumeragi/network_topology.rs [hunk 15]
```diff
@@ -125,29 +128,125 @@ impl Topology {
...
+        self.rotate_all_n(1);
     }
+
+    /// Rotate peers n times where n is a number of failed attempt to create a block.
+    pub fn rotate_all_n(&mut self, n: usize) {
+        let len = self.sorted_peers.len();
+        if let Some(rem) = n.checked_rem(len) {
+            self.sorted_peers.rotate_left(rem);
+        }
+    }
```
Comment (appetrosyan) [inline core/src/sumeragi/network_topology.rs:153]: There should be a way to do this in $O(1)$

File: core/src/sumeragi/network_topology.rs [hunk 16]
```diff
@@ -125,29 +128,125 @@ impl Topology {
     pub fn leader(&self) -> &PeerId {
         &self.sorted_peers[0]
     }
+
     /// Get proxy tail's peer id.
     pub fn proxy_tail(&self) -> &PeerId {
-        &self.sorted_peers[self.min_votes_for_commit()]
+        &self.sorted_peers[self.min_votes_for_commit() - 1]
```
Comment (appetrosyan) [inline core/src/sumeragi/network_topology.rs:134]: Comment on why $-1$

File: core/src/sumeragi/network_topology.rs [hunk 17]
```diff
@@ -105,15 +108,15 @@ impl Topology {
...
     /// the function will return `Role::ObservingPeer`.
     // This lint is a bad suggestion.
-    #[allow(clippy::option_if_let_else)]
     pub fn role(&self, peer_id: &PeerId) -> Role {
         match self.sorted_peers.iter().position(|p| p == peer_id) {
             Some(index) if index == 0 => Role::Leader,
-            Some(index) if index < self.min_votes_for_commit() => Role::ValidatingPeer,
-            Some(index) if index == self.min_votes_for_commit() => Role::ProxyTail,
+            Some(index) if index < self.min_votes_for_commit() - 1 => Role::ValidatingPeer,
+            Some(index) if index == self.min_votes_for_commit() - 1 => Role::ProxyTail,
```
Comment (appetrosyan) [inline core/src/sumeragi/network_topology.rs:119]: Comment on why we need to do `-1`. This can save searching far and wide to find the reason.

File: core/src/sumeragi/network_topology.rs (hunk 14 above)
Comment (Erigara) [reply core/src/sumeragi/network_topology.rs:244]: We check for total amount of signatures that we have at least 2f+1 signatures and then individually for proxy tail and leader signatures.

File: core/src/sumeragi/network_topology.rs (hunk 2 above)
Comment (Erigara) [reply core/src/sumeragi/network_topology.rs:45]: Newline between methods is common pattern across our codebase, so should i revert this change?

File: core/src/sumeragi/main_loop.rs [hunk 18]
```diff
@@ -1082,3 +1008,263 @@ fn early_return(
...
+
+        (wsv, kura, block)
+    }
+
+    #[test]
+    fn block_sync_invalid_block() {
+        let (finalized_wsv, _, mut block) = create_data_for_test();
+        let wsv = finalized_wsv.clone();
+
+        // Mailfrom block to make it invalid
```
Comment (0x009922) [inline core/src/sumeragi/main_loop.rs:1159]:
```suggestion
        // Malform block to make it invalid
```

?

File: core/src/sumeragi/main_loop.rs [hunk 19]
```diff
@@ -1082,3 +1008,263 @@ fn early_return(
...
+
+    #[test]
+    fn block_sync_invalid_soft_fork_block() {
+        let (finalized_wsv, kura, mut block) = create_data_for_test();
+        let wsv = finalized_wsv.clone();
+
+        kura.store_block(block.clone());
+        wsv.apply(&block).expect("Failed to apply block");
+
+        // Mailfrom block to make it invalid
```
Comment (0x009922) [inline core/src/sumeragi/main_loop.rs:1174]:
```suggestion
        // Malform block to make it invalid
```

Same

File: core/src/sumeragi/network_topology.rs (hunk 2 above)
Comment (0x009922) [reply core/src/sumeragi/network_topology.rs:45]: As for me, I don't have any cognitive pressure from these newlines. Instead, it looks satisfying.

File: core/src/sumeragi/network_topology.rs (hunk 17 above)
Comment (0x009922) [reply core/src/sumeragi/network_topology.rs:119]: Or add self-explanatory local (or non-local) constant:

```rust
const SIZE_AND_INDEX_DIFFERENCE = 1;
```

It will be compiled away anyway (haven't checked though).

File: core/src/sumeragi/network_topology.rs [hunk 20]
```diff
@@ -105,15 +108,15 @@ impl Topology {
             .cloned()
             .collect()
     }
+
     /// What role does this peer have in the topology. If it is not in the toplogy
     /// the function will return `Role::ObservingPeer`.
     // This lint is a bad suggestion.
```
Comment (0x009922) [inline core/src/sumeragi/network_topology.rs:114]:
```suggestion
```

File: core/src/sumeragi/network_topology.rs (hunk 17 above)
Comment (Erigara) [reply core/src/sumeragi/network_topology.rs:119]: I moved this logic into `proxy_tail_index` private function with required clarifications.

File: core/src/sumeragi/network_topology.rs (hunk 15 above)
Comment (Erigara) [reply core/src/sumeragi/network_topology.rs:153]: So how this can look like imo:

1. Use circular linked list and have a pointer to current head of the list.
2. In such case `rotate_set_a` operation will be to just moving leader element to the proxy tail position which is `O(1)`.
3. `rotate_all_n` will be just moving head pointer `n` elements forward

To optimize allocation fragmentation we can use [typed_arena](https://docs.rs/typed-arena/latest/typed_arena) for node storage.

However `update_peer_list` and `lift_up_peers` might be not so optimal in such case.

Comment (Erigara) [reply core/src/sumeragi/network_topology.rs:153]: Hmm, probably situation can be even simpler than that. 
If we use observation that we construct topology once per round and then only use rotate all.
We can just store index of current leader, then `rotate_all` will be just increment of this index.

Comment (Erigara) [reply core/src/sumeragi/network_topology.rs:153]: Created #3519 for further discussion.

File: core/src/sumeragi/network_topology.rs (hunk 14 above)
Comment (appetrosyan) [reply core/src/sumeragi/network_topology.rs:244]: Add as comments and I'll approve

File: core/src/sumeragi/network_topology.rs (hunk 12 above)
Comment (Erigara) [reply core/src/sumeragi/network_topology.rs:269]: Created #3524.

File: core/src/sumeragi/network_topology.rs (hunk 2 above)
Comment (appetrosyan) [reply core/src/sumeragi/network_topology.rs:45]: > Newline between methods is common pattern across our codebase, so should i revert this change?

Not this instance. Just don't add newlines to existing code if you have a PR with important contents. 

This is less of a problem, because you use conventional commits.

**Review by appetrosyan — APPROVED** [review]

File: core/src/block.rs [hunk 21]
```diff
@@ -46,39 +42,36 @@ pub struct PendingBlock {
...
 }
 
-impl BlockBuilder<'_> {
+impl BlockBuilder {
     /// Create a new [`PendingBlock`] from transactions.
     pub fn build(self) -> PendingBlock {
         let timestamp = crate::current_time().as_millis();
+        let height = self.wsv.height() + 1;
+        let previous_block_hash = self.wsv.latest_block_hash();
+        let transaction_validator = self.wsv.transaction_validator();
```
Comment (SamHSmith) [inline core/src/block.rs:66]: Smart.

**Review by SamHSmith — APPROVED** [review]
I don't see any issues with this.
