### PR TITLE
[fix] #2850: Fix deserialization/decoding of `Fixed`

### LINKED ISSUE #2850: Fix deserialization/decoding of `FixNum`
The current test `deserialize_from_json_should_fail` doesn't test anything. The test should verify that the correct error was returned, not that some error was returned. Fix the test, add a test for decoding and write manual implementations of `Deserialize` and `Decode`.

### PR DESCRIPTION
**Pull request by Erigara**
Signed-off-by: Shanin Roman <shanin1000@yandex.ru>

### Description of the Change

Check that `Fixed` is not negative during decoding/deserialization. 

### Issue

Closes #2850.

### Benefits

Corrent decoding/deserialization behavior.

### Possible Drawbacks

None.

### Usage Examples or Tests *[optional]*

```
cargo test --package iroha_primitives --lib -- fixed::tests --nocapture
```

### CODE REVIEW

**Review by mversic — DISMISSED** [review]

File: primitives/src/fixed.rs [hunk 1]
```diff
@@ -255,9 +274,57 @@ mod tests {
...
+            result.unwrap_err().to_string(),
+            "-1.0: negative value not allowed"
+        )
+    }
+
+    #[test]
+    fn decode_negative_value_from_parity_scale_should_fail() {
+        let encoded = Fixed::negative_one().encode();
+        let result: Result<Fixed, _> = Fixed::decode(&mut encoded.as_slice());
+        assert!(result.is_err());
```
Comment (mversic) [inline primitives/src/fixed.rs:291]: not possible to check failure reason?

**Review by mversic — APPROVED** [review]

File: primitives/src/fixed.rs (hunk 1 above)
Comment (Erigara) [reply primitives/src/fixed.rs:291]: Yes, sadly without `chain-error` feature we receive just placeholder [`Codec Error`](https://docs.rs/parity-scale-codec/latest/src/parity_scale_codec/error.rs.html#82)

**Review by QuentinI — APPROVED** [review]

**Comment by pesterev** [comment]
It seems that this PR also close my recently opened issue #2950 (I didn’t notice that #2850 and #2950 were the same)

**Review by pesterev — APPROVED** [review]
