### PR TITLE
[fix] #4162: SignedTransaction is immutable

### LINKED ISSUE #4162: Are genesis transaction signatures checked?
> BTW, I am confused by both tests patching constructed `GenesisNetwork`. They are inserting plain instructions into the payload of a signed transaction. By doing so, AFAIK, they invalidate the signature of the transaction being computed using the previous payload. One test checks that Iroha validates genesis by providing an invalid permission token, but Iroha should not accept genesis because of its signatures I guess. Another test checks whether base64 triggers are handled fine. I don't why the second test passes.

_Originally posted by @0x009922 in https://github.com/hyperledger/iroha/pull/4153#discussion_r1432095800_

### PR DESCRIPTION
**Pull request by Erigara**
## Description

Remove `payload_mut` method which is considered harmful.

### Linked issue

Closes #4162 

### Benefits

Don't break `SignedTransaction` invariant.

### CODE REVIEW

File: data_model/src/transaction.rs [hunk 1]
```diff
@@ -744,6 +734,12 @@ mod http {
             self
         }
 
+        /// Set creation time of transaction
+        pub fn set_creation_time(&mut self, creation_time_ms: u64) -> &mut Self {
```
Comment (mversic) [inline data_model/src/transaction.rs:738]: the same

**Review by mversic — CHANGES_REQUESTED** [review]

File: data_model/src/transaction.rs [hunk 2]
```diff
@@ -715,6 +699,12 @@ mod http {
             self
         }
 
+        /// Set executable for this transaction
+        pub fn with_executable(mut self, executable: Executable) -> Self {
```
[the remark this answers is not in the document]
Comment (mversic) [reply data_model/src/transaction.rs:703]: it's only used for testing

[the remark this answers is not in the document]
Comment (Erigara) [reply data_model/src/transaction.rs:703]: It's not different from `with_wasm` or `with_instructions`.
Also doesn't break any invariants because we are working with `TransactionBuilder`, not `SignedTransaction`.

File: data_model/src/transaction.rs (hunk 1 above)
Comment (Erigara) [reply data_model/src/transaction.rs:738]: I don't see why this method should be private, user might want to specify exact timestamp for his transaction.

Comment (mversic) [reply data_model/src/transaction.rs:738]: but then you have to modify the signature

File: data_model/src/transaction.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (mversic) [reply data_model/src/transaction.rs:703]: oh, I see it's defined on `TransactionBuilder`. But we already have `with_wasm` and `with_instructions`. I think you can remove both in favor of the `with_executable(mut self, executable: impl Into<Executable>`

File: data_model/src/transaction.rs (hunk 1 above)
Comment (mversic) [reply data_model/src/transaction.rs:738]: ok. Is `creation_time` even required to be part of the payload and signed?

File: data_model/src/transaction.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (Erigara) [reply data_model/src/transaction.rs:703]: good point

File: data_model/src/transaction.rs (hunk 1 above)
Comment (Erigara) [reply data_model/src/transaction.rs:738]: yes, otherwise it will be hard to distinguish two transfers

File: data_model/src/transaction.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (Erigara) [reply data_model/src/transaction.rs:703]: it won't work unfortunately with `with_instructions` because it's more involved than just call `into`

**Review by DCNick3 — APPROVED** [review]

**Review by mversic — APPROVED** [review]

File: data_model/src/transaction.rs (hunk 1 above)
Comment (mversic) [reply data_model/src/transaction.rs:738]: could the `creation_time` be assigned by the node instead of the client?

Comment (Erigara) [reply data_model/src/transaction.rs:738]: i don't this so because this will mess up transaction signature

Comment (mversic) [reply data_model/src/transaction.rs:738]: yes, it won't be a part of transaction signature. I'm questioning whether it makes sense to sign this piece of information? We're trusting a user that they will use a correct time, we might be trusting the peer

Comment (Erigara) [reply data_model/src/transaction.rs:738]: @mversic if transaction has wrong time it will be just rejected either as being outdated or from future

Comment (mversic) [reply data_model/src/transaction.rs:738]: > @mversic if transaction has wrong time it will be just rejected either as being outdated or from future

I know this. My intention here is to remove `create_time_ms` from transaction that user submits so that we can remove `pending_transaction` endpoint all together. It's the only thing that stands in the way of MST

Comment (Erigara) [reply data_model/src/transaction.rs:738]: I'm not sure that this will end up well. 
So currently we use time + nonce to distinguish between otherwise identical transactions and time is convenient way to do so.

If we would remove time from the transaction user have to use unique nonce every time he send transaction. 
And we back to square one where user need to get pending transactions in order to get proper nonce.

We might consider that creation of MST is happens outside iroha: that interested parties can communicate and create proper MST. 
This would allow to simplify:
1. CLI by not querying `/pending` transactions on every command
2. Queue because we can reject transactions with invalid signature check immediately we won't have partial MST which might or might not get additional signatures.

Comment (mversic) [reply data_model/src/transaction.rs:738]: thanks for the thoughtful response

**Review by DCNick3 — APPROVED** [review]

**Review by mversic — APPROVED** [review]
