### PR TITLE
[fix] #3393: Break communication deadlock loop in actors

### LINKED ISSUE #3393: [bug]: Break deadlock communication cycles in actors
Iroha sometimes freezes under high load due to communication deadlock of  bounded channels loop.

### PR DESCRIPTION
**Pull request by Erigara**
## Description

- Add tokio console support.
- Fixed bug with communication deadlock.
- Refactor sumeragi/network in terms of responsibility for connecting/disconnecting peers. 

### Linked issue

Closes #3393, #3392 

### Checklist

- [x] I've read `CONTRIBUTING.md`
- [x] I've used the standard signed-off commit format (or will squash just before merging)
- [x] All applicable CI checks pass (or I promised to make them pass later)
- [ ] (optional) I've written unit tests for the code changes
- [ ] I replied to all comments after code review, marking all implemented changes with thumbs up

### CODE REVIEW

**Review by SamHSmith — APPROVED** [review]
Looks good!

File: p2p/src/lib.rs [hunk 1]
```diff
@@ -94,3 +94,57 @@ impl From<io::Error> for Error {
 
 /// Result shorthand.
 pub type Result<T, E = Error> = core::result::Result<T, E>;
+
+pub(crate) mod unbounded_with_len {
```
Comment (Arjentix) [inline p2p/src/lib.rs:98]: Can you add documentation for this module, functions and structs inside it? Also I thought `clippy` will warn about it

File: p2p/src/peer.rs [hunk 2]
```diff
@@ -68,16 +69,18 @@ pub mod handles {
 
     /// Peer actor handle.
     pub struct PeerHandle<T: Pload> {
-        pub(super) post_sender: mpsc::Sender<T>,
+        // NOTE: it's ok for this channel to be unbounded.
+        // Because post messages originates inside system and there rate is configurable.
```
Comment (Arjentix) [inline p2p/src/peer.rs:73]:
```suggestion
        // Because post messages originates inside system and their rate is configurable.
```

Comment (Arjentix) [reply p2p/src/peer.rs:73]:
```suggestion
        // Because post messages originates inside system where rate is configurable.
```

Comment (Arjentix) [reply p2p/src/peer.rs:73]: I think one of this is right

File: p2p/src/network.rs [hunk 3]
```diff
@@ -87,83 +85,68 @@ impl<T: Pload, K: Kex + Sync, E: Enc + Sync> NetworkBaseHandle<T, K, E> {
...
+            .send(topology)
             .expect("NetworkBase must accept messages until there is at least one handle to it")
     }
 
     /// Receive latest update of [`OnlinePeers`]
-    pub fn online_peers(&mut self) -> OnlinePeers {
-        self.online_peers_receiver.borrow_and_update().clone()
+    pub fn online_peers<P>(&self, f: impl FnOnce(&OnlinePeers) -> P) -> P {
+        f(&self.online_peers_receiver.borrow())
     }
```
Comment (Arjentix) [inline p2p/src/network.rs:135]: That's interesting

File: p2p/src/network.rs [hunk 4]
```diff
@@ -276,7 +265,37 @@ impl<T: Pload, K: Kex, E: Enc> NetworkBase<T, K, E> {
...
+            .filter(|peer| !self.peers.contains_key(&peer.public_key))
+            .cloned()
+            .collect::<Vec<_>>();
+
+        let to_disconnect = self.peers
+            .keys()
+            // Peer is connected but shouldn't
+            .filter(|public_key| !self.current_topology.contains(*public_key))
+            .cloned()
+            .collect::<Vec<_>>();
```
Comment (Arjentix) [inline p2p/src/network.rs:287]: Can this be done with some kind of set manipulation? For example substraction?

File: core/src/sumeragi/main_loop.rs [hunk 5]
```diff
@@ -410,14 +361,18 @@ fn replace_top_block(
...
 
     cache_transaction(state, sumeragi)
 }
 
-fn update_topology(state: &mut State, committed_block: &VersionedCommittedBlock) {
+fn update_topology(
+    state: &mut State,
+    sumeragi: &Sumeragi,
+    committed_block: &VersionedCommittedBlock,
+) {
```
[the remark this answers is not in the document]
Comment (Erigara) [reply core/src/sumeragi/main_loop.rs:375]: It can be, but before this i want to do some refactoring in terms of relations between ‘Sumeragi’ and ’State’ because there bound isn't really clear to me and we almost always use them together.

File: scripts/test_env.sh
[the remark this answers is not in the document]
Comment (Erigara) [reply scripts/test_env.sh:1]: I'm using this file all the time, so i can't forget about it ;)

File: config/iroha_test_config.json [hunk 6]
```diff
@@ -67,7 +67,8 @@
     "TELEMETRY_CAPACITY": 1000,
     "COMPACT_MODE": false,
     "LOG_FILE_PATH": null,
-    "TERMINAL_COLORS": true
+    "TERMINAL_COLORS": true,
+    "TOKIO_CONSOLE_ADDR": "127.0.0.1:5555"
```
[the remark this answers is not in the document]
Comment (Erigara) [reply config/iroha_test_config.json:71]: I just don't want to introduce inconsistency  as you say. 
Let's gather other opinions @SamHSmith, @mversic, @appetrosyan

File: p2p/src/network.rs (hunk 4 above)
Comment (Erigara) [reply p2p/src/network.rs:287]: Yes, it's doable, but will require slight changes in way how we store peers. I will do this.

File: config/iroha_test_config.json (hunk 6 above)
[the remark this answers is not in the document]
Comment (appetrosyan) [reply config/iroha_test_config.json:71]: It's fine as long as it's not explicitly required.

File: core/src/sumeragi/main_loop.rs (hunk 5 above)
[the remark this answers is not in the document]
Comment (appetrosyan) [reply core/src/sumeragi/main_loop.rs:375]: Methods aren't always better. IMO just a `fn` is enough.

File: p2p/src/lib.rs (hunk 1 above)
Comment (appetrosyan) [reply p2p/src/lib.rs:98]: It's a private module. It doesn't need docs, but extra docs don't hurt.

File: scripts/test_env.sh
[the remark this answers is not in the document]
Comment (appetrosyan) [reply scripts/test_env.sh:1]: I do too. `docker` takes ages to compile.

File: p2p/src/peer.rs (hunk 2 above)
Comment (appetrosyan) [reply p2p/src/peer.rs:73]:
```suggestion
        // Because post messages originate inside the  system and their rate is configurable.
```

**Review by appetrosyan — APPROVED** [review]

File: core/src/sumeragi/main_loop.rs (hunk 5 above)
[the remark this answers is not in the document]
Comment (Erigara) [reply core/src/sumeragi/main_loop.rs:375]: @Arjentix can we resolve this?

File: config/iroha_test_config.json (hunk 6 above)
[the remark this answers is not in the document]
Comment (Erigara) [reply config/iroha_test_config.json:71]: We explicitly required to either pass in configuration or environment, so i will hide parameter under feature flag.

File: p2p/src/network.rs (hunk 4 above)
Comment (Arjentix) [reply p2p/src/network.rs:287]: > And if you look how difference is implemented nothing fancy here it's almost equal to how i implemented it here.

Well it's mostly not about performance it's about readabillity and understanding what author meant.

But I see the point, that it doesn't worth it. Closing this

File: config/Cargo.toml
Comment (Arjentix) [inline config/Cargo.toml:1]: Maybe add an empty line at the end of this file?

**Review by Arjentix — APPROVED** [review]

**Review by appetrosyan — APPROVED** [review]

**Review by appetrosyan — APPROVED** [review]

**Review by Arjentix — APPROVED** [review]

**Review by Arjentix — APPROVED** [review]

**Review by appetrosyan — APPROVED** [review]

**Review by Arjentix — APPROVED** [review]
