### PR TITLE
[fix] #1480: Shut down on panic

### LINKED ISSUE #1480: Stop Iroha on panic
On panic in one of the threads we should stop Iroha2 with appropriate panic message. Currently it seemed that with `unreachable()!` panic Iroha peer was not stopped.

### PR DESCRIPTION
**Pull request by ales-tsurko**
### Description of the Change

Currently, when panic occurs, only the corresponding thread shuts down. But we need the whole program to shut down if a panic appeared on any thread. A panic hook is provided, which uses [`tokio::sync::Notify`](https://docs.rs/tokio/1.19.2/tokio/sync/struct.Notify.html) to gracefully shut down the program.

### Issue

Fixes #1480 

### Benefits

The program will shut down gracefully if a panic occurs on any thread.

### Possible Drawbacks

As we use globals (i.e. panic hook), it can affect tests in some cases. But the test environment should be close or same as the production one. Following contributors should have it in mind.

### Alternate Designs *[optional]*

[A cargo config](https://doc.rust-lang.org/book/ch09-01-unrecoverable-errors-with-panic.html) or `std::process::exit` can be used instead, but that could leave garbage.

### CODE REVIEW

**Review by appetrosyan — APPROVED** [review]

File: cli/src/lib.rs [hunk 1]
```diff
@@ -242,7 +250,9 @@ where
             Arc::clone(&notify_shutdown),
         );
 
-        Self::start_listening_signal(notify_shutdown)?;
+        Self::start_listening_signal(Arc::clone(&notify_shutdown))?;
```
Comment (QuentinI) [inline cli/src/lib.rs:253]: Sounds a bit confusing to me, maybe we should rename it to something like `listen_for_signals`?

File: cli/src/lib.rs [hunk 2]
```diff
@@ -138,6 +138,14 @@ where
         .await
     }
 
+    fn prepare_panic_hook(notify_shutdown: Arc<Notify>) {
+        let hook = panic::take_hook();
+        panic::set_hook(Box::new(move |info| {
+            hook(info);
+            notify_shutdown.notify_one();
```
Comment (ilchu) [inline cli/src/lib.rs:145]: I might have missed some detail, but wouldn't it require
[`notify_waiters()`](https://docs.rs/tokio/latest/tokio/sync/struct.Notify.html#method.notify_waiters) 
to send the signal to both the telemetry and API servers? In the same way it was done
in the `cli::start_listening_signal()`, for example.

Comment (ales-tsurko) [reply cli/src/lib.rs:145]: Oh, thanks!

File: cli/src/lib.rs (hunk 1 above)
Comment (QuentinI) [reply cli/src/lib.rs:253]: > It's not related to the task

Sure, that's just an observation, I approved regardless.

File: cli/src/lib.rs (hunk 2 above)
Comment (ales-tsurko) [reply cli/src/lib.rs:145]: Hm, with `notify_waiters` it doesn't pass the test. The notification keeps being awaiting.

Comment (ilchu) [reply cli/src/lib.rs:145]: Then I guess it's fine as it is. Maybe asking @pesterev to take a look would
make sense, as he did the other `Notify` PR, but I'll approve for now.

**Review by ilchu — APPROVED** [review]
