### PR TITLE
[fix] #2548: Warn on large genesis file

### LINKED ISSUE #2548: [BUG]: Zombie Genesis
Under high load conditions, and given high packet loss, genesis application might not finish, or go through partially. 

In this state Iroha does not have a valid genesis. It looks like a `default` or rather empty genesis is at play. 

We need to reduce the incidence of these situations, and panic when they occur

### PR DESCRIPTION
**Pull request by Erigara**
Signed-off-by: Shanin Roman <shanin1000@yandex.ru>

### Description of the Change

Put warning in logs if genesis file is larger or equal 1Gb.

### Issue

Partially closes #2548. 

### Benefits

Notify uses.

### Possible Drawbacks

None.

### Usage Examples or Tests *[optional]*

Run iroha with genesis above 1Gb.

### Alternate Designs *[optional]*

I take simplest possible approach, other designs could be considered.

### CODE REVIEW

File: core/src/genesis.rs [hunk 1]
```diff
@@ -260,13 +260,22 @@ pub struct RawGenesisBlock {
...
     ///
     /// # Errors
     /// If file not found or deserialization from file fails.
     pub fn from_path<P: AsRef<Path> + Debug>(path: P) -> Result<Self> {
         let file = File::open(&path).wrap_err(format!("Failed to open {:?}", &path))?;
+        let size = file
+            .metadata()
+            .wrap_err("Unable to access genesis file metadata")?
+            .len();
+        if size >= Self::WARN_ON_GENESIS_GTE {
```
Comment (mversic) [inline core/src/genesis.rs:276]: are we checking file size or deserialized block size?

Comment (Erigara) [reply core/src/genesis.rs:276]: file size

**Review by mversic — APPROVED** [review]

**Review by appetrosyan — APPROVED** [review]
