### PR TITLE
[fix] #3038: Re-enable multisigs

### LINKED ISSUE #2595: Fix multisignature
After the merge of #2582 we will broke multisignature mechanism. It was working because of signature checking mistake (see #2580).

### LINKED ISSUE #3038: [fix]: Re-enable multisigs
Currently multi-signatures transactions is not working due to changes in the `Queue` and `Sumeragi`, this changes can be rollbacked in order to re-enable multisigs.

### PR DESCRIPTION
**Pull request by Erigara**
### Description of the Change

- Revert some changes made to `Queue` and `Sumeragi` to bring multisignatures back. 
- Turn on tests that works with multisigs.
- Add second queue for the multisignatures.

We need second queue for multisigns in order to prevent situation when multisig transactions prevent ordinary transactions from being processed. 

### Issue

Closes #2595, #3038, #3039.

### Benefits

Multisignatures are working again. 

### Possible Drawbacks

More complex queue.

### Usage Examples or Tests

Test for multisig functionality on one peer:

```bash
cargo test --package iroha_core --lib -- queue::tests::push_multisignature_tx --exact --nocapture
```

Test for multisig transaction gossiping between multiple peers: 

```bash
cargo test --package iroha_client --test mod -- integration::multisignature_transaction::multisignature_transactions_should_wait_for_all_signatures --exact --nocapture
```

### CODE REVIEW

File: core/src/sumeragi/main_loop.rs [hunk 1]
```diff
@@ -231,12 +231,11 @@ fn gossip_transactions<F>(
     F: FaultInjection,
 {
     if last_sent_transaction_gossip_time.elapsed() > sumeragi.gossip_period {
-        let txs = state
-            .transaction_cache
-            .iter()
-            .take(sumeragi.gossip_batch_size as usize)
-            .cloned()
-            .collect::<Vec<_>>();
+        // Transactions are intentionally taken from the queue instead of the cache
```
Comment (QuentinI) [inline core/src/sumeragi/main_loop.rs:234]: This could impact performance, did you run any comparisons?

**Review by QuentinI — COMMENTED** [review]
I assume this builds upon #3035, so looked only at the last commit.

File: core/src/sumeragi/main_loop.rs (hunk 1 above)
Comment (Erigara) [reply core/src/sumeragi/main_loop.rs:234]: Not yet, i have problems running `tps` benchmark on `dev` branch.

Comment (Erigara) [reply core/src/sumeragi/main_loop.rs:234]: Result of `tps-dev` benchmark doesn't reveal any changes in the performance.

```
Before (fbc7d346):
time:   [381.34 tps 455.59 tps 529.53 tps]

After (81448627):
time:   [433.57 tps 503.22 tps 568.07 tps]
change: [+26.541% +9.4650% -11.143%] (p = 0.39 > 0.05)
No change in performance detected.
```

File: config/iroha_test_config.json [hunk 2]
```diff
@@ -57,6 +57,7 @@
   "QUEUE": {
     "MAXIMUM_TRANSACTIONS_IN_BLOCK": 8192,
     "MAXIMUM_TRANSACTIONS_IN_QUEUE": 65536,
+    "MAXIMUM_TRANSACTIONS_IN_WAITING_BUFFER": 65536,
```
Comment (appetrosyan) [inline config/iroha_test_config.json:60]:
```suggestion
    "MAXIMUM_TRANSACTIONS_IN_SIGNATURE_BUFFER": 65536,
```

File: core/src/queue.rs [hunk 3]
```diff
@@ -26,8 +27,10 @@ use crate::prelude::*;
 /// Multiple producers, single consumer
 #[derive(Debug)]
 pub struct Queue {
-    /// The queue proper
+    /// The queue for transactions that pass signature check
```
Comment (appetrosyan) [inline core/src/queue.rs:30]:
```suggestion
    /// The queue for transactions that passed signature check
```

File: core/src/queue.rs [hunk 4]
```diff
@@ -147,49 +147,84 @@ impl Queue {
         tx: VersionedAcceptedTransaction,
         wsv: &WorldStateView,
     ) -> Result<(), (VersionedAcceptedTransaction, Error)> {
```
Comment (appetrosyan) [inline core/src/queue.rs:149]: Looks to me like the signature is a little off. Do you think it should be a tuple instead of `struct`?

File: core/src/queue.rs [hunk 5]
```diff
@@ -147,49 +147,84 @@ impl Queue {
...
-                    old_tx
-                        .get_mut()
-                        .as_mut_v1()
-                        .signatures
-                        .extend(tx.as_v1().signatures.clone());
-                    return Ok(());
+        match self.check_tx(&tx, wsv) {
+            Err(e) => Err((tx, e)),
+            Ok(MustUse(signature_check)) => {
+                // Get `txs_len` before entry to avoid deadlock
```
Comment (appetrosyan) [inline core/src/queue.rs:153]: Or, get the lock explicitly and drop it when done. Picking up and almost immediately dropping a mutex guard is not the worst but it's inefficient.

File: core/src/queue.rs [hunk 6]
```diff
@@ -147,49 +147,84 @@ impl Queue {
...
+                    }
+                    Entry::Vacant(entry) => entry,
+                };
+                if txs_len >= self.max_txs {
+                    return Err((tx, Error::Full));
                 }
-                Entry::Vacant(entry) => entry,
+
+                // Reason for such insertion order is to avoid situation
+                // when poped from the `queue` hash does not yet has corresponding (hash, tx) record in `txs`
```
Comment (appetrosyan) [inline core/src/queue.rs:173]:
```suggestion
                // Insert entry first so that the `tx` popped from `queue` will always have a `(hash, tx)` record in `txs`. 
```

File: core/src/queue.rs [hunk 7]
```diff
@@ -147,49 +147,84 @@ impl Queue {
...
+                        .expect("Inserted just before match");
+                    (err_tx, Error::Full)
+                })
+            }
+        }
+    }
+
+    /// Pop single transaction from the waiting buffer.
+    ///
+    /// Records unsigned transaction in `seen`.
```
Comment (appetrosyan) [inline core/src/queue.rs:193]:
```suggestion
    /// Pop single transaction from the waiting buffer. Record unsigned transaction in `seen`.
```

File: core/src/queue.rs [hunk 8]
```diff
@@ -147,49 +147,84 @@ impl Queue {
...
+        &self,
+        seen: &mut Vec<HashOf<VersionedSignedTransaction>>,
+        wsv: &WorldStateView,
+    ) -> Option<VersionedAcceptedTransaction> {
+        loop {
+            let hash = self.waiting_buffer.pop()?;
+            let entry = match self.txs.entry(hash) {
+                Entry::Occupied(entry) => entry,
+                // As practice shows this code is not `unreachable!()`.
+                // When transactions are submitted quickly it can be reached.
```
Comment (appetrosyan) [inline core/src/queue.rs:204]:
```suggestion
                // FIXME: Reachable under high load. Investigate, see if it's a problem. 
```

File: core/src/queue.rs [hunk 9]
```diff
@@ -147,49 +147,84 @@ impl Queue {
...
-                let (_, err_tx) = self
-                    .txs
-                    .remove(&err_hash)
-                    .expect("Inserted just before match");
-                (err_tx, Error::Full)
-            })
+            match self.check_tx(entry.get(), wsv) {
+                Err(_) => {
+                    entry.remove_entry();
+                    continue;
```
Comment (appetrosyan) [inline core/src/queue.rs:211]: Technically this `continue` is redundant. Given that the other pattern is an early return, just reorder the arms and move this to the bottom.

File: core/src/queue.rs [hunk 10]
```diff
@@ -249,21 +279,115 @@ impl Queue {
...
-        let out = std::iter::from_fn(|| self.pop(&mut seen, wsv))
+        let txs = txs_from_queue
+            .round_robin(txs_from_waiting_buffer)
             .filter(|tx| !transactions_hashes.contains(&tx.hash()))
             .take(self.txs_in_block - transactions.len());
-        transactions.extend(out);
+        transactions.extend(txs);
+
+        for (seen, queue) in [
+            (seen_queue, &self.queue),
```
Comment (appetrosyan) [inline core/src/queue.rs:300]: This function is an unholy mix of functional and imperative. Think we can rewrite parts of it to be one or the other?

File: core/src/queue.rs [hunk 11]
```diff
@@ -249,21 +279,115 @@ impl Queue {
...
+            (seen_waiting_buffer, &self.waiting_buffer),
+        ] {
+            #[allow(clippy::expect_used)]
```
Comment (appetrosyan) [inline core/src/queue.rs:303]:
```suggestion

```
No longer necessary.

File: core/src/queue.rs [hunk 12]
```diff
@@ -249,21 +279,115 @@ impl Queue {
...
+            seen.into_iter()
+                .try_for_each(|hash| queue.push(hash))
+                .expect("As we never exceed the number of transactions pending");
```
Comment (appetrosyan) [inline core/src/queue.rs:306]:
```suggestion
                .expect("Exceeded the number of transactions pending");
```

File: core/src/queue.rs [hunk 13]
```diff
@@ -249,21 +279,115 @@ impl Queue {
...
+        }
+    }
+}
+
+/// Iterator which combine two iterators into the single one in round-robin fashion.
+///
+/// ```ignore
+/// [(a0,a1,a2,..),(b0,b1,b2,..)] -> (a0,b0,a1,b1,a2,b2,..)
+/// ```
+struct RoundRobinIterator<A, B> {
```
Comment (appetrosyan) [inline core/src/queue.rs:316]: Think this might be useful in `iroha_primitives`.

File: core/src/queue.rs [hunk 14]
```diff
@@ -771,4 +1063,54 @@ mod tests {
         assert!(matches!(queue.push(tx, &wsv), Err((_, Error::InFuture))));
         assert_eq!(queue.txs.len(), 1);
     }
+
+    #[test]
```
Comment (appetrosyan) [inline core/src/queue.rs:1067]: Still more reasons to extract this into `iroha_primitives`.

File: core/src/queue.rs (hunk 5 above)
Comment (Erigara) [reply core/src/queue.rs:153]: I think dropping lock is not option here because we need to insert value into the `entry` just after check for size.

File: core/src/queue.rs (hunk 4 above)
Comment (Erigara) [reply core/src/queue.rs:149]: Sorry i'm not quite get your point on this one.

Comment (appetrosyan) [reply core/src/queue.rs:149]: Consider adding:
```rust 
struct Failure {
    tx: VersionedAcceptedTransaction, 
    err: Error
}
```

For clarity and ease of use.

File: core/src/queue.rs (hunk 10 above)
Comment (Erigara) [reply core/src/queue.rs]: Hope it looks better now

File: core/src/queue.rs [hunk 15]
```diff
@@ -137,59 +145,88 @@ impl Queue {
...
-    ///
-    /// Records unsigned transaction in `seen`.
-    #[allow(
-        clippy::expect_used,
-        clippy::unwrap_in_result,
-        clippy::cognitive_complexity
-    )]
-    fn pop(
+    /// Pop single transaction from the queue. Record unsigned transaction in `seen`.
+    fn pop_from_queue(
```
Comment (mversic) [inline core/src/queue.rs:229]: return the naming to just `pop`, obviously it's being popped from the queue

File: core/src/queue.rs [hunk 16]
```diff
@@ -202,20 +239,15 @@ impl Queue {
...
                 Entry::Vacant(_) => continue,
             };
-            if self.check_tx(entry.get(), wsv).is_err() {
+
+            if !self.is_pending(entry.get(), wsv) {
                 entry.remove_entry();
                 continue;
             }
 
             // Transactions are not removed from the queue until expired or committed
```
Comment (mversic) [inline core/src/queue.rs:248]: and why not? Only sumeragi is ever popping transactions out of the queue. It might as well remove them from the queue

File: core/src/queue.rs [hunk 17]
```diff
@@ -137,59 +145,88 @@ impl Queue {
...
-    #[allow(
-        clippy::expect_used,
-        clippy::unwrap_in_result,
-        clippy::cognitive_complexity
-    )]
-    fn pop(
+    /// Pop single transaction from the queue. Record unsigned transaction in `seen`.
+    fn pop_from_queue(
         &self,
         seen: &mut Vec<HashOf<VersionedSignedTransaction>>,
```
Comment (mversic) [inline core/src/queue.rs:231]: `seen` seems useless now? How can you have an unsigned transaction in the queue?

File: core/src/queue.rs [hunk 18]
```diff
@@ -137,59 +145,88 @@ impl Queue {
...
-            self.queue.push(hash).map_err(|err_hash| {
-                let (_, err_tx) = self
-                    .txs
-                    .remove(&err_hash)
-                    .expect("Inserted just before match");
-                (err_tx, Error::Full)
-            })
+            match self.check_tx(entry.get(), wsv) {
+                Ok(MustUse(signature_check)) => {
+                    // Transactions are not removed from the queue until expired or committed
```
Comment (mversic) [inline core/src/queue.rs:215]: again, it's unclear why not exactly

**Review by mversic — CHANGES_REQUESTED** [review]

File: client/tests/integration/multisignature_transaction.rs [hunk 19]
```diff
@@ -12,7 +12,6 @@ use test_network::*;
 use super::Configuration;
 
 #[allow(clippy::too_many_lines)]
-#[ignore = "Multisignature is not working for now. See #2595"]
```
Comment (mversic) [inline client/tests/integration/multisignature_transaction.rs:15]: I think you should reference `#2595` in the PR

File: core/src/queue.rs [hunk 20]
```diff
@@ -137,59 +145,88 @@ impl Queue {
...
-                    // MST case
-                    old_tx
-                        .get_mut()
-                        .as_mut_v1()
-                        .signatures
-                        .extend(tx.as_v1().signatures.clone());
-                    return Ok(());
+    ) -> Result<(), Failure> {
+        match self.check_tx(&tx, wsv) {
+            Err(err) => Err(Failure { tx, err }),
```
Comment (mversic) [inline core/src/queue.rs:154]: I think we should remove transaction from the queue here and maybe in `is_pending` as well

File: primitives/src/round_robin_iter.rs [hunk 21]
```diff
@@ -0,0 +1,141 @@
+//! Contains round-robin iterator and related trait
+
+/// Iterator which combine two iterators into the single one in round-robin fashion.
+///
+/// ```ignore
+/// [(a0,a1,a2,..),(b0,b1,b2,..)] -> (a0,b0,a1,b1,a2,b2,..)
+/// ```
+pub struct RoundRobinIterator<A, B> {
```
[the remark this answers is not in the document]
Comment (Erigara) [reply primitives/src/round_robin_iter.rs:8]: It is cyclic in sense that it pop item from the first iterator, then second, then first again and so on.

File: core/src/queue.rs (hunk 17 above)
Comment (Erigara) [reply core/src/queue.rs:231]: Right, seen is indeed useless in case of `queue`.

File: cli/src/torii/routing.rs [hunk 22]
```diff
@@ -116,7 +116,7 @@ pub(crate) async fn handle_instructions(
     #[allow(clippy::map_err_ignore)]
     queue
         .push(transaction, &sumeragi.wsv_mutex_access())
-        .map_err(|(tx, err)| {
+        .map_err(|queue::Failure { tx, err }| {
```
[the remark this answers is not in the document]
Comment (Erigara) [reply cli/src/torii/routing.rs:119]: @appetrosyan suggested to add `Failure` both options are fine to me.

File: config/src/queue.rs [hunk 23]
```diff
@@ -18,6 +19,8 @@ pub struct Configuration {
     pub maximum_transactions_in_block: u32,
     /// The upper limit of the number of transactions waiting in the queue.
     pub maximum_transactions_in_queue: u32,
+    /// The upper limit of the number of transactions waiting for more signatures.
+    pub maximum_transactions_in_signature_buffer: u32,
```
[the remark this answers is not in the document]
Comment (Erigara) [reply config/src/queue.rs:23]: I think we can split `maximum_transactions_in_queue` in half for normal and multisig transactions, but 2 parameters give us more granular control.

File: core/src/queue.rs [hunk 24]
```diff
@@ -108,24 +121,19 @@ impl Queue {
...
-        if tx.is_expired(self.tx_time_to_live) {
+    ) -> Result<MustUse<bool>, Error> {
+        if tx.is_in_future(self.future_threshold) {
+            Err(Error::InFuture)
+        } else if tx.is_expired(self.tx_time_to_live) {
             Err(Error::Expired)
         } else if tx.is_in_blockchain(wsv) {
             Err(Error::InBlockchain)
         } else {
             tx.check_signature_condition(wsv)
```
[the remark this answers is not in the document]
Comment (Erigara) [reply core/src/queue.rs:136]: Signatures are verified earlier in `AcceptedTransaction::from_transaction` method.

File: core/src/queue.rs (hunk 16 above)
Comment (Erigara) [reply core/src/queue.rs:248]: I think there is 2 reasons: 

1. This way we prevent duplicates from being added into the queue. 
2. Gossiping take transactions from the queue so we want transactions to state here until transactions are in blockchain and we don't want to gossip them anymore.

File: core/src/queue.rs (hunk 18 above)
Comment (Erigara) [reply core/src/queue.rs:215]: replied under another comment

File: core/src/queue.rs (hunk 20 above)
Comment (Erigara) [reply core/src/queue.rs:154]: hmm, but it's `push` method, so transaction is not in the queue yet

File: core/src/queue.rs (hunk 17 above)
Comment (Erigara) [reply core/src/queue.rs:231]: I will update documentation, because we record poped transactions in `seen` as well in order to put then back into the queue.

File: core/src/queue.rs (hunk 20 above)
Comment (mversic) [reply core/src/queue.rs:154]: ok, then in the `is_pending` we should remove transactions?

File: core/src/queue.rs (hunk 16 above)
Comment (mversic) [reply core/src/queue.rs:248]: > This way we prevent duplicates from being added into the queue.

how can we have duplicates in the queue when we use Set/Map

> Gossiping take transactions from the queue so we want transactions to state here until transactions are in blockchain and we don't want to gossip them anymore.

gossiping is different I agree, but any time we move transactions into sumeragi cache they should be removed from the queue immediately

File: core/src/queue.rs (hunk 24 above)
[the remark this answers is not in the document]
Comment (mversic) [reply core/src/queue.rs:136]: `check_signature_condition` documentation is incorrect then

File: config/src/queue.rs (hunk 23 above)
[the remark this answers is not in the document]
Comment (mversic) [reply config/src/queue.rs:23]: this is the reason why I don't like the approach with two queues. I presume that you've tried using only one queue but it didn't work out

[the remark this answers is not in the document]
Comment (Erigara) [reply config/src/queue.rs:23]: Actually approach with one queue works quite nice, with one exception multi-signatures could fill up whole queue preventing ordinary transactions from being added.
I'm not quite with current design too so feel free to suggest any idea.

File: core/src/queue.rs (hunk 16 above)
Comment (Erigara) [reply core/src/queue.rs:248]: > how can we have duplicates in the queue when we use Set/Map

If we are talking about removing transactions from the queue then them should be removed from `Map` as well because otherwise we would end up in the situation where `Map` is never cleared. 

> gossiping is different I agree, but any time we move transactions into sumeragi cache they should be removed from the queue immediately

Then we would need to extend gossiping to partially take transactions from sumeragi cache partially from queue which sounds clumsily to me.

File: core/src/queue.rs (hunk 24 above)
[the remark this answers is not in the document]
Comment (Erigara) [reply core/src/queue.rs:136]: i will update documentation

File: core/src/queue.rs (hunk 20 above)
Comment (Erigara) [reply core/src/queue.rs:154]: `is_pending` is predicate function why we should remove transactions inside it?

Comment (mversic) [reply core/src/queue.rs:154]: ok

File: core/src/queue.rs (hunk 16 above)
Comment (mversic) [reply core/src/queue.rs:248]: > Then we would need to extend gossiping to partially take transactions from sumeragi cache partially from queue which sounds clumsily to me.

valid point

File: core/src/queue.rs [hunk 25]
```diff
@@ -137,59 +145,88 @@ impl Queue {
...
-                    .remove(&err_hash)
-                    .expect("Inserted just before match");
-                (err_tx, Error::Full)
-            })
+            match self.check_tx(entry.get(), wsv) {
+                Ok(MustUse(signature_check)) => {
+                    // Transactions are not removed from the queue until expired or committed
+                    seen.push(hash);
+                    if signature_check {
+                        return Some(entry.get().clone());
```
Comment (mversic) [inline core/src/queue.rs:218]: it might be worth to consider using an `Arc` instead of cloning since what we have is multiple owners (queue and sumeragi) of the same data. This is just a passing thought
 
 this is what I was after when talking about removing transactions from the queue

File: config/src/queue.rs (hunk 23 above)
[the remark this answers is not in the document]
Comment (mversic) [reply config/src/queue.rs:23]: had a lengthy discussion with @Erigara on this matter. I'll make a write up. 2 queue solution remains

**Review by mversic — APPROVED** [review]

File: core/src/queue.rs (hunk 25 above)
Comment (mversic) [reply core/src/queue.rs:222]: @Erigara says: `i’m not sure that this will work out because we still need cloning becasue block contatin all transactions`

this is a good point, but we have `transaction_cache` containing duplicates of transactions. It might still be worth to consider using `Arc` for that reason. On the other hand, I can hardly believe that `transaction_cache` in sumeragi is making any difference - especially after these changes are merged. We should remove it if possbile

Comment (Erigara) [reply core/src/queue.rs:222]: Created #3067

File: core/src/queue.rs (hunk 20 above)
Comment (mversic) [reply core/src/queue.rs:158]: > is_pending is predicate function why we should remove transactions inside it?

is `is_pending` is also used in `all_transactions` but we don't remove from the queue

Comment (Erigara) [reply core/src/queue.rs:158]: This doesn't give much. Removing from map will not really free space for new transactions, because queues still will be occupied with hashes of removed transactions.

**Review by appetrosyan — APPROVED** [review]

**Review by mversic — APPROVED** [review]
