### PR TITLE
[fix] #3777: Validate role registration

### LINKED ISSUE #3777: [bug] Validate role registration
Originally found by me while working on #3775 .

Role registration is not validated, so it's possible to make validator panic by doing the next steps:

1. Create a role with invalid/unexistent permission token
2. Grant this role to someone

Iroha will deny the latest step with internal error. And that happens because role granting expects that all tokens were checked for validity during registration.

We should implement `visit_register_role()` on `DefaultValidator` and add a test.

### PR DESCRIPTION
**Pull request by Arjentix**
## Description

- Default Validator now returns error if decoding failed instead of a panic
- Added role registration validation
- Added test which ensures that role with invalid tokens won't be registered.

### Linked issue

- Closes #3777 

### Benefits

- Validator won't panic on decoding error
- Invalid roles won't pass registration

### Checklist

- [x] I've read `CONTRIBUTING.md`
- [x] I've used the standard signed-off commit format (or will squash just before merging)
- [x] All applicable CI checks pass (or I promised to make them pass later)
- [ ] (optional) I've written unit tests for the code changes
- [ ] I replied to all comments after code review, marking all implemented changes with thumbs up

### CODE REVIEW

**Review by appetrosyan — DISMISSED** [review]

**Review by mversic — DISMISSED** [review]

**Review by mversic — APPROVED** [review]

File: client/tests/integration/roles.rs [hunk 1]
```diff
@@ -137,3 +137,33 @@ fn unregistered_role_removed_from_account() -> Result<()> {
 
     Ok(())
 }
+
+#[test]
+fn role_with_invalid_permissions_is_not_accepted() -> Result<()> {
+    let (_rt, _peer, test_client) = <PeerBuilder>::new().with_port(10_705).start_with_runtime();
```
Comment (ilchu) [inline client/tests/integration/roles.rs:143]: It's been used in `unregistered_role_removed_from_account` test it seems. I know it's frustrating, but I usually just grep for the port through the repo to see if it's mentioned anywhere.

**Review by ilchu — CHANGES_REQUESTED** [review]
Seems some minor lints and a test are failing, can approve after that's fixed.

**Review by appetrosyan — APPROVED** [review]

**Review by mversic — APPROVED** [review]

**Review by appetrosyan — APPROVED** [review]
