### PR TITLE
[fix] #2963: Queue remove transactions correctly 

### LINKED ISSUE #2963: [LONGEVITY BUG] When each peer is running on the only one CPU machine Then iroha throw the error "Failed to push into queue. Queue is full."
### OS and Environment

- Ubuntu
- Docker Hub
- 1 CPU per one peer
- s1.stg1.iroha2.iroha.tech

### GIT commit hash

52dc18cd

### Minimum working example / Steps to reproduce

0. Create a stand where each peer are running on the only one CPU machine, run longevity script and wait. (It is all running now on the longevity stands s1-s5: s1.stg1.iroha2.iroha.tech Just connect to them) 
1.  Send any transaction to the peer http://s1.stg1.iroha2.iroha.tech:8080

### Actual result

```
   0: Failed to create domain
   1: Failed to submit transaction SignedTransaction { payload: Payload { account_id: Id { name: "alice", domain_id: Id { name: "wonderland" } }, instructions: Instructions([Register(RegisterBox { object: EvaluatesTo { expression: Raw(Identifiable(NewDomain(NewDomain { id: Id { name: "ass" }, logo: None, metadata: Metadata { map: {} } }))), _value_type: PhantomData } })]), creation_time: 1669117903206, time_to_live_ms: 100000, nonce: None, metadata: {} }, signatures: {iroha_crypto::signature::SignatureOf<iroha_data_model::transaction::Payload>({ pub_key: ed01207233bfc89dcbd68c19fde6ce6158225298ec1131b6a130d1aeb454c1ab5183c0, payload: DB8116524206673896EEADFECC84C3A664E31F525612ACF6D2D7D4FD7EED4B5662248073935374C8F12A76233EA287F47DCF90B4EF9548A28E4A7D1CAB190A0A })} }
   2: Unexpected transaction response; status: 500 Internal Server Error; response body: Error:
          0: Failed to push into queue    1: Queue is full

```

### Expected result

Successful transaction

### Logs in JSON format

<details>
  <summary>Log contents</summary>
  
  ```
2022-11-22T13:41:26.200040Z  WARN request{method=POST path=/transaction version=HTTP/1.1 remote.addr=139.178.89.153:56486}: iroha::torii::routing: Failed to push into queue error=Queue is full
2022-11-22T13:41:26.200119Z  INFO request{method=POST path=/transaction version=HTTP/1.1 remote.addr=139.178.89.153:56486}: warp::filters::trace: finished processing with success status=500
2022-11-22T13:41:26.200300Z ERROR iroha::torii::routing: Failure during subscription error=Stream error: Iroha version error: Parity SCALE (de)serialization issue
2022-11-22T13:41:34.402620Z  INFO request{method=GET path=/status version=HTTP/1.1 remote.addr=127.0.0.1:56724}: warp::filters::trace: processing request
2022-11-22T13:41:34.402642Z  INFO request{method=GET path=/status version=HTTP/1.1 remote.addr=127.0.0.1:56724}: warp::filters::trace: finished processing with success status=200
2022-11-22T13:42:26.700250Z  INFO request{method=GET path=/events version=HTTP/1.1 remote.addr=139.178.89.153:56490}: warp::filters::trace: processing request
2022-11-22T13:42:26.700250Z  INFO request{method=POST path=/transaction version=HTTP/1.1 remote.addr=139.178.89.153:56488}: warp::filters::trace: processing request
2022-11-22T13:42:26.700454Z  INFO request{method=GET path=/events version=HTTP/1.1 remote.addr=139.178.89.153:56490}: warp::filters::trace: finished processing with success status=101
2022-11-22T13:42:26.700940Z  WARN request{method=POST path=/transaction version=HTTP/1.1 remote.addr=139.178.89.153:56488}: iroha::torii::routing: Failed to push into queue error=Queue is full
2022-11-22T13:42:26.701018Z  INFO request{method=POST path=/transaction version=HTTP/1.1 remote.addr=139.178.89.153:56488}: warp::filters::trace: finished processing with success status=500
2022-11-22T13:42:26.701070Z ERROR iroha::torii::routing: Failure during subscription error=Stream error: Iroha version error: Parity SCALE (de)serialization issue
  ```
</details>

### Who can help to reproduce?

@astrokov7

### Notes

_No response_

### PR DESCRIPTION
**Pull request by Erigara**
### Description of the Change

- Add queue size to metrics;
- Fix Queue to correctly remove transactions;

### Issue

Closes #2963.

### Benefits

- No infinite growth of the transaction queue;
- More diagnostic information in the `/status` response.  

### Possible Drawbacks

None.

### Usage Examples or Tests *[optional]*

Queue size field in the status response: 
```
curl http://127.0.0.1:8180/status
```

### Alternate Designs *[optional]*

Multi-signatures are still not handled correctly by the queue, i would suggest fix this in the separate PR.

### CODE REVIEW

File: core/src/queue.rs [hunk 1]
```diff
@@ -424,18 +418,44 @@ mod tests {
     }
 
     #[test]
+    #[ignore = "Multisignature is not working for now. See #2595"]
     fn push_multisignature_tx() {
```
Comment (Erigara) [inline core/src/queue.rs:422]: This test wasn't test multisignatures at all previously, because in this test we are putting transaction that already pass signature check and then we are adding another signature to it.

File: core/src/queue.rs [hunk 2]
```diff
@@ -601,42 +647,6 @@ mod tests {
         assert_eq!(queue.get_transactions_for_block(&wsv).len(), 0);
     }
 
-    // Queue should only drop transactions which are already committed or ttl expired.
```
Comment (Erigara) [inline core/src/queue.rs:604]: I have decided to get rid of this invariant. 
Because transactions are loaded into the sumeragi transaction cache and it's waste of resources to repeatedly bombard transaction cache with transaction duplicates.

File: core/src/queue.rs [hunk 3]
```diff
@@ -209,75 +207,67 @@ impl Queue {
...
-
-    /// Pop a single transaction.
-    ///
-    /// Unlike [`Self::pop`], unsigned transactions are not recorded.
-    #[allow(
-        clippy::expect_used,
-        clippy::unwrap_in_result,
-        clippy::cognitive_complexity
-    )]
-    pub fn pop_without_seen(&self, wsv: &WorldStateView) -> Option<VersionedAcceptedTransaction> {
```
Comment (Erigara) [inline core/src/queue.rs:231]: This method was root cause of the issue.
Because this methods doesn't remove `(hash,tx)` record from the `queue.txs` and doesn't put back seen transactions to be deleted later, when `tx` would be in the blockchain.

File: core/src/queue.rs [hunk 4]
```diff
@@ -209,75 +207,67 @@ impl Queue {
...
     pub fn get_transactions_for_block(
         &self,
         wsv: &WorldStateView,
     ) -> Vec<VersionedAcceptedTransaction> {
+        let mut transactions = Vec::with_capacity(self.txs_in_block);
+        self.put_transactions_for_block_into(wsv, &mut transactions);
+        transactions
+    }
+
+    /// Put transaction into provided vector till they fill whole block or till the end of queue.
```
Comment (outoftardis) [inline core/src/queue.rs:241]:
```suggestion
    /// Put transactions into provided vector until they fill the whole block or there are no more transactions in the queue.
```

**Comment by mversic** [comment]
something's wrong with issue id in the title. It actually references a PR instead. Probably a github issue?

**Comment by Erigara** [comment]
> something's wrong with issue id in the title. It actually references a PR instead. Probably a github issue? But even the `Close #num` references the PR, you can fix that

oh, sure

File: core/src/queue.rs [hunk 5]
```diff
@@ -424,18 +416,44 @@ mod tests {
     }
 
     #[test]
+    #[ignore = "Multisignature is not working for now. See #2595"]
```
Comment (Arjentix) [inline core/src/queue.rs:419]: So I believe you have fixed the test? We can unignore it?

File: core/src/queue.rs [hunk 6]
```diff
@@ -220,64 +219,53 @@ impl Queue {
...
+            // Normally we would not expect to receive transaction duplicate from the queue and `transaction_hashes.contains(tx.hash())` would be enough
+            // However there might be situation when we poped transaction from the queue and just after that we received its duplicate
+            .filter(|tx| transactions_hashes.insert(tx.hash()))
+            .take(self.txs_in_block - transactions.len());
+        transactions.extend(out);
 
         #[allow(clippy::expect_used)]
         seen.into_iter()
             .try_for_each(|hash| self.queue.push(hash))
             .expect("As we never exceed the number of transactions pending");
```
Comment (QuentinI) [inline core/src/queue.rs:268]: Unrelated to this PR, but I really don't get where this guarantee comes from.

File: core/src/queue.rs [hunk 7]
```diff
@@ -695,13 +739,9 @@ mod tests {
         push_txs_handle.join().unwrap();
         get_txs_handle.join().unwrap();
 
-        // Last update for queue to drop invalid txs.
-        let _unused = queue.get_transactions_for_block(&wsv);
-
         // Validate the queue state.
         let array_queue: Vec<_> = core::iter::repeat_with(|| queue.queue.pop())
```
Comment (QuentinI) [inline core/src/queue.rs:743]: `from_fn` again

File: core/src/queue.rs [hunk 8]
```diff
@@ -220,64 +219,53 @@ impl Queue {
...
+    /// Return the number of transactions in the queue.
     pub fn tx_len(&self) -> usize {
         self.txs.len()
     }
 
     /// Gets transactions till they fill whole block or till the end of queue.
     ///
     /// BEWARE: Shouldn't be called in parallel with itself.
-    #[allow(clippy::missing_panics_doc, clippy::unwrap_in_result)]
     pub fn get_transactions_for_block(
```
Comment (QuentinI) [inline core/src/queue.rs:230]: We can make this private, since it's used only in tests as far as I see, and swap name length with `put_transactions_for_block_into`.

**Review by QuentinI — DISMISSED** [review]
Sorry for taking so long, wanted to make sure I understood what's going on.

File: core/src/queue.rs (hunk 5 above)
Comment (QuentinI) [reply core/src/queue.rs:419]: @Arjentix not until #3043, which [does unignore](https://github.com/hyperledger/iroha/pull/3043/commits/98b8242268abbeaa5a77906308d15baf842b5123#diff-e6b9f4fffa1a86e9147aab986d762b234878cfa7a1900ee45487d5d9ca91a156L419) it.

File: core/src/queue.rs [hunk 9]
```diff
@@ -220,64 +219,53 @@ impl Queue {
...
+        let mut transactions_hashes: HashSet<HashOf<VersionedSignedTransaction>> = transactions
+            .iter()
+            .map(VersionedAcceptedTransaction::hash)
+            .collect();
         let out = std::iter::repeat_with(|| self.pop(&mut seen, wsv))
-            .take_while(Option::is_some)
-            .map(Option::unwrap)
-            .take(self.txs_in_block)
-            .collect::<Vec<_>>();
+            .map_while(core::convert::identity)
```
[the remark this answers is not in the document]
Comment (QuentinI) [reply core/src/queue.rs:258]: Same could be expressed as just `from_fn` I believe

File: core/src/queue.rs (hunk 7 above)
Comment (Erigara) [reply core/src/queue.rs:743]: yeap, good suggestion, i was unaware of this function!

File: core/src/queue.rs [hunk 10]
```diff
@@ -220,64 +219,53 @@ impl Queue {
...
+            // Normally we would not expect to receive transaction duplicate from the queue and `transaction_hashes.contains(tx.hash())` would be enough
+            // However there might be situation when we poped transaction from the queue and just after that we received its duplicate
+            .filter(|tx| transactions_hashes.insert(tx.hash()))
```
[the remark this answers is not in the document]
Comment (Erigara) [reply core/src/queue.rs:261]: Hm, i'm not sure that this method would feet here since, we have initial set of hashes which came from transactions vector.

File: core/src/queue.rs [hunk 11]
```diff
@@ -220,64 +219,53 @@ impl Queue {
...
         wsv: &WorldStateView,
     ) -> Vec<VersionedAcceptedTransaction> {
+        let mut transactions = Vec::with_capacity(self.txs_in_block);
+        self.put_transactions_for_block_into(wsv, &mut transactions);
+        transactions
+    }
+
+    /// Put transactions into provided vector until they fill the whole block or there are no more transactions in the queue.
+    ///
+    /// BEWARE: Shouldn't be called in parallel with itself.
```
[the remark this answers is not in the document]
Comment (Erigara) [reply core/src/queue.rs:241]: I believe such behavior came from locking  behavior of `DashMap`.
But i don't think that it's problem currently since `Sumeragi` work in single tread.

File: core/src/queue.rs (hunk 8 above)
Comment (Erigara) [reply core/src/queue.rs:230]: What do you mean by "swap name length"?

File: core/src/queue.rs (hunk 6 above)
Comment (Erigara) [reply core/src/queue.rs:268]: I believe such guarantee came from the fact that we never pushing back more transactions that was poped previously (so there is should be enough space for them).

File: core/src/queue.rs (hunk 8 above)
Comment (QuentinI) [reply core/src/queue.rs:230]: Oh, sorry. I meant, we could rename them so that public one is shorter.

File: core/src/queue.rs (hunk 6 above)
Comment (QuentinI) [reply core/src/queue.rs:268]: Another thread could fill up the queue in the meantime though

File: core/src/queue.rs (hunk 8 above)
Comment (Erigara) [reply core/src/queue.rs:230]: Do you have any suggestion how we can make function name shorter? 

Because `put_transactions_for_block_into` and `get_transactions_for_block` a bit different in the first case we put transactions in the provided buffer and in the second case we return new vector.

File: core/src/queue.rs (hunk 6 above)
Comment (Erigara) [reply core/src/queue.rs:268]: I suppose not because we don't remove transaction from `txs` map and inside `push` we have check for `txs` size.

Comment (QuentinI) [reply core/src/queue.rs:268]: Oh, so we don't remove signed txs from the map until they're in blockchain. Got it, thanks!

File: core/src/queue.rs (hunk 8 above)
Comment (QuentinI) [reply core/src/queue.rs:230]: We could make `put_transactions_for_block_into` the new `get_transactions_for_block` and rename the one that provides the Vec to something like `collect_transactions_for_block`, or better yet, also move it to tests mod, since as far as I understand it's a convenience fn just for tests.

Comment (QuentinI) [reply core/src/queue.rs:230]: Sorry, I'm bad with words today. Basically
`get_transactions_for_block` ->  `tests::collect_transactions_for_block` or something
`put_transactions_for_block_into` -> `get_transactions_for_block`

Comment (Erigara) [reply core/src/queue.rs:230]: good suggestion, i will do this

File: core/src/queue.rs [hunk 12]
```diff
@@ -220,64 +219,51 @@ impl Queue {
...
-            .take_while(Option::is_some)
-            .map(Option::unwrap)
-            .take(self.txs_in_block)
-            .collect::<Vec<_>>();
+        let transactions_hashes: HashSet<HashOf<VersionedSignedTransaction>> = transactions
+            .iter()
+            .map(VersionedAcceptedTransaction::hash)
+            .collect();
+        let out = std::iter::from_fn(|| self.pop(&mut seen, wsv))
+            .filter(|tx| !transactions_hashes.contains(&tx.hash()))
```
Comment (Erigara) [inline core/src/queue.rs:259]: On the second look i have discovered that `transactions.insert` is redundant here, because since we store transactions in the queue untill expired or in the blockchain in would be impossible to receive duplicate transaction from the queue.

**Review by Arjentix — APPROVED** [review]

File: core/src/queue.rs (hunk 10 above)
[the remark this answers is not in the document]
Comment (Arjentix) [reply core/src/queue.rs]: Indeed, I see. And new version with `contains()` looks nice to me

**Review by QuentinI — APPROVED** [review]
