### PR TITLE
fix(schema): rename `type_` to `type` in schema

### LINKED ISSUE #4770: Rename `type_` to `type` in `schema.json`
`type` being a reserved Rust token should not affect the schema. If it is still `type_` internally, consider patching `IntoSchema` to support something like `rename` attribute.

_Originally posted by @0x009922 in https://github.com/hyperledger/iroha/pull/4741#discussion_r1651576375_

### PR DESCRIPTION
**Pull request by mversic**
## Description

* add support for handling `serde(rename)` attributes with `IntoSchema`
* attach `serde(rename = "type")` to `type_` fields in data model

### Linked issue

Closes #4770

### Checklist

- [ ] I've read `CONTRIBUTING.md`
- [ ] I've used the standard signed-off commit format (or will squash just before merging)
- [ ] All applicable CI checks pass (or I promised to make them pass later)
- [ ] (optional) I've written unit tests for the code changes
- [ ] I replied to all comments after code review, marking all implemented changes with thumbs up

### CODE REVIEW

File: data_model/src/asset.rs [hunk 1]
```diff
@@ -114,6 +114,7 @@ mod model {
         pub id: AssetDefinitionId,
         /// Type of [`AssetValue`]
         #[getset(get_copy = "pub")]
```
Comment (mversic) [inline data_model/src/asset.rs:116]: note that getter in Rust is still `AssetDefinition::type_(&self)`

**Review by nxsaken — APPROVED** [review]

**Review by Erigara — APPROVED** [review]
